### PR TITLE
Fix ResourceLimitExceeded for cloudwatchLog event

### LINKED ISSUE #3447: Fix cloudwatchLog event with the case that facing a resource limit exceeded
When using `cloudwatchLog` event, the deployment will fail with an error that a resource limit exceeded if you replace the `logGroup` name of one function with the `logGroup` name of another function in your `serverless.yml` file and run `serverless deploy`

This is caused by the fact that CloudFormation tries to attach the new subscription filter before detaching the old one. CloudWatch Logs only support one subscription fitlter per log group as you can read in the documentation about [CloudWatch Logs Limits](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html).

We should fix it in upcoming release.

cc @pmuens

### PR DESCRIPTION
**Pull request by rdsedmundo**
## What did you implement:

Closes #3447

## How did you implement it:

As per CloudFormation nature, it won't delete a resource before trying to create a new one firstly, and the problem come up once it tries to create a new subscription filter, as it will hit CloudWatch's hard limit of 1 subscription filter per log group (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html). The unique option to make it work is to manually delete the resource and then run the CF update again -- since the resource is gone CF is going to be able to create the new one, and also delete the old as its definition is not on template anymore. The idea is to delete the subscription filter whenever the destination function ARN is different from the one that was just configured at `serverless.yml`.

I haven't added UT at all because I'd like to know firstly if this implementation makes sense. It worked for all situations that were pointed out by @ztmdsbt on #3447. 

## How can we verify it:

1. Create a project with `serverless.yml` with the following configuration: https://gist.github.com/rdsedmundo/556d8b6ed7fc119f13b8c54bf47595fa. `handler.js` content can be whatever, e.g just a hello world:
```
'use strict';

module.exports.hello = async (event, context) => {
  return { message: 'Go Serverless v1.0! Your function executed successfully!', event };
};
```
2. Change `cloudwatchLog` log group interchangeably (set test-1 for the first function, then test-2 to the 3rd, etc), change function definitions orders (add hello first, then hello2 at the end, etc), create new functions at the beginning of the function definitions, at the middle, etc.
3. If you're using the version from this PR you won't face the "ResourceLimitExceeded" error as we got on `master` (reference: https://serverless.com/framework/docs/providers/aws/events/cloudwatch-log#current-gotchas).

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by bryanrcampbell** [comment]
Thanks for doing this @rdsedmundo! This would solve an extremely irritating problem we have with cloudwatch log subscriptions.

File: lib/plugins/aws/package/compile/events/cloudWatchLog/index.js [hunk 1]
```diff
@@ -15,133 +15,206 @@ class AwsCompileCloudWatchLogEvents {
...
+   * If we change a cloudwatchLog event entry to add a subscription filter to a log group
+   * that already had one before, it will throw an error because CloudFormation firstly
+   * tries to create and replace the new subscription filter (therefore hitting the limit)
+   * before deleting the old one. This precompile process aims to delete existent
+   * subscription filters of functions that a new filter was provided, by checking the
+   * current ARN with the new one that will be generated.
+   * See: https://git.io/fpKCM
+  */
+  checkAndFixLogGroupSubscriptionFilterResourceLimitExceeded({ logGroupName, functionName }) {
+    return new Promise((resolve, reject) => {
```
Comment (dschep) [inline lib/plugins/aws/package/compile/events/cloudWatchLog/index.js]: Could you please rewrite this with out a `new Promise`? Namley, `cloudWatchLogs.describeSubscriptionFilters({ logGroupName }).promise()` is already returning a promise, so there's no reason to wrap that in `new Promise((resolve, reject) => {/*stuff*/})`

Comment (rdsedmundo) [reply lib/plugins/aws/package/compile/events/cloudWatchLog/index.js]: I can't just return this promise directly because the flow may not even reach to there when:

- the describeSubscriptionFilters call fails (log group doesn't exist yet)
- getAccountId call fails

**Comment by rdsedmundo** [comment]
```
what potential issues might there be with manually deleting the subscription before then updating the cfn stack?
```

That's exactly what I was expecting to hear from the serverless team as a feedback.

From what I understand deleting outside CloudFormation is not ideal, but in the case of the subscription filters, when there's a change on the function target CloudFormation will remove the old definition from the template, so the script is removing it by hand, but this definition is not also on the template anymore in that circumstance.

From the tests that I run I saw no issue or inconsistency on the CloudFormation at the console. Run it multiple times and everything went fine.

It would be great to have an input of someone with better knowledge on that here.

File: lib/plugins/aws/package/compile/events/cloudWatchLog/index.js [hunk 2]
```diff
@@ -15,133 +15,206 @@ class AwsCompileCloudWatchLogEvents {
...
+      const region = this.provider.getRegion();
+      const serviceName = this.serverless.service.getServiceName();
+      const stage = this.provider.getStage();
+      const cloudWatchLogs = new this.provider.sdk.CloudWatchLogs({ region });
+
+      cloudWatchLogs
+        .describeSubscriptionFilters({ logGroupName })
+        .promise()
+        .then(({ subscriptionFilters: [subscriptionFilter] }) => {
```
Comment (dschep) [inline lib/plugins/aws/package/compile/events/cloudWatchLog/index.js]: What about if a log has multiple subscriptionFilter?

Comment (rdsedmundo) [reply lib/plugins/aws/package/compile/events/cloudWatchLog/index.js]: So, that's exactly the limitation -- it's not possible to have more than one. I thought about that and didn't understand why this request returns an array and is even paginated if there's a hard limit of a single sub filter.

File: lib/plugins/aws/package/compile/events/cloudWatchLog/index.js (hunk 1 above)
Comment (dschep) [reply lib/plugins/aws/package/compile/events/cloudWatchLog/index.js]: Still shouldn't be an issue (note, I've also modified it to get account & subscription filters in parallel):
```javascript
    const region = this.provider.getRegion();
    const serviceName = this.serverless.service.getServiceName();
    const stage = this.provider.getStage();
    const cloudWatchLogs = new this.provider.sdk.CloudWatchLogs({ region });
    return Promise.all([
        cloudWatchLogs.describeSubscriptionFilters({ logGroupName }).promise(),
        this.provider.getAccountId()])
      .then(([{ subscriptionFilters: [subscriptionFilter] }, accountId]) => {
        // log group doesn't have any subscription filters currently
        if (!subscriptionFilter) {
          return;
        }
        const { destinationArn: oldDestinationArn, filterName } = subscriptionFilter;
        // eslint-disable-next-line max-len
        const newDestinationArn = `arn:aws:lambda:${region}:${accountId}:function:${serviceName}-${stage}-${functionName}`;
            // everything is fine, just resolve
        if (oldDestinationArn === newDestinationArn) {
            return;
        }
        /*
        if the destinations functions' arns doesn't matter, we need to delete the current
        subscription filter to prevent the resource limit exceeded error to happen
        */
        return cloudWatchLogs.deleteSubscriptionFilter({ logGroupName, filterName }).promise();
      })
      /*
        it will throw when trying to get subscription filters of a log group that was just added
        to the serverless.yml (therefore not created in AWS yet), we can safely ignore this error
        and just resolve
      */
      .catch(() => null);
```

Comment (rdsedmundo) [reply lib/plugins/aws/package/compile/events/cloudWatchLog/index.js]: Ah, you're right! I'll change. I wish we had support to `async/await` to be honest, but we need to have support for NodeJS 4/6 yet here, so it shouldn't be available soon... anyways, I'll make that change.

I'm also thinking right now that it is not necessary to get the accountId every time. I can get it outside and pass as a parameter, I'll rework on this promise flow entirely.

**Comment by rdsedmundo** [comment]
Yeah, although on this situation it doesn't make difference as if the destinationArns are different the resource would have been deleted either way later, I agree that it's more prudent to let CloudFormation to handle that.

But instead of this CLI option, I'd prefer adding some extra configuration at the `cloudWatchLog` event, otherwise, I'd need to pass this option every time and it may get annoying. What do you think? I can also still keep with the check and provide a warning on a situation that probably an error will be triggered (in case of the flag not being provided and the deletion would have been necessary).

File: lib/plugins/aws/package/compile/events/cloudWatchLog/index.js (hunk 2 above)
Comment (dschep) [inline lib/plugins/aws/package/compile/events/cloudWatchLog/index.js]: Don't use destructuring as the framework still supports Node v4.

File: lib/plugins/aws/package/compile/events/cloudWatchLog/index.js [hunk 3]
```diff
@@ -15,133 +15,206 @@ class AwsCompileCloudWatchLogEvents {
...
+          // log group doesn't have any subscription filters currently
+          if (!subscriptionFilter) {
+            resolve();
+            return;
+          }
+
+          this.provider.getAccountId()
+            .then((accountId) => {
+              const { destinationArn: oldDestinationArn, filterName } = subscriptionFilter;
```
Comment (dschep) [inline lib/plugins/aws/package/compile/events/cloudWatchLog/index.js]: here too

**Comment by rdsedmundo** [comment]
@dschep I submitted a new version without seeing your comments (was working on them while you're reviewing again). I'll address then later and squash the commits. Meanwhile, I added some UT tests. I'm more familiar using `Jest` so I might have not written some of them in the best way, please feel free to suggest improvements.

**Comment by dschep** [comment]
You shouldn't have to check if it's `sls deploy` explicitly. I  recommend moving the check out of the compile functions & in to the deploy functions. Putting it in [`/lib/plugins/aws/deploy/lib/checkForChanges.js`](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/checkForChanges.js) makes the most sense, I think.

**Comment by dschep** [comment]
The code checking if its need & then deleting the existing subscription should live in `checkForChanges`. You don't need to explicitly worry about `deploy` vs `package`. `package` calls the compile modules(this generates the cloudformation template). `deploy` and calls `package` before moving onto the deploy work, including `checkForChanges`.

**Comment by rdsedmundo** [comment]
@dschep Changes done. I went ahead and excluded the old commits for avoiding noise on the PR.

File: lib/plugins/aws/deploy/lib/checkForChanges.js [hunk 4]
```diff
@@ -112,4 +120,107 @@ module.exports = {
...
+          subscription filter to prevent the resource limit exceeded error to happen
+        */
+        return cloudWatchLogsSdk
+          .deleteSubscriptionFilter({ logGroupName, filterName }).promise();
+      })
+      /*
+        it will throw when trying to get subscription filters of a log group that was just added
+        to the serverless.yml (therefore not created in AWS yet), we can safely ignore this error
+      */
+      .catch(() => undefined);
```
Comment (dschep) [inline lib/plugins/aws/deploy/lib/checkForChanges.js]: Oh, nevermind, this addresses my 'one last thought', right?

Comment (rdsedmundo) [reply lib/plugins/aws/deploy/lib/checkForChanges.js]: Yes, that's right.

**Comment by rdsedmundo** [comment]
By the way, the tests failed randomly it seems, AwsInvokeLocal, I don't think it's related to those changes.

**Comment by dschep** [comment]
Yeah. I don't worry too much about windows tests failures so long as most of the sub-builds pass.

**Comment by dschep** [comment]
Me remembering to merge this is what's missing 😬 

:shipit: !!
