### PR TITLE
Govcloud custom resource fix

### LINKED ISSUE #6995: Custom Resource does not support AWS US Gov Cloud Region (us-gov-west-1)
# Bug Report

## Description

1. What did you do?
Attempting to deploy a serverless application in `us-gov-west-1` that utilizes Custom Resources (an AWS Lambda function with event trigger on existing S3 bucket. 

1. What happened?
The CloudFormation stack hangs for one hour on deploying the Custom S3 resource and rolls back.  I noticed errors occurring on the Custom Resource lambda, but no logging was present.  After editing the serverless cloudformation to add logging rights to the custom resource lambda, I noticed the error is due to `/lib/plugins/aws/customResource/utils.js` not supporting Lambda ARN pattern for `us-gov-west-1`.  The offending lines in the code are [here](https://github.com/serverless/serverless/blob/1249361035362c8fc33c6ade7c3b3f09bea34f4d/lib/plugins/aws/customResources/resources/utils.js#L59) and [here](https://github.com/serverless/serverless/blob/1249361035362c8fc33c6ade7c3b3f09bea34f4d/lib/plugins/aws/customResources/resources/utils.js#L64)

The lambda arn schema in Gov Cloud is a bit different than other regions:
`arn:aws-us-gov:lambda:us-gov-west-1:XXXXXXXXXX:function:s3-asset-scanner-app-3-dev-scanner`

The error from custom resource lambda:
```
START RequestId: 3119d862-248a-45cb-b343-a3ec830ec496 Version: $LATEST

2019-11-21T18:31:34.257Z	3119d862-248a-45cb-b343-a3ec830ec496	ERROR	Invoke Error 	{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property '0' of null",
    "stack": [
        "TypeError: Cannot read property '0' of null",
        "    at getEnvironment (/var/task/utils.js:67:19)",
        "    at create (/var/task/s3/handler.js:19:33)",
        "    at handler (/var/task/s3/handler.js:9:12)",
        "    at Runtime.handler (/var/task/utils.js:78:28)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}

END RequestId: 3119d862-248a-45cb-b343-a3ec830ec496
REPORT RequestId: 3119d862-248a-45cb-b343-a3ec830ec496	Duration: 3.48 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 84 MB	Init Duration: 312.26 ms	
START RequestId: 3119d862-248a-45cb-b343-a3ec830ec496 Version: $LATEST
2019-11-21T18:32:33.423Z	3119d862-248a-45cb-b343-a3ec830ec496	ERROR	Invoke Error 	{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property '0' of null",
    "stack": [
        "TypeError: Cannot read property '0' of null",
        "    at getEnvironment (/var/task/utils.js:67:19)",
        "    at create (/var/task/s3/handler.js:19:33)",
        "    at handler (/var/task/s3/handler.js:9:12)",
        "    at Runtime.handler (/var/task/utils.js:78:28)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
END RequestId: 3119d862-248a-45cb-b343-a3ec830ec496
REPORT RequestId: 3119d862-248a-45cb-b343-a3ec830ec496	Duration: 6.18 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 84 MB	
```

1. What should've happened?

Stack should have deployed correctly, and the supporting Custom Resource lambda should properly parse ARNs in US Gov Cloud regions, such as **`arn:aws-us-gov:lambda:us-gov-west-1**

1. What's the content of your `serverless.yml` file?

```yaml
service: s3-asset-scanner-app-3

provider:
  name: aws
  endpointType: REGIONAL  
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'} ## dev stage is default, can be overridden by CLI (for ex: serverless deploy --stage prod
  region: us-gov-west-1
  profile: ${opt:profile, 'pgfs-ci-service'} ##This must match a valid IAM profile in ~/.aws/credentials
  #profile name default is 'pgfs-ci-service', can be interpolated using the stage for different environments, or overridden by the CLI

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  s3BucketArn: 'arn:aws-us-gov:s3:::REDACTED'
  s3BucketName: 'REDACTED'
  allowedMIMETypes: 'image/png,image/jpeg,image/gif'
  notificationTopicArn: 'sadfsdf'

package:
  exclude:
    - node_modules/**/*

functions:
  scanner:
    handler: handler.scanner
    memorySize: 128
    environment:
      S3_BUCKET_ARN: ${self:custom.s3BucketArn}
      S3_BUCKET_NAME: ${self:custom.s3BucketName}
      ALLOWED_MIME_TYPES: ${self:custom.allowedMIMETypes}
      NOTIFICATION_TOPIC_ARN: ${self:custom.notificationTopicArn}
    events:
      - s3:
          bucket: REDACTED #TODO Parameterize this later
          event: s3:ObjectCreated:*
          existing: true         

```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

serverless version / environment info:

```ps
  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.15.1
     Framework Version:         1.58.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

serverless deploy:

```ps
$ serverless deploy --region us-gov-west-1 --stage dev --verbose
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - s3-asset-scanner-app-2-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - s3-asset-scanner-app-2-dev
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service s3-asset-scanner-app-2.zip file to S3 (2.27 KB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - s3-asset-scanner-app-2-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ScannerLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ScannerLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ScannerLogGroup
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ScannerLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ScannerLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - ScannerLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ScannerLambdaVersioneApviq3i7hGfN1vukw8srmJo9fJueqjd0L2VNHoNrVw
CloudFormation - CREATE_IN_PROGRESS - Custom::S3 - ScannerCustomS31
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ScannerLambdaVersioneApviq3i7hGfN1vukw8srmJo9fJueqjd0L2VNHoNrVw
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - ScannerLambdaVersioneApviq3i7hGfN1vukw8srmJo9fJueqjd0L2VNHoNrVw
Pulling docker image gitlab/gitlab-runner-helper:x86_64-05161b14 ...
ERROR: Job failed: execution took longer than 1h0m0s seconds
```
Similar or dependent issues:

- None that I know of

### PR DESCRIPTION
**Pull request by jmb12686**
## What did you implement

Closes #6995 .  Fix GovCloud Region ARN and Environment parsing utilities in the AWS Plugin for Custom Resources.

## How can we verify it

Deploy a serverless function to `us-gov-west-1` or `us-gov-east-1`  that uses S3 Bucket events on an existing S3 bucket, for example:

```yml
service:
  name: myService
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-gov-west-1
functions:
  users:
    handler: users.handler
    events:
      - s3:
          bucket: legacy-photos
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
          existing: true

```
## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test-ci` --> Run all validation checks on proposed changes
- `npm run lint-updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check-updated` --> Check if updated files adhere to Prettier config
- `npm run prettify-updated` --> Prettify all the updated files

</details>

- [x] Write and run all tests
- [x] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

File: lib/plugins/aws/customResources/resources/utils.js [hunk 1]
```diff
@@ -56,13 +56,22 @@ function response(event, context, status, data = {}, err) {
 }
 
 function getLambdaArn(region, accountId, functionName) {
-  return `arn:aws:lambda:${region}:${accountId}:function:${functionName}`;
+  let awsNode = 'aws';
+  if (region === 'us-gov-west-1' || region === 'us-gov-east-1') {
+    awsNode = 'aws-us-gov';
+  }
+  return `arn:${awsNode}:lambda:${region}:${accountId}:function:${functionName}`;
```
Comment (medikoo) [inline lib/plugins/aws/customResources/resources/utils.js]: I believe we should rather rely on [AWS::Partition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-partition) as e.g. we already do here: https://github.com/serverless/serverless/blob/c77cf010718a243bb98b922c4b9ba7e6c6318a62/lib/plugins/aws/customResources/index.js#L140

As there are other region cases which require that (e.g. china regions)

Comment (jmb12686) [reply lib/plugins/aws/customResources/resources/utils.js]: Ok I can make this change to utilize the AWS partition

Comment (jmb12686) [reply lib/plugins/aws/customResources/resources/utils.js]: Actually, in reading the the code that uses these utils functions, I do not believe we have access to leverage the `AWS::Partition`?

When this code invoked, we are in a Lambda execution context, not in CloudFormation templating/execution context.

Comment (medikoo) [reply lib/plugins/aws/customResources/resources/utils.js]: Indeed, in that case we need to somehow reliably resolve a partition for current region.
Still at this point I'm not sure how to do that (I see it's not available as env variable)

Comment (maafk) [reply lib/plugins/aws/customResources/resources/utils.js]: You should be able to gather the AWS partition from the `invokedFunctionArn` in the [context](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html) object, similar to how we can get the partition [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L516)

Comment (jmb12686) [reply lib/plugins/aws/customResources/resources/utils.js]: Nice, ok I'll try that.  I probably won't be able to get it done today, but this weekend hopefully.  Thanks!

File: lib/plugins/aws/customResources/resources/utils.js [hunk 2]
```diff
@@ -56,13 +56,22 @@ function response(event, context, status, data = {}, err) {
...
 }
 
 function getEnvironment(context) {
```
Comment (maafk) [inline lib/plugins/aws/customResources/resources/utils.js]: Perhaps replace this function to gather the partition in the regex

```javascript
function getEnvironment(context) {
  const arn = context.invokedFunctionArn.match(
    /^arn:(aws[\w-]*).*:lambda:(\w+-\w+-\d+):(\d+):function:(.*)$/
  );
  return {
    LambdaArn: arn[0],
    Partition: arn[1],
    Region: arn[2],
    AccountId: arn[3],
    LambdaName: arn[4],
  };
}
```

Comment (medikoo) [reply lib/plugins/aws/customResources/resources/utils.js]: Good suggestion it's `getEnvironment` which should resolve partition

Comment (jmb12686) [reply lib/plugins/aws/customResources/resources/utils.js]: Right, that's exactly what I just attempted to do.  However, the region for GovCloud has a different format: `us-gov-west-1` and `us-gov-east-1` that is incompatible with the existing regex that extracts region.  Any suggestions?

This works for govcloud, but not for regular public regions
```js
/^arn:(aws[\w-]*).*:lambda:(\w+-\w+-\w+-\d+):(\d+):function:(.*)$/
```

This works for public regions, but not for govcloud:
```js
/^arn:(aws[\w-]*).*:lambda:(\w+-\w+-\d+):(\d+):function:(.*)$/
```

Comment (maafk) [reply lib/plugins/aws/customResources/resources/utils.js]: Oh good point!

In that case I think adjusting the regex in this way should work

`/^arn:(aws[\w-]*).*:lambda:([\w+-]{2,}\d+):(\d+):function:(.*)$/`

**Comment by jmb12686** [comment]
I made the modifications requested.  I also found 3 additional locations under the `/lib/plugins/aws/customResources/resources/*` tree that were not properly handling AWS Partition for US GovCloud.  I went ahead and created a utility function to properly parse from Region -> Partition for the `permissions.js` scripts.

File: lib/plugins/aws/customResources/resources/utils.js [hunk 3]
```diff
@@ -55,22 +55,34 @@ function response(event, context, status, data = {}, err) {
...
 }
 
+function getPartition(region) {
+  let partition = 'aws';
+  if (region && /^cn-/.test(region)) {
+    partition = 'aws-cn';
+  } else if (region && /^us-gov-/.test(region)) {
+    partition = 'aws-us-gov';
+  }
+  return partition;
```
Comment (maafk) [inline lib/plugins/aws/customResources/resources/utils.js]: There are other [less known](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L5143) partitions, but this function handles 99% of use cases. I'm happy to open a new PR once this is merged to try and address the other possible partitions

Comment (jmb12686) [reply lib/plugins/aws/customResources/resources/utils.js]: Since I can actually functionally test against `us-gov-west-1` I feel comfortable making the changes within this PR.  I'd rather not personally attempt to fix partition parsing for the entire code base (for which I am pretty unfamiliar with).

**Comment by jmb12686** [comment]
I was able to test this PR's changes successfully in `us-gov-west-1` region with the scenario I reported in bug #6995 .  Let me know if there's anything I need to do to get this approved and merged into master. 
 Thanks.

File: lib/plugins/aws/customResources/resources/utils.js [hunk 4]
```diff
@@ -55,22 +55,34 @@ function response(event, context, status, data = {}, err) {
...
-    AccountId: arn[2],
-    LambdaName: arn[3],
+    Partition: arn[1],
+    Region: arn[2],
+    AccountId: arn[3],
+    LambdaName: arn[4],
   };
 }
 
+function getPartition(region) {
```
Comment (medikoo) [inline lib/plugins/aws/customResources/resources/utils.js]: I think this function should not be introduced. Instead in all places where it's used, we should take _partition_ in arguments together with a _region_ (and both via `getEnvironment` hould be resolved in handler context)

Comment (jmb12686) [reply lib/plugins/aws/customResources/resources/utils.js]: @medikoo , I'm not exactly sure what you you would like changed here?  I am trying to calculate Partition from a given region which I discovered was incorrectly being parsed.  This function is used in 3 locations, where Partition was being parsed from Region to form a non-lambda ARN.  See the three locations here, which were not properly handling GovCloud:
line 17  - lib/plugins/aws/customResources/resources/cognitoUserPool/lib/permissions.js
line 17 - lib/plugins/aws/customResources/resources/eventBridge/lib/permissions.js
line 17 - lib/plugins/aws/customResources/resources/s3/lib/permissions.js

I wanted to ensure that all use-cases for Custom Resources are now properly handled by the framework for GovCloud, which this solves.  

Thank you.

Comment (jmb12686) [reply lib/plugins/aws/customResources/resources/utils.js]: After looking thru, I may get what you are saying, please correct me if i'm wrong.  You are suggesting that I pass Partition into the permissions.js addPermission() / removePermission() functions, after getting the Partition in the handler.js functions, via getEnvironment?  Sorry, I just want to understand what you are asking before I pursue the changes.

Comment (medikoo) [reply lib/plugins/aws/customResources/resources/utils.js]: >  You are suggesting that I pass Partition into the permissions.js addPermission() / removePermission() functions,

Yes, exactly, sorry, for not being perfectly clear

**Comment by jmb12686** [comment]
@medikoo I've updated the PR with the latest changes you requested.
