### PR TITLE
Pause for mfa input

### LINKED ISSUE #6576: sls deploy with AWS cross account profile no longer waits for MFA input
# This is a Bug Report

## Description

- What went wrong?
  - Invoking `sls deploy` via `SLS_DEBUG=* sls deploy --stage mystage --aws-profile my-cross-account-role-with-mfa`, the application skips straight past the prompt for "Enter MFA code for..."
  - If an MFA token is entered at the next opportunity on stdin despite the _output_ moving on, then the deploy will continue using the assumed role
  - If the user simply hits enter because it looks like the deploy has stalled, then the deploy will fail with an error about `AWS provider credentials not found`
  - This previously worked OK with 1.37.1, the application waited for an MFA token on stdin but on 1.50.0 the output continues and is quite misleading as the app is still waiting for input
- What did you expect should have happened?
  - Application should wait at the MFA prompt for user input, then continue using the cross-account role
- What was the config you used?
  - ```
    provider:
    name: aws
    runtime: python3.6
    stage: ${opt:stage, 'dev'}
    region: eu-west-1
    ```
  - ~/.aws/credentials
    ```
    [default]
    aws_access_key_id = <my-root-account-access-key-id>
    aws_secret_access_key = <my-root-account-access-key-id>
    ```
  - Root account user has MFA enabled
  - ~/.aws/config
    ```
    [profile my-cross-account-role-with-mfa]
    region = eu-west-1
    role_arn = arn:aws:iam::<target-account-id>:role/<role-name>
    source_profile = default
    ```
    
- What stacktrace or error message from your provider did you see?
  - Initial application output:
    ```
    $ export AWS_SDK_LOAD_CONFIG="true"
    $ SLS_DEBUG=* sls deploy --stage mystage --aws-profile my-cross-account-role-with-mfa
    Serverless: Load command config
    Serverless: Load command config:credentials
    [...]
    Serverless: Invoke deploy
    Serverless: Invoke package
    Serverless: Invoke aws:common:validate
    Enter MFA code for arn:aws:iam::<root-account-id>:mfa/<root-user-name>: Serverless:Invoke aws:common:cleanupTempDir
    Serverless: Generated requirements from /[...]/requirements.txt in /[...]/.serverless/requirements.txt...
    Serverless: Installing requirements from /[...]/.serverless/requirements/requirements.txt ...
    ```
  - Deploy continues
    ```
    AWS Pseudo Parameter: 
    Resources::ChannelDeleteLambdaPermissionS3::Properties::SourceArn Replaced 
    AWS::Region with ${AWS::Region}
    AWS Pseudo Parameter: 
    Resources::ChannelUpdateLambdaPermissionS3::Properties::SourceArn Replaced 
    AWS::Region with ${AWS::Region}
    <enter-MFA-token-here>
    Serverless: [AWS sts 200 0.65s 0 retries] assumeRole({ RoleArn: 
    [...]

    ```

Similar or dependent issues:

- 

## Additional Data

- **_Serverless Framework Version you're using_**: 1.50.0
- **_Operating System_**: MacOS 10.13.6
- **_Stack Trace_**:
- **_Provider Error messages_**:

### PR DESCRIPTION
**Pull request by drexler**
## What did you implement
This allows credential validation checks to be applied when running the `package` hook only if the initial command is to create an artifact for deployment, that is explicitly `sls package`. Since the package hook is invoked by other commands like `deploy`, the validation step is deferred to that command's hook.

Closes #6576

## How can we verify it

Setup an MFA requirement with the AWS CLI and attempt to deploy: `sls deploy`. It should await input on the MFA prompt.

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test-ci` --> Run all validation checks on proposed changes
- `npm run lint-updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check-updated` --> Check if updated files adhere to Prettier config
- `npm run prettify-updated` --> Prettify all the updated files

</details>

- [x] Write and run all tests
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

File: lib/plugins/aws/package/index.js [hunk 1]
```diff
@@ -52,7 +52,11 @@ class AwsPackage {
        */
       'package:cleanup': () =>
         BbPromise.bind(this)
-          .then(() => this.serverless.pluginManager.spawn('aws:common:validate'))
+          .then(() => {
+            if (this.serverless.processedInput.commands[0] === 'package') {
```
Comment (medikoo) [inline lib/plugins/aws/package/index.js]: Why exactly do we need this condition?

Technically validation is already skipped for not applicable commands here: https://github.com/serverless/serverless/blob/f767fab43952c5a394d76b6b0f3f9779c8a5a3e6/lib/plugins/aws/lib/validate.js#L19-L24

Comment (drexler) [reply lib/plugins/aws/package/index.js]: True that validation is skipped there for non-applicable commands..but for commands like `sls deploy` this invokes it **twice**. Running with `SLS_DEBUG` shows this. So adding this check removes the need for an initial check during the _packaging_ phase whilst preserving the existing validation check if a user wants to explicitly run the packaging command: `sls package`

Comment (medikoo) [reply lib/plugins/aws/package/index.js]: Ok, I think it's logical error, that `aws:common:validate` is called here at all.

It's purely about validation of an AWS credentials, and this validation is already not pursued with `package` command (due to conditional I've linked above), while in `deploy` it incurs a double validation.

Therefore I think it's totally safe to remove this instruction completely here

**Comment by drexler** [comment]
@medikoo I've updated the PR per your review feedback.
