### PR TITLE
Fix invoke local when using callback in nodejs

### LINKED ISSUE #5522: SLS Invoke Local Exiting Too Soon
# This is a Bug Report

## Description

* What went wrong? sls invoke local with a nodejs handler that uses callbacks exiting too soon
* What did you expect should have happened? sls invoke local should wait for handler callback to be called before exiting
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #5349

## Additional Data

* ***Serverless Framework Version you're using***:1.33.0+
* ***Operating System***:Mac OS
* ***Stack Trace***:
* ***Provider Error messages***:

Seems that #5349 has broken sls invoke local for nodejs when using callbacks.

For example - when running this handler function with sls invoke local, the cli exits before the callback is run and output is not displayed in the console:

```
module.exports.hello = (event, context, callback) => {
    setTimeout(function(err, obj) {
        callback({
            statusCode: 200,
            body: JSON.stringify({
                message: 'Go Serverless v1.0! Your function executed successfully!',
                input: event
            })
        })
    }, 1000);
};
```

When run with serverless <= v1.32.0 it works as expected.

### PR DESCRIPTION
**Pull request by dschep**
## What did you implement:

Closes #5522

## How did you implement it:
Wrapped the invocation in a Promise that's resolved when `callback` is invoked.

## How can we verify it:
```
npm i -g serverless
git clone https://github.com/dschep-bug-repos/sls-5522
cd sls-5522
sls invoke local -f hello
npm i -g serverless/serverless#fix-invoke-local-callback
sls invoke local -f hello
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/plugins/aws/invokeLocal/index.js [hunk 1]
```diff
@@ -312,60 +312,63 @@ class AwsInvokeLocal {
...
     }
 
-    const callback = (err, result) => {
-      if (!hasResponded) {
-        hasResponded = true;
-        if (err) {
-          handleError.call(this, err);
-        } else if (result) {
-          handleResult.call(this, result);
+    return new Promise((resolve) => {
```
Comment (dschep) [inline lib/plugins/aws/invokeLocal/index.js]: This is probably easier to review by turning off white space diffing: https://github.com/serverless/serverless/pull/5525/files?w=1

**Comment by dschep** [comment]
I'm not sure how I'd use `fromCallback` to simplify this. It's not just classic node callback style. It also supports synchronous return & Promise return values. And the `callback` function ties into the `handleResult` and `handleError` functions.

**Comment by pmuens** [comment]
> I'm not sure how I'd use fromCallback to simplify this. It's not just classic node callback style. It also supports synchronous return & Promise return values. And the callback function ties into the handleResult and handleError functions.

Yes, good question. I was just reading through that code and thought that this might be a good enhancement. However, given this I'd say it's GTM and we can just merge this as is...
