### PR TITLE
S3 Transfer Acceleration IAM breaking change fix

### LINKED ISSUE #4625: ServerlessError: An error occurred: ServerlessDeploymentBucket - API: s3:setBucketAccelerateConfiguration Access Denied.
# This is a Bug Report
## Description

For bug reports:
* What went wrong?
The deploy failed with error `ServerlessError: An error occurred: ServerlessDeploymentBucket - API: s3:setBucketAccelerateConfiguration Access Denied.`. We've been using serverless with the same IAM user for the past few months, and this is the first time it's happened.
* What did you expect should have happened?
I'm guessing this has something to do with the new feature added for bucketAcceleration. I would expect that the addition of that feature would not break current deploys -- I don't want bucket acceleration, so I shouldn't have to give that permission to my IAM user.
* What was the config you used?
* What stacktrace or error message from your provider did you see?
```ServerlessError: An error occurred: ServerlessDeploymentBucket - API: s3:setBucketAccelerateConfiguration Access Denied.
    at provider.request.then (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:112:33)
From previous event:
    at AwsDeploy.monitorStack (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
    at provider.request.then (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:84:30)
From previous event:
    at AwsDeploy.update (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:84:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:101:12)
From previous event:
    at AwsDeploy.updateStack (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:135:39)
From previous event:
    at Object.AwsDeploy.hooks.aws:deploy:deploy:updateStack [as hook] (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:131:10)
    at BbPromise.reduce (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:368:55)
From previous event:
    at PluginManager.invoke (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:368:22)
    at PluginManager.spawn (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:386:17)
    at AwsDeploy.BbPromise.bind.then (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
From previous event:
    at Object.AwsDeploy.hooks.deploy:deploy [as hook] (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
    at BbPromise.reduce (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:368:55)
From previous event:
    at PluginManager.invoke (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:368:22)
    at PluginManager.run (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/classes/PluginManager.js:399:17)
    at variables.populateService.then (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Serverless.run (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/opt/circleci/nodejs/v6.1.0/lib/node_modules/serverless/bin/serverless:42:50)
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by alexcasalboni**
## What did you implement:

Closes #4625

I've made `s3:PutAccelerateConfiguration` IAM permissions optional (and documented it), and added a new `--no-aws-s3-accelerate` argument, as suggested.

## How did you implement it:

No `AccelerateConfiguration` will be added to the CloudFormation template unless `--aws-s3-accelerate` or `--no-aws-s3-accelerate` are provided.

## How can we verify it:

Deploy the service documented in #4293 with a limited IAM Role (i.e. without `s3:PutAccelerateConfiguration` permissions).

## Todos:

- [X] Write tests
- [X] Write documentation
- [X] Fix linting errors
- [X] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/plugins/aws/package/lib/generateCoreTemplate.js [hunk 1]
```diff
@@ -25,6 +25,14 @@ module.exports = {
 
     const bucketName = this.serverless.service.provider.deploymentBucket;
     const isS3TransferAccelerationEnabled = this.provider.isS3TransferAccelerationEnabled();
+    const isS3TransferAccelerationDisabled = this.provider.isS3TransferAccelerationDisabled();
+
+    if (isS3TransferAccelerationEnabled && isS3TransferAccelerationDisabled) {
+      const errorMessage = [
+        'You cannot enable and disable S3 Transfer Acceleration at the same time',
+      ].join('');
+      throw new this.serverless.classes.Error(errorMessage);
```
Comment (HyperBrain) [inline lib/plugins/aws/package/lib/generateCoreTemplate.js]: To introduce promise consistency over time, we should not throw here but reject.

```
return BbPromise.reject(new this.serverless.classes.Error(errorMessage));
```

Comment (alexcasalboni) [reply lib/plugins/aws/package/lib/generateCoreTemplate.js]: Done :)
