### PR TITLE
Multiple event definitions for existing Cognito User Pools

### LINKED ISSUE #6420: Can't add more than one Lambda trigger to existing Cognito User Pools at a time
# This is a Bug Report

## Description

- What went wrong?

Specifying more than one Lambda trigger to be added to an existing Cognito User Pool causes an error. The error indicates maybe there's a concurrency issue, when provisioning should be run in serial.

- What did you expect should have happened?

Expected all specified Lambda triggers to be created in a single deploy.

- What was the config you used?

```yaml
functions:
  preSignUp:
    handler: src/handlers.preSignUpHandler
    events:
      - cognitoUserPool:
          pool: ${self:custom.cognitoUserPool}
          trigger: PreSignUp
          existing: true
  defineAuthChallenge:
    handler: src/handlers.defineAuthChallengeHandler
    events:
      - cognitoUserPool:
          pool: ${self:custom.cognitoUserPool}
          trigger: DefineAuthChallenge
          existing: true
  createAuthChallenge:
    handler: src/handlers.createAuthChallengeHandler
    events:
      - cognitoUserPool:
          pool: ${self:custom.cognitoUserPool}
          trigger: CreateAuthChallenge
          existing: true
  verifyAuthChallenge:
    handler: src/handlers.verifyAuthChallengeHandler
    events:
      - cognitoUserPool:
          pool: ${self:custom.cognitoUserPool}
          trigger: VerifyAuthChallengeResponse
          existing: true
```

- What stacktrace or error message from your provider did you see?

```
  Serverless Error ---------------------------------------

  An error occurred: PreSignUpCustomCognitoUserPool1 - Failed to create resource. Only one request to update this UserPool can be processed at a time. See details in CloudWatch Log: 2019/07/20/[$LATEST]71e1d74b910b4766bf1f28e04354fcd1.

  Stack Trace --------------------------------------------

ServerlessError: An error occurred: PreSignUpCustomCognitoUserPool1 - Failed to create resource. Only one request to update this UserPool can be processed at a time. See details in CloudWatch Log: 2019/07/20/[$LATEST]71e1d74b910b4766bf1f28e04354fcd1.
    at provider.request.then.data (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:121:33)
From previous event:
    at AwsDeploy.monitorStack (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:27:12)
    at provider.request.then.cfData (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:103:28)
From previous event:
    at AwsDeploy.update (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:103:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:117:35)
From previous event:
    at AwsDeploy.updateStack (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:113:33)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:123:30)
    at BbPromise.reduce (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:464:55)
From previous event:
    at PluginManager.invoke (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:464:22)
    at PluginManager.spawn (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:484:17)
    at AwsDeploy.BbPromise.bind.then (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
From previous event:
    at Object.deploy:deploy [as hook] (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
    at BbPromise.reduce (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:464:55)
From previous event:
    at PluginManager.invoke (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:464:22)
    at PluginManager.run (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/classes/PluginManager.js:496:17)
    at variables.populateService.then (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/Serverless.js:116:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/lib/Serverless.js:103:74)
    at serverless.init.then (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/bin/serverless.js:52:28)
    at /Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:171:20)
From previous event:
    at initializeErrorReporter.then (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/bin/serverless.js:52:6)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Object.<anonymous> (/Users/Joel/.nvm/versions/node/v10.4.0/lib/node_modules/serverless/bin/serverless.js:38:39)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.4.0
     Serverless Version:        1.48.2
     Enterprise Plugin Version: 1.3.1
     Platform SDK Version:      2.0.3
```

Similar or dependent issues:

- 

## Additional Data

- **_Serverless Framework Version you're using_**: 1.48.2
- **_Operating System_**: MacOS High Sierra
- **_Stack Trace_**:
- **_Provider Error messages_**:

### PR DESCRIPTION
**Pull request by pmuens**
## What did you implement:

Closes #6420 

Adds support to define multiple Cognito User Pool events in one function.

## How did you implement it:

Fix it and write regression tests.

## How can we verify it:

Use the following serverless.yml file or run the Cognito User Pool integration tests (which were updated as well).

```yaml
service: test-${self:custom.idx}

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

custom:
  idx: 0
  pool: ExistingUserPool

functions:
  pre:
    handler: handler.hello
    events:
      - cognitoUserPool:
          pool: ${self:custom.pool}
          trigger: PreSignUp
          existing: true
      - cognitoUserPool:
          pool: ${self:custom.pool}
          trigger: DefineAuthChallenge
          existing: true
  post:
    handler: handler.hello
    events:
      - cognitoUserPool:
          pool: ${self:custom.pool}
          trigger: CreateAuthChallenge
          existing: true
      - cognitoUserPool:
          pool: ${self:custom.pool}
          trigger: VerifyAuthChallengeResponse
          existing: true
```

## Todos:

_**Note: Run `npm run test-ci` to run all validation checks on proposed changes**_

- [x] Write tests and confirm existing functionality is not broken.  
       **Validate via `npm test`**
- [x] Write documentation
- [x] Ensure there are no lint errors.  
       **Validate via `npm run lint-updated`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [x] Ensure introduced changes match Prettier formatting.  
       **Validate via `npm run prettier-check-updated`**  
       _Note: All reported issues can be automatically fixed by running `npm run prettify-updated`_
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** NO  
**_Is it a breaking change?:_** NO

### CODE REVIEW

File: lib/plugins/aws/package/compile/events/cognitoUserPool/index.js [hunk 1]
```diff
@@ -108,56 +108,78 @@ class AwsCompileCognitoUserPoolEvents {
...
+                Effect: 'Allow',
+                Resource: '*',
+                Action: [
+                  'cognito-idp:ListUserPools',
+                  'cognito-idp:DescribeUserPool',
+                  'cognito-idp:UpdateUserPool',
+                ],
+              });
+            } else {
+              Resources[customPoolResourceLogicalId].Properties.UserPoolConfigs.push({
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/cognitoUserPool/index.js]: If I read correctly, logic as put doesn't handle well configuration where user configured two pools under one function, and will assign two triggers to first approached pool (?) e.g. following:

```yaml
functions:
  users:
    handler: users.handler
    events:
      - cognitoUserPool:
          pool: legacy-user-pool
          trigger: CustomMessage
          existing: true
      - cognitoUserPool:
          pool: other-pool
          trigger: OtherMessage
          existing: true
```

will confgure `CustomMessage` and `OtherMessage` triggers for `legacy-user-pool`.

I think we should rather throw here if we approach events configuration for two different pools.

To ease the validation and make configuration schema less error-prone, maybe it'll be better to not allow more than one `cognitoUserPool` event per function, and allow to list triggers with a list, e.g.:

```yaml
functions:
  users:
    handler: users.handler
    events:
      - cognitoUserPool:
          pool: legacy-user-pool
          trigger:
            - CustomMessage
            - PreSignUp
          existing: true
```

File: lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js [hunk 2]
```diff
@@ -368,6 +368,219 @@ describe('AwsCompileCognitoUserPoolEvents', () => {
...
+              {
+                Trigger: 'DefineAuthChallenge',
+              },
+            ],
+          },
+        });
+      });
+    });
+
+    it('should create DependsOn clauses when one cognito user pool is used in more than 1 custom resources', () => {
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js]: We may also add tests, where user configures two different pools for one function, and expect specific, UX friendly exception in such case

File: lib/plugins/aws/package/compile/events/cognitoUserPool/index.js (hunk 1 above)
Comment (pmuens) [reply lib/plugins/aws/package/compile/events/cognitoUserPool/index.js]: Good point. I already added a note in the docs and will add a check for it here as well.

Unfortunately we cannot alter the event definition since this has to be aligned with the event definition we put in place when implementing Cognito User Pool event support for non-existing pools.

File: lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js (hunk 2 above)
Comment (pmuens) [reply lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js]: On it...
