### PR TITLE
Fix the plugin commands fail if listed plugins does not exist

### LINKED ISSUE #4259: `sls plugin search` fails if a plugin is uninstalled
# This is a Bug Report

## Description

In a given directory that has a plugin listed in the `serverless.yml` which is not installed, a call to `sls plugin search --query webpack` fails with the message:

`Serverless plugin "serverless-spotinst-functions" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.`

I would expect this plugin search to complete even if I have an uninstalled plugin locally.

## Additional Data

* ***Serverless Framework Version you're using***: 1.22
* ***Node.js Version you're using***: 8.5.0
* ***Operating System***: macos

### PR DESCRIPTION
**Pull request by horike37**
## What did you implement:
The plugin commands failed if listed plugins within serverless.yml do not exist in node_modules. 
All plugin commands shouldn't catch the error related to the state of another plugin. Then I fixed it.

Closes #4259 

## How did you implement it:
when running the `plugin` commands, errors are ignored even if listed plugins within serverless.yml do not exist.

## How can we verify it:
- Run `serverless create -t spotinst-nodejs`. At this time, you will see listed the spotinst plugin but that is not actually installed
- Run `serverless plugin` commands

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/classes/PluginManager.js [hunk 1]
```diff
@@ -90,6 +90,9 @@ class PluginManager {
 
         this.addPlugin(Plugin);
       } catch (error) {
+        if (this.cliCommands[0] === 'plugin') {
```
Comment (HyperBrain) [inline lib/classes/PluginManager.js]: For now I think this is ok (to generally ignore errors on the plugin plugin) to get it working.

On a longer term, we could introduce a boolean property `loadAlways` for plugins that we check here. So any plugin can request to be loaded, even if there are errors. But that approach is out of scope for this PR and would need some deeper thinking 😃

**Comment by horike37** [comment]
Thank you for the review @HyperBrain :+1:
Yes. That's a reasonable solution what you stated. 
If plugins which want not to be loaded every time increase, we should introduce such a solution.
For now, I will merge this PR.
