### PR TITLE
remove request and response config when using proxy integration

### LINKED ISSUE #2798: v1.2.1 introduces a bug with HTTP event Request Parameters
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

When doing a `sls deploy`, the following error occurs:

```
............................Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: ApiGatewayMethodBroadcastIdVarGet
     - Invalid mapping expression specified: Validation Result:
     warnings : [], errors : [Invalid mapping expression
     specified: paths].

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.5.0
     Serverless Version: 1.2.0
```

* What did you expect should have happened?

When I use Serverless 1.1.0, it works as expected.

* What was the config you used?

The relavant part of the config file is:

```yaml
functions:
  http:
    name: ${self:custom.${env:PROG_ENV}.name.lower}-http
    handler: handlers.http_handler
    timeout: 5
    events:
      - http:
          method: get
          path: resource/{id}
          request:
            parameters:
              paths:
                id: true
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - Authorization
              - Accept
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - x-secret
```

* What stacktrace or error message from your provider did you see?

    Invalid mapping expression specified: paths

## Additional Data

I also tested this with v1.2.0 and the issue happens there too. So I am going to stick with 1.1.0 until this get resolved.

If there is anything I can do to help, please let me know.

### PR DESCRIPTION
**Pull request by dougmoscrop**
## What did you implement:

Closes #2798

## How did you implement it:

What was being 'ignored' was the parsing of the request/response configuration, not the configuration itself.

## How can we verify it:

Tests pass, and example yaml in the issue now deploys.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors (* other code on master is having linting problems??)
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by pmuens** [comment]
@dougmoscrop thank you for this fix! 👍 

Could you maybe rebase this PR and add a small test so that we can make sure that the `request` and `response` are removed? Thanks in advance 👍

**Comment by dougmoscrop** [comment]
Done!

**Comment by pmuens** [comment]
Just wondering if we should leave a comment in the docs about this behavior here (at the top where the `LAMBDA-PROXY` and `LAMBDA` integration types are described: https://github.com/serverless/serverless/blob/master/docs/providers/aws/events/apigateway.md

**Comment by mthenw** [comment]
We shouldn't ignore user's config. If the config is wrong we should exit with meaningful error message but not accepting wrong configuration. That creates lots of confusion.

**Comment by pmuens** [comment]
Yep. I agree. Then no doc updates are required...

**Comment by dougmoscrop** [comment]
Changing to throwing is going to break peoples scripts that may have been working right now without paying attention to the message. Are you sure you want to do this?

**Comment by pmuens** [comment]
That's a good point. Is it a breaking change? 🤔 
Although I agree with @mthenw that it's way more explicit than ignoring the users config.

**Comment by mthenw** [comment]
Hmm, that's a tough one. 

Just to make sure that we are on the same page:
- 1.x version shows warning about using lambda-proxy with req/res config
- the issue is that it's actually not ignoring this config

If that's true we should merge this PR and just add another issue for 2.0 about returning error when both lambda-proxy and req/res config is set.

**Comment by pmuens** [comment]
Yep. I agree with @mthenw throwing an error will be a breaking change but should be implemented in v2 so that the user knows exactly what's going on.

Can you open up an issue for that @mthenw and add it to the v2 milestone? Thanks!

File: lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js [hunk 1]
```diff
@@ -101,6 +101,9 @@ module.exports = {
                 ' This configuration will be ignored during deployment.',
```
Comment (pmuens) [inline lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js]: This should be updated that the config will be removed
