### PR TITLE
Local function invocation with handler path containing dot in folder name

### LINKED ISSUE #7330: Invoke local fails if function path contains '.'
# Bug Report

## Description

We output our typescript build to .build directory.
Our functions reference this directory i.e. `handler: .build/handler.doSomething`
invoke splits on '.' and doesn't get our paths correct.
Would be good if it split out the file portion before splitting on '.'

### PR DESCRIPTION
**Pull request by arbbakbenny**
## What did you implement

Closes #7330

### Automatically

Checkout to commit `a7da3400e3dc5abfe1bac8a4eb251f2d7e4dd0d1` and run `lib/plugins/aws/invokeLocal/index.test.js`. Test
<pre>
test://AwsInvokeLocal.#invokeLocal().for different handler paths.should call invokeLocalNodeJs for any node\.js runtime version for \.build/handler\.hello
</pre>
should fail.
Checkout to the HEAD and run the test again, it should pass.

### Manually
Create following project structure
<pre>
projectRoot
|- .build/handler.js
|- serverless.yml
</pre>
with reference in `serverless.yml`
<pre>
functions:
  hello:
    handler: .build/handler.hello
</pre>
Executing `serverless invoke local -f hello` should return proper response instead of throwing an error.

## Todos

- [x] Write and run all tests
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** Yes
**_Is it a breaking change?:_** No

### CODE REVIEW

File: lib/plugins/aws/invokeLocal/index.js [hunk 1]
```diff
@@ -178,8 +178,9 @@ class AwsInvokeLocal {
     }
 
     if (runtime.startsWith('nodejs')) {
-      const handlerPath = handler.split('.')[0];
-      const handlerName = handler.split('.')[1];
+      const handlerComponents = handler.split(/\./);
+      const handlerPath = handlerComponents.slice(0, -1).join('.');
+      const handlerName = handlerComponents.pop();
```
Comment (medikoo) [inline lib/plugins/aws/invokeLocal/index.js]: Probably less convoluted will be that way (?)

```suggestion
      const handlerSeparatorIndex = handler.lastIndexOf('.');
      const handlerPath = handler.slice(0, handlerSeparatorIndex);
      const handlerName = handler.slice(handlerSeparatorIndex + 1);
```

Comment (arbbakbenny) [reply lib/plugins/aws/invokeLocal/index.js]: Hi @medikoo , thank you very much for your feedback, it's appreciated! Your suggestion does look better so I'll adapt the code.
