### PR TITLE
Fix #3792: Resolve tabtab/src/cli.js path when installing locally

### LINKED ISSUE #3792: Postinstall script installation fails when installing locally
# This is a Bug Report

## Description
I know a correct way to install globally using `npm install serverless - g`, but when installing locally in own project with `npm install serverless --save`, an error occurs during execution of postinstall.js.

Is this bug? or does it mean sls has not supported for installing locally?

### step to reproduce
- Create directory with `mkdir sls-project && cd sls-project`
- Run `npm init`
- Run `npm install serverless --save`, and you will see the following error

```
$npm install serverless --save
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-F2n0tVHu3OQZ8FBd6uLiZ2NULTc= integrity checksum failed when using sha1: wanted sha1-F2n0tVHu3OQZ8FBd6uLiZ2NULTc= but got sha512-0TZ20a+xcIl4u0+Mj5xDH2yOWdmQiXlKf9Hm+TgDXjTMsEYb+gDrmb8e8UNAzMCitX8NBqG4Z/FUQIyzv/R1JQ==. (2982 bytes)

> serverless@1.15.3 postinstall /Users/horike/src/sls-project/node_modules/serverless
> node ./scripts/postinstall.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/horike/src/sls-project/node_modules/serverless/node_modules/tabtab/src/cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/horike/src/sls-project/node_modules/serverless/node_modules/tabtab/src/cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

> spawn-sync@1.0.15 postinstall /Users/horike/src/sls-project/node_modules/spawn-sync
> node postinstall

npm WARN saveError ENOENT: no such file or directory, open '/Users/horike/src/sls-project/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/horike/src/sls-project/package.json'
npm WARN sls-project No description
npm WARN sls-project No repository field.
npm WARN sls-project No README data
npm WARN sls-project No license field.

+ serverless@1.15.3
added 210 packages in 23.298s
```
Similar or dependent issues:
* #3760
* #3763

## Additional Data
* ***node version***: 6.10.2
* ***npm version***: 5.0.3
* ***Serverless Framework Version you're using***:1.15.3
* ***Operating System***: macOS 10.11.6
* ***Stack Trace***: above
* ***Provider Error messages***: above

### PR DESCRIPTION
**Pull request by k1LoW**
## What did you implement:

Closes #3792 

## How did you implement it:

Check `tabtab` path using `fileExistsSync` before exec.

## How can we verify it:

- Create directory with `mkdir sls-project && cd sls-project`
- Run `npm init`
- Run `npm install k1LoW/serverless#get-installed-path --save` , and you will see no error like #3792 

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: scripts/postinstall.js [hunk 1]
```diff
@@ -20,13 +22,17 @@ try {
 
 function setupAutocomplete() {
   return new Promise((resolve, reject) => {
+    let tabtabPath = './node_modules/tabtab';
+    if (!fileExistsSync(path.join(__dirname, '..', 'node_modules', 'tabtab', 'src', 'cli.js'))) {
+      tabtabPath = '../tabtab';
```
Comment (HyperBrain) [inline scripts/postinstall.js]: If you'd use the "get-installed-path" module as I mentioned in #3792, we could skip the tabtab invocation at all.

Only checking the main path and then trying the alternative path without checking it will exist, will trigger the exc-eption later. It would be better to use the module and immediately emit a warning, that tabtab was not found without trying to execute a command that might not exist.

get-installed-path would even find a global tabtab if the local one is not found.

Comment (k1LoW) [inline scripts/postinstall.js]: I thought so. ( and at first, I used get-installed-path. )
But,  "get-installed-path" did not work, when I excute `npm install serverless --save`.

Comment (martinheidegger) [inline scripts/postinstall.js]: What about `package.resolve` ?

Comment (k1LoW) [inline scripts/postinstall.js]: @martinheidegger https://www.npmjs.com/package/resolve ?

**Comment by horike37** [comment]
Hey @pmuens, this is friendly ping!
Could you review this PR? @k1LoW has created an error tracking tool named [faultline](https://github.com/faultline/faultline). The tool uses sls framework as `node_module`, so when the tool install, the tabtab invocation error occurs. Hope to fix this error.

File: scripts/postinstall.js (hunk 1 above)
Comment (martinheidegger) [inline scripts/postinstall.js]: https://nodejs.org/api/globals.html#globals_require_resolve

**Comment by pmuens** [comment]
Thanks for pinging @horike37 👍 Adding it to the upcoming milestone...

Really nice project @k1LoW ! Just checked it out and it looks really promising 💯 🥇

File: scripts/postinstall.js (hunk 1 above)
Comment (k1LoW) [inline scripts/postinstall.js]: Thank you @maciejtreder ! `require.resolve` work good!

**Comment by k1LoW** [comment]
@pmuens 

I tried now. and still works.

```sh
~/tmp > mkdir sls-project
~/tmp > cd sls-project
~/tmp/sls-project > npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (sls-project)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
license: (ISC)
About to write to /Users/k1low/tmp/sls-project/package.json:

{
  "name": "sls-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "k1LoW <k1lowxb@gmail.com> (https://github.com/k1LoW)",
  "license": "ISC"
}


Is this ok? (yes) yes
~/tmp/sls-project > npm install k1LoW/serverless#get-installed-path --save
npm WARN prefer global serverless@1.15.3 should be installed with -g

> spawn-sync@1.0.15 postinstall /Users/k1low/tmp/sls-project/node_modules/spawn-sync
> node postinstall


> serverless@1.15.3 postinstall /Users/k1low/tmp/sls-project/node_modules/serverless
> node ./scripts/postinstall.js


[tabtab] Adding source line to load /Users/k1low/tmp/sls-project/node_modules/tabtab/.completions/serverless.zsh
in /Users/k1low/.zshrc


[tabtab] Adding source line to load /Users/k1low/tmp/sls-project/node_modules/tabtab/.completions/sls.zsh
in /Users/k1low/.zshrc

sls-project@1.0.0 /Users/k1low/tmp/sls-project
└─┬ serverless@1.15.3  (git://github.com/k1low/serverless.git#fa5e5d443d12f57abf89700f8e74a37faf685f03)
  ├─┬ archiver@1.3.0
  │ ├─┬ archiver-utils@1.3.0
  │ │ ├── lazystream@1.0.0
  │ │ └─┬ normalize-path@2.1.1
  │ │   └── remove-trailing-separator@1.0.2
  │ ├── async@2.4.1
  │ ├── buffer-crc32@0.2.13
  │ ├─┬ glob@7.1.2
  │ │ ├── fs.realpath@1.0.0
  │ │ ├─┬ inflight@1.0.6
  │ │ │ └── wrappy@1.0.2
[...]
  │ │ │   └── number-is-nan@1.0.1
  │ │ └── through@2.3.8
  │ ├── lodash.difference@4.5.0
  │ ├── lodash.uniq@4.5.0
  │ └─┬ npmlog@2.0.4
  │   ├── ansi@0.3.1
  │   ├─┬ are-we-there-yet@1.1.4
  │   │ └── delegates@1.0.0
  │   └─┬ gauge@1.2.7
  │     ├── has-unicode@2.0.1
  │     ├── lodash.pad@4.5.1
  │     ├── lodash.padend@4.6.1
  │     └── lodash.padstart@4.6.1
  ├── uuid@2.0.3
  └─┬ write-file-atomic@2.1.0
    ├── imurmurhash@0.1.4
    └── slide@1.1.6

npm WARN sls-project@1.0.0 No description
npm WARN sls-project@1.0.0 No repository field.
~/tmp/sls-project >
```

**Comment by medikoo** [comment]
Great to see that fix, do you know when this will be published on npm?

**Comment by horike37** [comment]
@medikoo 
This PR has added 1.17 milestone, so including this on the next release.

**Comment by pmuens** [comment]
> Great to see that fix, do you know when this will be published on npm?

@medikoo Yes, @horike37 is right. `v1.17` is scheduled to be released on July 5, 2017.

**Comment by hash** [comment]
Hello, on windows it is still broken. 
My fix attempt:
```diff
diff --git a/scripts/postinstall.js b/scripts/postinstall.js
index 9eb4fba3..5de81cc0 100644
--- a/scripts/postinstall.js
+++ b/scripts/postinstall.js
@@ -5,6 +5,7 @@
 
 const Serverless = require('../lib/Serverless');
 const execSync = require('child_process').execSync;
+const path = require('path');
 
 try {
   const serverless = new Serverless();
@@ -20,14 +21,16 @@ try {
 
 function setupAutocomplete() {
   return new Promise((resolve, reject) => {
-    const tabtabPath = require.resolve('tabtab').replace(/\/index.js$/, '');
+    const tabtabPath = require.resolve('tabtab').split(path.sep);
+    if (tabtabPath[tabtabPath.length - 1] === 'index.js') { tabtabPath.pop(); }
+    const tabtabPathCli = path.join(...tabtabPath, 'src', 'cli.js');
     try {
-      execSync(`node ${tabtabPath}/src/cli.js install --name serverless --auto`);
-      execSync(`node ${tabtabPath}/src/cli.js install --name sls --auto`);
+      execSync(`node ${tabtabPathCli} install --name serverless --auto`);
+      execSync(`node ${tabtabPathCli} install --name sls --auto`);
       return resolve();
     } catch (error) {
-      execSync(`node ${tabtabPath}/src/cli.js install --name serverless --stdout`);
-      execSync(`node ${tabtabPath}/src/cli.js install --name sls --stdout`);
+      execSync(`node ${tabtabPathCli} install --name serverless --stdout`);
+      execSync(`node ${tabtabPathCli} install --name sls --stdout`);
       console.log('Could not auto-install serverless autocomplete script.');
       console.log('Please copy / paste the script above into your shell.');
       return reject(error);

```

File: scripts/postinstall.js [hunk 2]
```diff
@@ -20,13 +20,14 @@ try {
 
 function setupAutocomplete() {
   return new Promise((resolve, reject) => {
+    const tabtabPath = require.resolve('tabtab').replace(/\/index.js$/, '');
```
Comment (HyperBrain) [inline scripts/postinstall.js]: I think this is not OS agnostic (also commented by @hash) as it uses a fixed "/" path separator which is e.g. not available on Windows.
`path.sep` should be used to build the regex here.

Comment (HyperBrain) [inline scripts/postinstall.js]: The referenced issue is #3792

Comment (pmuens) [inline scripts/postinstall.js]: Shoot! Nice catch @HyperBrain.

I'll submit a fix in a sec.

Comment (pmuens) [inline scripts/postinstall.js]: Just PRed the fix in #3870.
