### PR TITLE
AWS Environment variables should contain only strings

### LINKED ISSUE #4884: Different validation behavior between `serverless deploy` & `serverless deploy function`
# This is a `Bug Report`

## Description

* What went wrong?
I'm facing the validation issue when running `serverless deploy function --function facebook-events`
**BUT** everything is working as expected when I'm running `serverless deploy`

* What did you expect should have happened?
The same validation rules should be applied.

* What was the config you used?

```yml
...
functions:
  facebook-albums:
    handler: facebook-albums/index.handler
    package:
      include: ['facebook-albums/**']
    environment:
      API_TOKEN: ${ssm:facebookApiToken}

  facebook-events:
    handler: facebook-events/index.handler
    package:
      include: ['facebook-events/**']
    environment:
      COUNT: 6 # <== ISSUE 
      API_TOKEN: ${ssm:facebookApiToken}
...
```

* What stacktrace or error message from your provider did you see?

`Expected params.Environment.Variables['COUNT'] to be a string`

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: macOS 10.13.4
* ***Node.js Version***: v6.11.4

### PR DESCRIPTION
**Pull request by kobim**
## What did you implement:

Closes #4884

Lambda environment variables must only contain strings. Although both [CloudFormation template documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-environment.html) and [Lambda's API](https://docs.aws.amazon.com/lambda/latest/dg/API_Environment.html) state that, only Lambda's API enforces it.

As `deploy --function` uses [Lambda's UpdateFunctionConfiguration](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html) and `deploy` updates the CF template, you only see a validation issue when running the function deploy command.

This makes sure both uses will go through the same check to make sure everything is ok (and hopefully in the future, the CF validation will be fixed and no one will be shocked _serverless_ didn't validate this before).

## How did you implement it:

Making sure the `Environment.Variables` parameter in both the CF template and _updateFunctionConfiguration_ call will contain only string values.

## How can we verify it:

```yml
functions:
  error-function:
    handler: handler.func
    environment:
      INPUT: 80

  good-function:
    handler: handler.func
    environment:
      INPUT: '80'
      SOMEREF:
        Ref: MyVar

resources:
  Parameters:
    MyVar:
      Type: Number
      Default: 7
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/plugins/aws/deployFunction/index.js [hunk 1]
```diff
@@ -164,6 +164,10 @@ class AwsDeployFunction {
             const errorMessage = 'Invalid characters in environment variable';
             throw new this.serverless.classes.Error(errorMessage);
           }
+          if (typeof params.Environment.Variables[key] !== 'string') {
```
Comment (HyperBrain) [inline lib/plugins/aws/deployFunction/index.js]: Does that also still work for CF references like this?
```
Environment:
  MY_VAR:
    Ref: myResource
```
It is important that CF references that are resolved while CloudFormation deploys the stack still work.
Maybe it would be better to error only on disallowed integral types with a condition like this:
`if (_.isNumber(...) || _.isBoolean(...) || ... ` or even a specific check on the special AWS CF functions.
E.g. check for anything that is not a string and not an object that contains `Ref`, or `Fn::*`:

```
if (!_.isString(...) || _.isObject(...) && !_.some(..., (val, key) => _.startsWith(key, 'Fn::'))) {
``` 

Additionally you should use lodash here for all typechecks.

**Comment by kobim** [comment]
Fixes pushed
I didn't check for CF ref & functions in the deploy function, as these are removed (97896eb34fa3282f42c0cc72d2946c94e284731c).

I'm a bit unsure about the syntax I chose (`const isCFRef = ...`), but I didn't want to write a complex _if_ function.

**Comment by kobim** [comment]
any updates on this PR @HyperBrain ?

**Comment by HyperBrain** [comment]
@kobim Sorry for the delay. We're releasing 1.27 right now and holding back any PRs until that is finished.
I'll add the 1.28 milestone and check it again soon.

**Comment by HyperBrain** [comment]
Regarding the CFRef I think it is ok to do the simple check as it will catch the generic errors.
