### PR TITLE
Temporarily remove provider.variableSyntax during variable population

### LINKED ISSUE #2890: Variable Syntax matches itself in serverless.yml
# This is a Bug Report

## Description
I tried to use the `variableSyntax` property to enable me to use cross-stack references in CloudFormation. I set it to `'\${{([\s\S]+?)}}'` to allow me to use `${blah}` in CF and `${{opt:stage}}` 

The custom variable syntax I set is matching on itself. [Variables.js](https://github.com/serverless/serverless/blob/master/lib/classes/Variables.js) temporarily removes this property `this.service.defaults.variableSyntax` but does not remove `this.service.provider.variableSyntax` causing it to match on that property.

The fix will be to temporarily remove `this.service.provider.variableSyntax`.

## Similar Issue
* #2143

## Additional Data

* ***Serverless Framework Version you're using***: 1.3.0
* ***Operating System***: MacOSX
* ***Stack Trace***:
```
  Serverless Error ---------------------------------------
 
     Invalid variable reference syntax for variable ([\s\S]+?).
     You can only reference env vars, options, & files. You
     can check our docs for more info.
 
  Stack Trace --------------------------------------------
 
ServerlessError: Invalid variable reference syntax for variable ([\s\S]+?). You can only reference env vars, options, & files. You can check our docs for more info.
    at Variables.getValueFromSource (/.../serverless/lib/classes/Variables.js:128:13)
    at /.../serverless/lib/classes/Variables.js:66:34
    at Array.forEach (native)
    at Variables.populateProperty (/.../serverless/lib/classes/Variables.js:58:43)
    at Object.<anonymous> (/.../serverless/lib/classes/Variables.js:45:25)
    at walker (/.../serverless/node_modules/traverse/index.js:190:22)
    at /.../serverless/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/.../serverless/node_modules/traverse/index.js:298:31)
    at walker (/.../serverless/node_modules/traverse/index.js:203:13)
    at /.../serverless/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/.../serverless/node_modules/traverse/index.js:298:31)
    at walker (/.../serverless/node_modules/traverse/index.js:203:13)
    at walk (/.../serverless/node_modules/traverse/index.js:226:7)
    at Traverse.forEach (/.../serverless/node_modules/traverse/index.js:50:18)
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /.../serverless/bin/serverless:11:28
    at Object.<anonymous> (/.../serverless/bin/serverless:20:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.3.2
     Serverless Version: 1.3.0
```

### PR DESCRIPTION
**Pull request by johncmckim**
## What did you implement:
Closes #2890

## How did you implement it:
Temporarily remove provider.variableSyntax during variable population. This will prevent the service from matching on itself.

## How can we verify it:
Run `sls deploy --noDeploy` with a minimal `serverless.yml`

```
service: test-sls-proj

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: false
  variableSyntax: '\${{([\s\S]+?)}}'
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** Yes

### CODE REVIEW

File: lib/classes/Variables.js [hunk 1]
```diff
@@ -32,6 +32,7 @@ class Variables {
 
     // temporally remove variable syntax from service otherwise it'll match
     this.service.defaults.variableSyntax = true;
+    this.service.provider.variableSyntax = true;
```
Comment (eahefnawy) [inline lib/classes/Variables.js]: hmmm is it just me, or do I see two identical lines here? am I missing something?!

Comment (eahefnawy) [inline lib/classes/Variables.js]: oh!! yeah this is what I was missing! 😂 Thanks man! 👍

Comment (pmuens) [inline lib/classes/Variables.js]: 👍 😄
