### PR TITLE
Fix average functions duration calculation in metrics output

### LINKED ISSUE #3066: Serverless metrics outputs incorrect average function duration
# This is a Bug Report

#### What went wrong?
My functions never executed longer than 800 ms, but serverless says average time is 831 ms.

#### What did you expect should have happened?
I expected to see a real metrics

#### What was the config you used?
Not applicable.

#### What stacktrace or error message from your provider did you see?
No error message.

Similar or dependent issues:
* none

## Additional Data

* ***Serverless Framework Version you're using***: 1.5.0
* ***Operating System***: Ubuntu 16.10
* ***Stack Trace***: none
* ***Provider Error messages***: none

I cloned the latest `master` branch locally to add some `console.log`s to see what's the problem.

**awsMetrics.js**
```diff
      _.forEach(metrics, (metric, index) => {
+        console.log(`--- ${index} function`);
        _.forEach(metric, (funcMetric) => {
          if (funcMetric.Label === 'Invocations') {
            invocations += reduceDatapoints(funcMetric.Datapoints, 'Sum');
          } else if (funcMetric.Label === 'Throttles') {
            throttles += reduceDatapoints(funcMetric.Datapoints, 'Sum');
          } else if (funcMetric.Label === 'Errors') {
            errors += reduceDatapoints(funcMetric.Datapoints, 'Sum');
          } else {
+            funcMetric.Datapoints.forEach(point => {
+              console.log(moment(point.Timestamp).format('YYYY-MM-DD'), '-', point.Average.toFixed(2));
+            });
            duration += reduceDatapoints(funcMetric.Datapoints, 'Average');
          }
        });
      });
```

which produced the output:

```bash
$ ~/serverless/bin/serverless metrics --startTime 10d --stage prod
--- 0 function
2017-01-01 - 247.40
2016-12-29 - 129.54
--- 1 function
2016-12-28 - 575.13
2017-01-01 - 255.61
2016-12-29 - 186.05
2017-01-02 - 284.15
2016-12-31 - 186.15
--- 2 function
2017-01-01 - 102.32
2016-12-29 - 102.07
2017-01-02 - 222.01
2016-12-31 - 97.99
--- 3 function
2016-12-29 - 565.32
2017-01-02 - 371.52
Service wide metrics
December 27, 2016 9:26 PM - January 6, 2017 9:26 PM

Invocations: 725 
Throttles: 0 
Errors: 0 
Duration (avg.): 831.3125ms

```

So it's visible that something is wrong in calculating the average. After looking forward I found that we sum together milliseconds from every day and divide them by `metrics.length` i.e. by number of functions. But we don't take into account CloudWatch can return data by several Periods in a given timespan.
Hence I looked into this already, I'll prepare a fix.

### PR DESCRIPTION
**Pull request by vladgolubev**
## What did you implement:

Closes #3066  + refactoring of AWS Metrics plugin

## How did you implement it:

**Before:**
Previously it was summing durations from each day and dividing it by number of Lambda functions, instead of number of data points from CloudWatch.

**After:**
```js
const durationAverage = _.meanBy(getDatapointsByLabel('Duration'), 'Average') || 0;
```

Also refactored some code to increase readability (I hope) and "code churn" metric :sweat_smile: I was careful and all the tests are still passing, so should be ok.

## How can we verify it:

This can be verified by:

1. Unit test: `should display correct average of service wide average function duration`
2. By manually checking service wide metrics for a large period of time for 1 function. Previously you would see abnormally high value. 

Also I'm not sure whether the code coverage dropped or not. It dropped by statements, but increased by branches.

```
before:
Statements   : 95.63% ( 2624/2744 )
Branches     : 90.26% ( 1056/1170 )
Functions    : 97.55% ( 279/286 )
Lines        : 95.71% ( 2587/2703 )


after:
Statements   : 95.53% ( 2587/2708 )
Branches     : 90.72% ( 1046/1153 )
Functions    : 97.56% ( 280/287 )
Lines        : 95.62% ( 2552/2669 )
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by vladgolubev** [comment]
Also docs looks strange. But they are ok in repo.

image

**Comment by pmuens** [comment]
Thank you very much!

Awesome PR description! 👍 We'll look into it ASAP!

File: lib/classes/Service.js [hunk 1]
```diff
@@ -182,6 +182,10 @@ class Service {
     return Object.keys(this.functions);
   }
 
+  getAllFunctionsNames() {
```
Comment (pmuens) [inline lib/classes/Service.js]: This should be covered by a test.

File: lib/plugins/aws/configCredentials/awsConfigCredentials.js [hunk 2]
```diff
@@ -64,19 +65,13 @@ class AwsConfigCredentials {
...
     this.serverless.cli.log('Saving your AWS profile in "~/.aws/credentials"...');
 
-    // locate home directory on user's machine
-    const env = process.env;
-    const home = env.HOME ||
-      env.USERPROFILE ||
-      (env.HOMEPATH ? ((env.HOMEDRIVE || 'C:/') + env.HOMEPATH) : null);
-
-    if (!home) {
+    if (!os.homedir()) {
```
Comment (pmuens) [inline lib/plugins/aws/configCredentials/awsConfigCredentials.js]: is `os.homedir()` also safe for old Node versions?

Comment (pmuens) [inline lib/plugins/aws/configCredentials/awsConfigCredentials.js]: Here's the list of Node versions we "officially" support: https://github.com/serverless/serverless/blob/53c96088a2f15c72173536ab94428c8ea5f4b7d2/.travis.yml#L5-L8

Comment (vladgolubev) [inline lib/plugins/aws/configCredentials/awsConfigCredentials.js]: image


Hm, added in v2.3.0 - means safe.

My reasoning was, that I noticed that unit tests are using `os.homedir()` but the code not. After `git blame` found out it was because after refactoring project structure file was just copy pasted, and tests were written after by a different person. So just minor inconsistency.

**Comment by vladgolubev** [comment]
@pmuens thanks for the review and feedback! Sorry for absence, I'm back here )

 >  Usually it's better to have function based PRs

I strongly agree for that!! But with this PR the story was a bit different)

When you released metrics support in some of the recent releases, I, was impressed. So I went to the sources to read the implementation. After reading, I created a note to myself to refactor that file, as it's a great functionality, but no so readable as I could wish. 

So I started refactoring it at that time, and after unit tests,  I moved to testing it with my AWS account.

And at that time I realised that outputs differ from my local sls branch and what is published to npm. So I started digging into it to find where is my bug.

But in the end, it occurred on contrary - my refactoring fixed a bug I didn't have an idea about. 

So, refactoring without any purpose resulted in a bug fix. Of course, afterwards I could fix couple of lines in the old code knowing the reason, and submit a new PR with just a refactoring, buuut, this didn't happen, it wasn't already so interesting for me, so all I can say to forgive me

File: lib/classes/Service.js (hunk 1 above)
Comment (vladgolubev) [inline lib/classes/Service.js]: Of course, thanks @pmuens, just pushed the changes

Comment (pmuens) [inline lib/classes/Service.js]: Thanks!

File: lib/plugins/aws/configCredentials/awsConfigCredentials.js (hunk 2 above)
Comment (pmuens) [inline lib/plugins/aws/configCredentials/awsConfigCredentials.js]: Yep. That totally makes sense.

I copied the code for the homedir detection from an old PR and pushed the test on top of that 😬. But yes, if the test use os.homedir and work for all node versions on our CI system, then the usage of `os.homedir` should work in the main code as well 😆 🤦‍♂️

File: lib/plugins/aws/provider/awsProvider.js [hunk 3]
```diff
@@ -190,15 +191,12 @@ class AwsProvider {
...
-    } else if (this.serverless.service.provider.region) {
-      returnValue = this.serverless.service.provider.region;
-    }
-    return returnValue;
+    const defaultRegion = 'us-east-1';
+
+    return _.get(this, 'options.region')
+      || _.get(this, 'serverless.config.region')
+      || _.get(this, 'serverless.service.provider.region')
+      || defaultRegion;
```
Comment (eahefnawy) [inline lib/plugins/aws/provider/awsProvider.js]: Nice!

File: lib/plugins/aws/metrics/awsMetrics.js [hunk 4]
```diff
@@ -207,33 +107,28 @@ class AwsMetrics {
...
+          .flatten()
+          .filter({ Label })
+          .map('Datapoints')
+          .flatten()
+          .value();
+
+      const invocationsCount = _.sumBy(getDatapointsByLabel('Invocations'), 'Sum');
+      const throttlesCount = _.sumBy(getDatapointsByLabel('Throttles'), 'Sum');
+      const errorsCount = _.sumBy(getDatapointsByLabel('Errors'), 'Sum');
+      const durationAverage = _.meanBy(getDatapointsByLabel('Duration'), 'Average') || 0;
```
Comment (eahefnawy) [inline lib/plugins/aws/metrics/awsMetrics.js]: ❤️
