### PR TITLE
Invoke local docker

### LINKED ISSUE #3456: Invoke local should support context.callbackWaitsForEmptyEventLoop
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Invoke local doesn't check the event loop before "executing" the handler callback.
* What did you expect should have happened?
Invoke local should replicate lambda behavior of waiting event loop to be empty before executing the handler callback, unless context.callbackWaitsForEmptyEventLoop is set to false.
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Even though this is a lambda specific behavior, I think this event loop flag could be added to the documentation. My suggestion is in the invoke sessions.

* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.9.0
* ***Operating System***:  macOS
* ***Stack Trace***:
* ***Provider Error messages***:

### LINKED ISSUE #5848: Investigate Docker usage for invoke local
# This is a Feature Proposal

## Description

Investigate whether Docker is a feasible way to support `invoke local`. Please comment / add your reactions to this proposal.

/cc @serverless/framework-maintainers 

This will (probably) close:

Closes https://github.com/serverless/serverless/issues/4405
Closes https://github.com/serverless/serverless/issues/3456
Closes https://github.com/serverless/serverless/issues/4746
Closes https://github.com/serverless/serverless/issues/5542
Closes https://github.com/serverless/serverless/issues/3520

### PR DESCRIPTION
**Pull request by dschep**
This is a work in progress for implementing docker based invoke local support. 

 **Feedback greatly appreciated**

## What did you implement:
Closes #5848 by using docker with the [docker-lambda images from lambci](https://github.com/lambci/docker-lambda).
Closes #3456

The main benefits are:
 * More runtimes supported, even `provided`!
 * Layers support
 * runtime environments more closely resemble real lambda env
   * logging environment
   * paths (your handler is actually run at `/var/task`)
   * linux (as opposed to host OS)

The feature is currently implemented by default for previously unsupported runtimes, and can be enabled for python/javascript/java/ruby with the the `--docker` flag.

## How did you implement it:
* local layers are resolved by traversing the `Ref` and arn based layers are downloaded and extracted into `.serverless/invokeLocal/layers/<layername>`.
* generate `.serverless/invokeLocal/Dockerfile` with a `FROM` that bases it on `lambci/lambda:${runtime}` and then `ADD`s each layer to `/opt`
* build said `Dockerfile`
* run the image with working dir mounted as `/var/task` and passing the lambda and event as the arguments

## How can we verify it:
* install with `npm i -g serverless/serverless#invoke-local-docker`
* create an aws project
* `sls invoke local -f hello --docker`
* add a layer and try to use it again!

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by dschep** [comment]
I've tested with:
 * `nodejs8.10`
 * `provided`
   * bash based `aws-provided` template
   * https://github.com/dschep/sls-aws-lambci-nodejs10
 * `python3.7`
 * `go1.x`

File: lib/plugins/aws/invokeLocal/index.js [hunk 1]
```diff
@@ -10,6 +10,9 @@ const chalk = require('chalk');
 const stdin = require('get-stdin');
 const spawn = require('child_process').spawn;
 const inspect = require('util').inspect;
+const download = require('download');
+const jsZip = require('jszip');
+const mkdirp = require('mkdirp');
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Looks like some of the dependencies here need to be added to `package.json`.

In `jsZip` case it needs to be moved from `devDependencies` to `dependencies`. We could also check if `archiver` supports unzipping to save one dependency.

File: lib/plugins/aws/invokeLocal/index.js [hunk 2]
```diff
@@ -125,60 +128,75 @@ class AwsInvokeLocal {
...
+            .then(layerInfo => download(layerInfo.Content.Location))
+            .then(jsZip.loadAsync)
+            .then(zip => Promise.all(
+              Object.keys(zip.files)
+                .map(filename => zip.files[filename].async('nodebuffer').then(fileData => {
+                  if (filename.endsWith('/')) {
+                    return Promise.resolve();
+                  }
+                  mkdirp.sync(
+                    path.dirname(`.serverless/invokeLocal/layers/${arnParts[6]}/${filename}`));
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: I had to replace this with:

```suggestion
                    path.join('.serverless', 'invokeLocal', 'layers', `${arnParts[6]}/${filename}`);
```

File: lib/plugins/aws/invokeLocal/index.js [hunk 3]
```diff
@@ -125,60 +128,75 @@ class AwsInvokeLocal {
...
+
+    const imageName = 'sls-docker';
+
+    return layerPathsPromise.then(layerPaths => new BbPromise((resolve, reject) => {
+      let dockerfile = `FROM lambci/lambda:${runtime}`;
+      for (const layerPath of layerPaths) {
+        dockerfile += `\nADD --chown=sbx_user1051:495 ${layerPath} /opt`;
+        // fs.copySync(layerPath, `.serverless/invokeLocal/${layerPath}`);
+      }
+      mkdirp.sync(path.dirname('.serverless/invokeLocal'));
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: I had to replace this with:

```suggestion
      mkdirp.sync(path.join('.serverless' , 'invokeLocal'));
```

File: lib/plugins/aws/invokeLocal/index.js [hunk 4]
```diff
@@ -125,60 +128,75 @@ class AwsInvokeLocal {
...
+      fs.writeFileSync('.serverless/invokeLocal/Dockerfile', dockerfile);
+      this.serverless.cli.consoleLog('Building docker image...');
+      const docker = spawn('docker', ['build', '-t', imageName,
+        `${this.serverless.config.servicePath}`, '-f', '.serverless/invokeLocal/Dockerfile']);
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Same question about a potential `path.join` usage here.

File: lib/plugins/aws/invokeLocal/index.js [hunk 5]
```diff
@@ -125,60 +128,75 @@ class AwsInvokeLocal {
...
+
+    return layerPathsPromise.then(layerPaths => new BbPromise((resolve, reject) => {
+      let dockerfile = `FROM lambci/lambda:${runtime}`;
+      for (const layerPath of layerPaths) {
+        dockerfile += `\nADD --chown=sbx_user1051:495 ${layerPath} /opt`;
+        // fs.copySync(layerPath, `.serverless/invokeLocal/${layerPath}`);
+      }
+      mkdirp.sync(path.dirname('.serverless/invokeLocal'));
+      fs.writeFileSync('.serverless/invokeLocal/Dockerfile', dockerfile);
+      this.serverless.cli.consoleLog('Building docker image...');
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Do we keep this log later on or do we turn this into `this.serverless.cli.log` for a better formatting?

We could also break this down into separate steps a like "Downloading Image", "Buliding container" or something like that because it could take quite some time for larger images and slow internet connections.

File: lib/plugins/aws/invokeLocal/index.js (hunk 1 above)
Comment (dschep) [reply lib/plugins/aws/invokeLocal/index.js]: I'll look into `archiver`, but it's not a new dep afaik... i think archiver uses it internally

File: lib/plugins/aws/invokeLocal/index.js (hunk 5 above)
Comment (dschep) [reply lib/plugins/aws/invokeLocal/index.js]: Ah, oops. Just using the wrong function. As for splitting it, good idea 👍

**Comment by dschep** [comment]
Switched to `path.join`, the right logging func, and split download into its own step.

Also thinking layer content should be cached between invokations (SAM does this too). Should that live in a global cache/tmp dir? or in .serverless? Do we have any caching in the framework currently?

File: lib/plugins/aws/invokeLocal/index.js (hunk 1 above)
Comment (dschep) [reply lib/plugins/aws/invokeLocal/index.js]: switched to `download` lib's built-in extraction code 🙂

File: lib/plugins/aws/invokeLocal/index.js [hunk 6]
```diff
@@ -177,8 +189,145 @@ class AwsInvokeLocal {
...
+      docker.on('close', error => (error ? reject(error) : resolve(Boolean(stdout.trim()))));
+    });
+  }
+
+  pullDockerImage() {
+    const runtime = this.options.functionObj.runtime
+      || this.serverless.service.provider.runtime
+      || 'nodejs4.3';
+
+    this.serverless.cli.log('Downloading base docker image...');
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Probably personal preference, but I'd vote for `Docker` vs. `docker` since it's a company / product name.

File: lib/plugins/aws/invokeLocal/index.js [hunk 7]
```diff
@@ -177,8 +189,145 @@ class AwsInvokeLocal {
...
+          const layerArn = arnParts.slice(0, -1).join(':');
+          const layerVersion = Number(arnParts.slice(-1)[0]);
+          const layerContentsPath = path.join(
+            '.serverless', 'layers', arnParts[6], arnParts[7]);
+          const layerContentsCachePath = path.join(
+            cachePath, 'layers', arnParts[6], arnParts[7]);
+          if (fs.existsSync(layerContentsPath)) {
+            return layerContentsPath;
+          }
+          let downloadPromise = Promise.resolve();
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Same Promise-usage comment applies here.

File: lib/plugins/aws/invokeLocal/index.test.js [hunk 8]
```diff
@@ -468,10 +472,23 @@ describe('AwsInvokeLocal', () => {
...
-    it('throw error when using runtime other than Node.js, Python, Java or Ruby', () => {
-      awsInvokeLocal.options.functionObj.runtime = 'invalid-runtime';
-      expect(() => awsInvokeLocal.invokeLocal()).to.throw(Error);
-      delete awsInvokeLocal.options.functionObj.runtime;
+    it('should call invokeLocalDocker if using runtime provided', () => {
+      awsInvokeLocal.options.functionObj.runtime = 'provided';
+      awsInvokeLocal.options.functionObj.handler = 'handler.foobar';
+      return awsInvokeLocal.invokeLocal().then(() => {
+        expect(invokeLocalDockerStub.calledOnce).to.be.equal(true);
+        expect(invokeLocalDockerStub.calledWithExactly()).to.be.equal(true);
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.test.js]: What's the difference between this and `calledOnce`?

File: lib/plugins/aws/invokeLocal/index.test.js [hunk 9]
```diff
@@ -468,10 +472,23 @@ describe('AwsInvokeLocal', () => {
...
+      });
+    });
+
+    it('should call invokeLocalDocker if using --docker option with nodejs8.10', () => {
+      awsInvokeLocal.options.functionObj.runtime = 'nodejs8.10';
+      awsInvokeLocal.options.functionObj.handler = 'handler.foobar';
+      awsInvokeLocal.options.docker = true;
+      return awsInvokeLocal.invokeLocal().then(() => {
+        expect(invokeLocalDockerStub.calledOnce).to.be.equal(true);
+        expect(invokeLocalDockerStub.calledWithExactly()).to.be.equal(true);
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.test.js]: Same question about `calledOnce()` vs. `calledWithExactly()` here.

File: lib/plugins/aws/invokeLocal/index.test.js [hunk 10]
```diff
@@ -1097,4 +1114,85 @@ describe('AwsInvokeLocal', () => {
...
+      };
+    });
+
+
+    afterEach(() => {
+      delete require.cache[require.resolve('./index')];
+      delete require.cache[require.resolve('child_process')];
+    });
+
+    it('watwat', () =>
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.test.js]: 😅

File: lib/plugins/aws/invokeLocal/index.js [hunk 11]
```diff
@@ -177,8 +189,145 @@ class AwsInvokeLocal {
...
+  extractArtifact() {
+    const artifact = _.get(this.options.functionObj, 'package.artifact', _.get(
+      this.serverless.service, 'package.artifact'
+    ));
+    if (!artifact) {
+      return this.serverless.config.servicePath;
+    }
+    return fs.readFileAsync(artifact)
+      .then(jszip.loadAsync)
+      .then(zip => Promise.all(
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Same Promise-usage comment applies here.

File: lib/plugins/aws/invokeLocal/index.js [hunk 12]
```diff
@@ -177,8 +189,145 @@ class AwsInvokeLocal {
...
+        Object.keys(zip.files)
+          .map(filename => zip.files[filename].async('nodebuffer').then(fileData => {
+            if (filename.endsWith(path.sep)) {
+              return Promise.resolve();
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Same Promise-usage comment applies here.

File: lib/plugins/aws/invokeLocal/index.js [hunk 13]
```diff
@@ -177,8 +189,145 @@ class AwsInvokeLocal {
...
+          }))))
+      .then(() => path.join(
+        this.serverless.config.servicePath, '.serverless', 'invokeLocal', 'artifact'));
+  }
+
+
+  invokeLocalDocker() {
+    const handler = this.options.functionObj.handler;
+
+    return Promise.all([
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Same Promise-usage comment applies here.

File: lib/plugins/aws/invokeLocal/index.js [hunk 14]
```diff
@@ -177,8 +189,145 @@ class AwsInvokeLocal {
...
+    });
+  }
+
+  getLayerPaths() {
+    const layers = _.mapKeys(
+      this.serverless.service.layers,
+      (value, key) => this.provider.naming.getLambdaLayerLogicalId(key)
+    );
+
+    return Promise.all(
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Best would be to stick to one Promise implementation (`BbPromise` in this case).

Reason being that we once hunted down a race condition in the Serverless Variables implementation for days after figuring out that we used native Promises and Bluebird Promises in the same codebase and one implementation (probably Bluebird) was slightly faster.

File: lib/plugins/aws/invokeLocal/index.js [hunk 15]
```diff
@@ -177,8 +189,145 @@ class AwsInvokeLocal {
...
+
+    return new BbPromise((resolve, reject) => {
+      let dockerfile = `FROM lambci/lambda:${runtime}`;
+      for (const layerPath of layerPaths) {
+        dockerfile += `\nADD --chown=sbx_user1051:495 ${layerPath} /opt`;
+      }
+      mkdirp.sync(path.join('.serverless', 'invokeLocal'));
+      const dockerfilePath = path.join('.serverless', 'invokeLocal', 'Dockerfile');
+      fs.writeFileSync(dockerfilePath, dockerfile);
+      this.serverless.cli.log('Building docker image...');
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: Probably personal preference, but I'd vote for `Docker` vs. `docker` since it's a company / product name.

Comment (dschep) [reply lib/plugins/aws/invokeLocal/index.js]: Fair enough. When I think [Dd]ocker, I think `docker` bc it's `/usr/bin/docker` not `/usr/bin/Docker` 😜

File: lib/plugins/aws/invokeLocal/index.test.js (hunk 8 above)
Comment (dschep) [reply lib/plugins/aws/invokeLocal/index.test.js]: `calledOnce` ensures that the function wasn't called more than one time. `calledWithExactly` ensures that it was called _at least once with those exact arguments_, IE, it could be called any number of additional times with other arguments.

File: lib/plugins/aws/invokeLocal/index.js (hunk 15 above)
Comment (pmuens) [reply lib/plugins/aws/invokeLocal/index.js]: Make sense! 😊

**Comment by sheerun** [comment]
I get following error:

Serverless plugin "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js" initialization errored: Cannot find module 'jszip'

**Comment by triptec** [comment]
@dschep seems jszip is listed under devDependencies so that might need to be moved to devependencies. Thanks for the work by the way, looking forward to having this merged.

File: lib/plugins/aws/invokeLocal/index.js [hunk 16]
```diff
@@ -177,8 +189,145 @@ class AwsInvokeLocal {
...
+                { extract: true }));
+          }
+          return downloadPromise
+            .then(() => fse.copySync(layerContentsCachePath, layerContentsPath))
+            .then(() => layerContentsPath);
+        }));
+  }
+
+  buildDockerImage(layerPaths) {
+    const runtime = this.options.functionObj.runtime
```
Comment (pmuens) [inline lib/plugins/aws/invokeLocal/index.js]: This piece of code is used at least 4 times in this file alone. Maybe we can use a function like `getRuntime(this)` to DRY that out a little bit...

File: lib/plugins/aws/invokeLocal/index.test.js (hunk 8 above)
Comment (pmuens) [reply lib/plugins/aws/invokeLocal/index.test.js]: Makes sense...

File: lib/plugins/aws/invokeLocal/index.js [hunk 17]
```diff
@@ -177,8 +192,151 @@ class AwsInvokeLocal {
...
+          }
+          let downloadPromise = BbPromise.resolve();
+          if (!fs.existsSync(layerContentsCachePath)) {
+            this.serverless.cli.log(`Downloading layer ${layer}...`);
+            mkdirp.sync(path.join(layerContentsCachePath));
+            downloadPromise = this.provider.request(
+              'Lambda', 'getLayerVersion', { LayerName: layerArn, VersionNumber: layerVersion })
+              .then(layerInfo => download(
+                layerInfo.Content.Location,
+                layerContentsPath,
```
Comment (endeepak) [inline lib/plugins/aws/invokeLocal/index.js]: @dschep I think this should be downloading to `layerContentsCachePath` instead of `layerContentsPath`. Currently this code creates empty directory in `layerContentsCachePath` in first run and subsequent runs will have empty directory copied to `layerContentsPath`. Due to this handler fails to import layer in subsequent runs

Comment (endeepak) [reply lib/plugins/aws/invokeLocal/index.js]: I've raised an issue for this -> https://github.com/serverless/serverless/issues/5990

Comment (dschep) [reply lib/plugins/aws/invokeLocal/index.js]: Good catch
