### PR TITLE
Remove entrypoint subcmds in generateCommandsHelp

### LINKED ISSUE #3847: Commands Help prints entrypoint subcommands too
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Ran `sls package -h` and got:
```
$ sls package -h
Plugin: Package
package ....................... Packages a Serverless service
package function .............. undefined
    --stage / -s ....................... Stage of the service
    --region / -r ...................... Region of the service
    --package / -p ..................... Output path for the package
```

* What did you expect should have happened?

`package function ............. undefined` shouldn't be printed, since it's an entrypoint subcommand, refer:[package.js](https://github.com/serverless/serverless/blob/master/lib/plugins/package/package.js#L53).

## Additional Data

* ***Serverless Framework Version you're using***: 1.16.0
* ***Operating System***: macOS

### PR DESCRIPTION
**Pull request by darkowlzz**
## What did you implement:

Closes #3847 

## How did you implement it:

Added a loop to iterate through all the subcommands of the parent command and check for `type` of the command to be `entrypoint`. Subcommands with type `entrypoint` are deleted because they should be hidden.

## How can we verify it:

`sls package -h` results in:
```
Plugin: Package
package ....................... Packages a Serverless service
    --stage / -s ....................... Stage of the service
    --region / -r ...................... Region of the service
    --package / -p ..................... Output path for the package
```

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
If you use `pluginManager.getCommands()` to retrieve the commands, the entrypoints are automatically removed from the result list. The problem is, that entry points can be nested - getCommands() resolves the filtering.

**Comment by darkowlzz** [comment]
@HyperBrain is this okay or should I be thinking of an alternate solution?

Closing and reopening the PR to re-run the tests. Failure seems unrelated to the change 🤔

**Comment by darkowlzz** [comment]
huh! I would need help with the failing test

File: lib/classes/CLI.js [hunk 1]
```diff
@@ -149,6 +149,13 @@ class CLI {
     const command = this.serverless.pluginManager.getCommand(commandsArray);
     const commandName = commandsArray.join(' ');
 
+    // Remove entrypoint subcommands
+    _.forEach(command.commands, (details, cmd) => {
```
Comment (HyperBrain) [inline lib/classes/CLI.js]: This will only remove top-level entry points. As commands can contain multiple levels of subcommands, this won't work in case a sub-sub command would be an entrypoint.

A solution would be to fetch all commands and then just render the command out of that.
```
const allCommands = this.serverless.pluginManager.getCommands();
const command = _.reduce(commandsArray, (currentCmd, command) => {
  return currentCmd[command];
}, commandsArray);
// Now command contains the command given by commandsArray,
// or undefined, if any parent of the selected command is an entrypoint
// or the command does not exist
if (command) {
  // Command found
} else {
  // Command not found
}
```

Comment (HyperBrain) [inline lib/classes/CLI.js]: PS: I've written this out of my mind - and did not test it ;-)
Please check if there is an issue. In general the approach should work.

File: lib/classes/CLI.js [hunk 2]
```diff
@@ -146,9 +146,26 @@ class CLI {
...
 
+    // Get all the commands using getCommands() with filtered entrypoint
+    // commands and reduce to the required command.
+    const allCommands = this.serverless.pluginManager.getCommands();
+    const command = _.reduce(commandsArray, (currentCmd, cmd) => {
+      if (currentCmd.commands && cmd in currentCmd.commands) {
+        return currentCmd.commands[cmd];
+      }
+      return undefined;
+    }, { commands: allCommands });
```
Comment (darkowlzz) [inline lib/classes/CLI.js]: @HyperBrain implemented this based on your idea. Seems to work. Hope this is how you intended it to be :)

Comment (HyperBrain) [inline lib/classes/CLI.js]: Yep. This was what I had in my mind ;-)

Comment (pmuens) [inline lib/classes/CLI.js]: Thanks for fixing @darkowlzz and thanks for helping out @HyperBrain 👍
