### PR TITLE
Follow up fixes for #4713

### LINKED ISSUE #3627: 1.13.1 and 1.13.2 break ${self:} references.
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

running `sls package` against this serverless.yml file:
```yml
service: test
custom:
  test: ${self:}
  exportThis: ${self:custom.test.service}

provider: aws
```
causes an infinitely recursive loop that crashes serverless.

* What did you expect should have happened?

should have produced a package for deployment.

* What stacktrace or error message from your provider did you see?

```

<--- Last few GCs --->

[20894:0x104800000]   770076 ms: Mark-sweep 2790.2 (3047.1) -> 2790.1 (2985.1) MB, 2995.9 / 0.0 ms  last resort
[20894:0x104800000]   773017 ms: Mark-sweep 2790.1 (2985.1) -> 2790.1 (2960.1) MB, 2940.1 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x47a495266a1 <JS Object>
    1: _then [/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:~219] [pc=0x25add9e48667](this=0xeef459b2451 <a Promise with map 0x3014c5dce181>,didFulfill=0x718d9cf5c11 <JS Function gotAccum (SharedFuncti
onInfo 0x2a30dadc3eb9)>,didReject=0x24687c502311 <undefined>,_=0x24687c502311 <undefined>,receiver=0x8181f660071 <an Object with map 0x28376fe425d1>,internalDat...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3> >::ConvertElementsW
ithCapacity(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, unsigned int, unsigned int, unsigned int, int) [/usr/local/bin/node]
 7: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3> >::GrowCapacityAndC
onvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 8: v8::internal::(anonymous namespace)::FastElementsAccessor<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3> >::AddImpl(v8::inte
rnal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/usr/local/bin/node]
 9: v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow) [/usr/local/bin/node]
10: v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [/usr/loc
al/bin/node]
11: v8::internal::Runtime_SetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x25add98043a7
abort
```

## Additional Data

* ***Serverless Framework Version you're using***:  1.13.1 and 1.13.2; 1.13.0 does not exhibit the problem.
* ***Operating System***: 

```
; sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.4
BuildVersion:   16E195
```

### LINKED ISSUE #3711: Detect cyclic dependencies in Serverless Variable system
# This is a Feature Proposal

## Description

Given the fact that we're recursively resolving the variables it might be possible that developers create cyclic dependencies when using the variable system.

Serverless should detect those dependencies and throw an error if those are found.

One example can be found [here](https://github.com/serverless/serverless/issues/3627).

originally brought up by @sammarks in https://github.com/serverless/serverless/issues/3627#issuecomment-305080247

/cc @eahefnawy @brianneisler

### LINKED ISSUE #3740: JavaScript heap out of memory
# This is a Bug Report

## Description

Endless recursive file loading exceeds process memory limits.

When trying to remove the serverless.yml here:
https://github.com/Nordstrom/hello-retail/tree/master/web

With the command (STAGE is properly defined and references an existing stack):
```
../node_modules/.bin/sls remove -s $STAGE -v
```

* What went wrong?

```
<--- Last few GCs --->

[22378:0x102804600]   192582 ms: Mark-sweep 1484.5 (1567.0) -> 1484.5 (1567.0) MB, 2065.8 / 0.0 ms  allocation failure GC in old space requested
[22378:0x102804600]   194638 ms: Mark-sweep 1484.5 (1567.0) -> 1484.4 (1536.0) MB, 2056.4 / 0.0 ms  last resort gc 
[22378:0x102804600]   196780 ms: Mark-sweep 1484.4 (1536.0) -> 1484.4 (1536.0) MB, 2141.0 / 0.0 ms  last resort gc 


<--- JS stacktrace --->

==== JS stack trace =========================================

    2: arguments adaptor frame: 1->2
Security context: 0x90122ec0d31 <JS Object>
    3: _settlePromiseFromHandler [<src-root>/hello-retail/node_modules/serverless/node_modules/bluebird/js/release/promise.js:~496] [pc=0x20e01cfbd1f3](this=0x2d4a7d8ea59 <a Promise with map 0x17140f73cc21>,handler=0x2d4a7d97671 <JS Function getValueFromSource.then.valueToPopulate (SharedFunctionInfo 0x2b325a77f011)>,receiver=0x90122e04311 <undefined>,val...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [~/.nvm/versions/node/v7.2.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [~/.nvm/versions/node/v7.2.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [~/.nvm/versions/node/v7.2.0/bin/node]
 4: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [~/.nvm/versions/node/v7.2.0/bin/node]
 5: v8::internal::SourcePositionTableBuilder::ToSourcePositionTable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::AbstractCode>) [~/.nvm/versions/node/v7.2.0/bin/node]
 6: v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) [~/.nvm/versions/node/v7.2.0/bin/node]
 7: v8::internal::(anonymous namespace)::GenerateUnoptimizedCode(v8::internal::CompilationInfo*) [~/.nvm/versions/node/v7.2.0/bin/node]
 8: v8::internal::(anonymous namespace)::GetUnoptimizedCode(v8::internal::CompilationInfo*) [~/.nvm/versions/node/v7.2.0/bin/node]
 9: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [~/.nvm/versions/node/v7.2.0/bin/node]
10: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [~/.nvm/versions/node/v7.2.0/bin/node]
11: 0x20e01ca063a7
12: 0x20e01ca0675a
13: 0x20e01ca07e55
14: 0x20e01cfbd1f3
15: 0x20e01cfe1eb4
Abort trap: 6
```

* What did you expect should have happened?

Expected: removal of stack

Downgrading to serverless@1.11.0 allowed this to proceed as expected.

* What was the config you used?

https://github.com/Nordstrom/hello-retail/blob/master/web/serverless.yml

* What stacktrace or error message from your provider did you see?

see above.

## Additional Data

I suspect that this change may have introduced the new behavior but am not certain:
https://github.com/serverless/serverless/commit/971a27994c3566d9904f166a2e943c21ba4dfe54#diff-b921cbcedd2151d24391fb39acb84adeR88

* ***Serverless Framework Version you're using***: 1.13.2, 1.14.0
* ***Operating System***: osx
* ***Stack Trace***: see above
* ***Provider Error messages***: n/a

### LINKED ISSUE #3882: Hanging on sls deploy, with no output
# This is a (Bug Report / Feature Proposal)

## Description

* What went wrong?
I referenced custom variables in a file two folders higher in the folder hierarchy, and used them to set a variable in serverless.yml. When doing sls deploy, nothing happens, it just 'hangs', with no output, and I have to kill it. Like an infinite loop or recursion.

* What did you expect should have happened?
To set the variables properly and deploy ? ^^

* What was the config you used?
?

* What stacktrace or error message from your provider did you see?
None

It's kinda funny ^^"

## Additional Data

* ***Serverless Framework Version you're using***: 1.16.1
* ***Operating System***: macOS 10.13 beta(17A291j)
* ***Stack Trace***: None
* ***Provider Error messages***: None

Faulty lines in serverless.yml (makes sls deploy hang indefinitely):

```
custom:
  private: ${file(../../slsconf/private.yml)}
  sns: ${file(../../slsconf/sns.yml)}
```

Replacing them with the following works just fine
```
custom:
  private: ${file(../../slsconf/private.yml)}
  sns:
    topicNames:
    sources:
      source:
        action: sources_source_action_${self:provider.stage}
  arns:
    sources:
      source:
        action: arn:aws:sns:${self:provider.region}:${self:custom.private.IDs.aws}:${self:custom.sns.topicNames.sources.source.action}
```

Content of private.yml
```
APIKeys:
  baseSync: anApiKey
IDs:
  aws: myAwsId
misc:
  baseUserAgent: anUser/Agent
  baseTestClientDeviceUUID: anUUID
```

Content of sns.yml
```
topicNames:
  sources:
    source:
      action: sources_source_action_${self:provider.stage}

arns:
  sources:
    source:
      action: arn:aws:sns:${self:provider.region}:${self:custom.private.IDs.aws}:${self:custom.sns.topicNames.sources.source.action}
```

### LINKED ISSUE #4556: Referencing `${self:}` leads to crash in the print command
# This is a Bug Report

## Description

When referencing `${self:}` with the new circular variables support, the print command will crash with a stack overflow. (For details see https://github.com/serverless/serverless/pull/4144#pullrequestreview-82321021 and the discussion in the PR).

This is due to a missing circular object support in the modules to traverse the service object tree used by the print command.

### LINKED ISSUE #4687: All variables should resolve, timeout, or be identified
# This is a Bug Report

It is possible to define a project that never resolves variable population.

## Description

* What went wrong?
I attempted to package a project.  SLS loaded and then hung indefinitely.

* What did you expect should have happened?
I expected a package to be produced

* What was the config you used?
Simple config:
`serverless.yml`:
```
service: test
provider:
  name: aws
custom:
  project: ${file(./project.yml)}
```

`project.yml`:
```
foo: baz
bar:
  name: ${self:custom.project.foo}
```

* What stacktrace or error message from your provider did you see?
none is given

## Additional Data

I've instrumented the code and produced the following list of unresolved variable resolutions:
```
unsettled promises:
file(./project.yml) waited on by:
${file(./project.yml)}
${file(./project.yml)}

self:custom.project.foo waited on by:
${self:custom.project.foo}
```

The problem is that resolving `${file(./project.yml)}` involves, prior to replacing the `custom.project` attribute on the service object, attempting to resolve `${self:custom.project.foo}` which then circularly attempts to resolve `${file(./project.yml)}` again, resulting in a deadlock since `${file(./project.yml)}` now cannot resolve until `${file(./project.yml)}` is resolved.

It could have been any asynchronously resolving variable that referred to itself prior to being replaced in the origin object.

* ***Serverless Framework Version you're using***: 1.25.0 / master
* ***Operating System***: osx
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a

### LINKED ISSUE #4699: Program exits with no error(s) when there is error inside expression in serverless.yml
# This is a Bug Report

## Description

When there is error in serverless.yml file then when executing for example `sls deploy` or `sls package` or any other command that reads that file, then program exits and no errors are returned in console. In the config below there is error in provider.environment.S3_BUCKET_URL:

```
S3_BUCKET_URL: https://s3-${opt:region, self:provider.region}.amazonaws.com/${self:provider:environment.S3_BUCKET}
```

It should be `${self:provider.environment.S3_BUCKET}` instead of `${self:provider:environment.S3_BUCKET}` (note `:` after `provider`).  

Try to run `sls deploy` command with this config - program will just exit with no errors. Expecting to display error about bad expression in serverless.yml file. 

```yaml
service: hello-world

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    S3_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-audio-files
    S3_BUCKET_URL: https://s3-${opt:region, self:provider.region}.amazonaws.com/${self:provider:environment.S3_BUCKET}
    SNS_TOPIC_CONVERT_TEXT_TO_SPEECH: arn:aws:sns:${opt:region, self:provider.region}:#{AWS::AccountId}:convertTextToSpeech
  iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: "${self:provider.environment.SNS_TOPIC_CONVERT_TEXT_TO_SPEECH}"
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:PutObjectAcl
        Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
      - Effect: Allow
        Action:
          - polly:SynthesizeSpeech
        Resource: "*"

plugins:
  - serverless-offline
  - serverless-pseudo-parameters

functions:
  graphql:
    handler: dist/app.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  convertTextToSpeech:
    handler: dist/tasks/convertTextToSpeech.handler
    events:
      - sns:
          topicName: convertTextToSpeech
          displayName: Convert text to speech

resources:
  Resources:
    AudioFilesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    AudioFilesBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: ${self:provider.environment.S3_BUCKET}

```

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: Mac OS X
* ***Node.js***: v8.4.0

### LINKED ISSUE #4744: A valid service attribute to satisfy the declaration 'self:service.name' could not be found
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?

I'm trying to use dynamic variables in `serverless.yml` and it fails.
Basically, I have the following in my `provider`:

```
  environment:
    SERVICE_NAME: ${self:service.name}
    DYNAMODB_TABLE: ${self:service.name}-test
```
The `SERVICE_NAME` is correctly resolved **IF** I comment the `DYNAMODB_TABLE: "${self:service.name}-test"`, otherwise it fails with the following stack trace.

If I use `${self:service.name}` alone it works, but if I add some string after, then it fails: `${self:service.name}-test`

* What did you expect should have happened?

Resolving variables correctly

* What stacktrace or error message from your provider did you see?

```bash
➜  simulator-feedback git:(master) ✗ sls print
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
 
 Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:service.name' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:service.name' could not be found.
 
 
  Serverless Error ---------------------------------------
 
  Trying to populate non string value into a string for variable ${self:service.name}. Please make sure the value of the property is a string.
 
  Stack Trace --------------------------------------------
 
ServerlessError: Trying to populate non string value into a string for variable ${self:service.name}. Please make sure the value of the property is a string.
    at Variables.populateVariable (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:156:13)
    at pendingMatches.push.pendingMatch.then.matchedValue (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:124:21)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at property.match.forEach (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:122:40)
    at Array.forEach (<anonymous>)
    at Variables.populateProperty (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:111:41)
    at forEachLeaf (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:85:14)
    at forEachLeaf (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:75:14)
    at addContext (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:62:42)
    at /Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:13392:38
    at /Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:3002:24)
    at Function.mapValues (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:13391:7)
    at forEachLeaf (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:73:37)
    at addContext (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:62:42)
    at /Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:13392:38
    at /Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:3002:24)
    at Function.mapValues (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:13391:7)
    at forEachLeaf (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:73:37)
    at addContext (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:62:42)
    at /Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:13392:38
    at /Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:3002:24)
    at Function.mapValues (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/node_modules/lodash/lodash.js:13391:7)
    at forEachLeaf (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:73:37)
    at Variables.populateObject (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:79:5)
    at Variables.populateService (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/classes/Variables.js:47:17)
    at Serverless.run (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/lib/Serverless.js:89:27)
    at serverless.init.then (/Users/vadorequest/.nvm/versions/node/v8.9.4/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.4
     Serverless Version:     1.26.0

```

Similar or dependent issues:
* https://github.com/serverless/serverless/issues/3714

## Additional Data

* ***Operating System***: MacOS X

### PR DESCRIPTION
**Pull request by erikerikson**
## What did you implement:
Fixes:
1. deep variables can contain overwrites (see https://github.com/serverless/serverless/pull/4713#issuecomment-366975172 - thank you @laardee).  Reported on #4687.
2. deep variables can render to different variables and must thereby be deep-variable-ified too.  New bug of #4687 discovered fixing previous.
3. errors with the print command cross contaminating the given `serverless.yml` with the previously populated and adorned version processed by the framework.  OLD, painful, and previously unreported.
4. cleans a messy prepopulation implementation.  Closes #4744.
5. a cyclic references bug leading to crashes when using print.  Closes #3627, Closes #3711, Closes #3740, Closes #3882, Closes #4556, Closes #4687.
6. Silently undetected unresolved variables Closes #4699.
7. Support the variables `"${self:service.name}"` and `"${self:provider}"` which users expect to be valid because they are present in their `serverless.yml` but are mutated by the `Service` class.  Closes #4744.

## How did you implement it:

1. ensure that the `getValueFromDeep` method uses the standard logic for detecting and resolving overwrites rather than assuming that all deep variables are standard single variable strings.
2. add sophistication to `getValueFromDeep`, detecting recursive resolution to a new variable containing string.
3. clean caches for each invocation of variable population methods (primary entry points only).
4. knock out retrieval of restricted variable types for prepopulation, use existing methods.
5. clean caches.
6. Not exactly sure which change fixed this one.
7. Implement variable replacement for these special cases.

## How can we verify it:

`npm run test`

## Todos:

- [x] Write tests
- [n/a] Write documentation (no changes to existing documented variable system)
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
@laardee Can you give this PR a try and see if the problem is solved?

**Comment by erikerikson** [comment]
I have validated the latest push against the full materials @laardee provided.  Am awaiting @laardee's validation.  Apologies for the early push.

**Comment by laardee** [comment]
Yes, now it packages our project at least as good as before. This, or the previous PR, fixes also the issue that we faced with @medikoo where the region variable was not resolved early enough for SSM variables.

**Comment by erikerikson** [comment]
I have detected a returned cyclic error here.  So many configs to check...
Will update as I know more.

**Comment by erikerikson** [comment]
This cyclic issue is restricted to the print command.  Continuing investigation.

**Comment by erikerikson** [comment]
This should be ready for merge.

**Comment by HyperBrain** [comment]
@erikerikson Wow. Thank you. Can you add all issues that are closed by this PR (there seem to be a whole lot of them 😄 ) as `Closes #` to the description? We should make sure that everything is cleaned up with the merge.

File: lib/classes/Variables.js [hunk 1]
```diff
@@ -10,90 +10,102 @@ const fse = require('../utils/fs/fse');
 const logWarning = require('./Error').logWarning;
 const PromiseTracker = require('./PromiseTracker');
 
+/**
```
Comment (HyperBrain) [inline lib/classes/Variables.js]: ❤️

File: lib/classes/Variables.js [hunk 2]
```diff
@@ -495,9 +522,18 @@ class Variables {
   }
 
   getValueFromSelf(variableString) {
+    let variable = variableString;
+    // The loaded service is altered during load in ~/lib/classes/Service (see loadServiceFileParam)
+    // Account for these so that user's reference to their file populate properly
+    if (variable === 'self:service.name') {
```
Comment (HyperBrain) [inline lib/classes/Variables.js]: Maybe we can add a comment to the `Service` class at the proper location to warn people, that any changes done there that affect the service property, have to be checked with this implementation too?

File: lib/plugins/print/print.js [hunk 3]
```diff
@@ -23,29 +25,76 @@ class Print {
...
+    if (_.isObject(this.cache.serviceService)) {
+      service.service = service.service.name;
+      service.serviceObject = this.cache.serviceService;
+    }
+    // provider treatment and defaults
+    this.cache.serviceProvider = service.provider;
+    if (_.isString(this.cache.serviceProvider)) {
+      service.provider = { name: this.cache.serviceProvider };
+    }
+    service.provider = _.merge({
```
Comment (HyperBrain) [inline lib/plugins/print/print.js]: This should be only done if the provider is set to `aws`, shouldn't it? The print command is located at top level (outside of the aws plugin) and might be called for arbitrary provider types.

File: lib/classes/Variables.js (hunk 2 above)
Comment (erikerikson) [reply lib/classes/Variables.js]: Really good point.  Missed commenting this.  Adding additional comment here too.

File: lib/plugins/print/print.js (hunk 3 above)
Comment (erikerikson) [reply lib/plugins/print/print.js]: I would have expected so too.  However, the code in ~/lib/classes/Service.js (https://github.com/serverless/serverless/blob/bf5a8c9fd4a90946f1862e1837e6899b542d4cb2/lib/classes/Service.js#L19) does this, I believe generally, for all services.  Do I misunderstand?  Otherwise, I'm happy to improve this.

**Comment by erikerikson** [comment]
Thanks for the kick to actually read docs on how the title "closes #..."/keywords feature :D

I have added comments as discussed.  If you agree with my analysis of the print.js, line 41 comment, this should be ready to merge but otherwise, I'll fix it.

File: lib/plugins/print/print.js (hunk 3 above)
Comment (HyperBrain) [reply lib/plugins/print/print.js]: Indeed 🤔 . So it seems to be just an initial value there (that will be overridden by the incoming service configuration). In theory, a service.yml without provider definition would work then, which is a bit strange, but so be it.

However, here in the print command I'm not really sure if that, what we do here, is really just a preliminary intialization that will be overwritten or will influence subsequent behavior.

**Comment by HyperBrain** [comment]
@erikerikson I meant in the bug description, not subject 😆

File: lib/plugins/print/print.js (hunk 3 above)
Comment (erikerikson) [reply lib/plugins/print/print.js]: Yeah, it was weird to see at first but I faulted on the side of parity to avoid bugs resulting from dissonance.  Thank you very much for paying attention here!

**Comment by HyperBrain** [comment]
Merged. Hopefully some people will test with master and verify that the covered cases now work as expected.

**Comment by laardee** [comment]
Some people here :grinning: I quickly tested with the master and now I get some errors with SSM parameters and provider/region. 

I have a `my-ssm-parameter` stored in eu-west-1. `sls package --region eu-west-1` should then resolve the value of the `my-ssm-parameter`. It works ok with v1.26.

```yaml
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  environment:
    MY_SSM_PARAM: ${ssm:my-ssm-parameter}
```

But it fails with error `Variable Failure: value region set to 'ssm:my-ssm-parameter' references SSM which requires a region value for use.` with the master.

Adding the region to the provider doesn't help either and packaging with `sls package` and `sls package --region eu-west-1` fails with same error. This also works with v1.26.
 
```yaml
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  environment:
    MY_SSM_PARAM: ${ssm:my-ssm-parameter}
```

But when I add the region to custom and refer to it in provider, packaging works as expected. 

```yaml
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ${self:custom.region}
  environment:
    MY_SSM_PARAM: ${ssm:my-ssm-parameter}

custom:
  region: eu-west-1
```
This last setup is about the same that we have. We have the region in a file, but somewhat similar. I used that setup to test the PR earlier so I didn't catch this. 😞

@HyperBrain @erikerikson can you quickly check if my findings are valid.

**Comment by erikerikson** [comment]
Thanks for reporting/finding this @laardee, we're working from an unfortunate deficit of test cases.

I'll look into it shortly.

**Comment by erikerikson** [comment]
I've reproduced this and discovered the error.  I created a timing issue based on the resolution order of the promises but on a positive note, it should be simple to test for and fix.  Incoming...

**Comment by erikerikson** [comment]
Just commited tests for the case you encountered and a fix.  PR #4769

I also ran the new code against your provided config using the cmd line you gave.  I got the expected error from SSM rather than this codebase.

Apologies for the train of issues.

**Comment by laardee** [comment]
That PR #4769 fixes all of the issues I encountered earlier with the SSM.

**Comment by HyperBrain** [comment]
Ok. I'll merge the update/fix PR now. Then master can be given a second try and further round of testing 😄

**Comment by laardee** [comment]
All my use cases work now with the master branch 👏

**Comment by dschep** [comment]
What about `${self:service.awsKmsKeyArn}`? This doesn't seem to fix that. Should I file a separate issue?

**Comment by erikerikson** [comment]
What's the issue @dschep?  Link?

**Comment by dschep** [comment]
It doesn't get populated:
```
$ sls create -t aws-nodejs
$ sed -i'' -r -e 's/service: aws-nodejs ?.*$/service:\n  name: aws-nodejs\n  awsKmsKeyArn: arn:aws:kms:us-east-1:xxxxxxxxxxxx:key\/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/' serverless.yml # NOTE: that's GNU sed
$ echo -e 'custom:\n  arn: ${self:service.awsKmsKeyArn}' >> serverless.yml
$ sls print
 
 Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:service.awsKmsKeyArn' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:service.awsKmsKeyArn' could not be found.
 
service:
  name: aws-nodejs
  awsKmsKeyArn: 'arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
custom: {}
```

Note that the above is with `npm i -g serverless/serverless`, with sls 1.26.1 I get:
```
$ sls -v
1.26.1
$ sls print
 
 Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:service.awsKmsKeyArn' could not be found.
 
service:
  name: aws-nodejs
  awsKmsKeyArn: 'arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
custom:
  arn: 'arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'

```

**Comment by erikerikson** [comment]
Thank you.  I'll look into it.

**Comment by erikerikson** [comment]
It turns out that I don't have GNU sed.  To verify, your `sed` replaces
```
service: aws-nodejs
```
with
```
service:
  name: aws-nodejs
  awsKmsKeyArn: arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
right?

It looks like we need to rewrite `self:service.[...]` to `self:serviceObject.[...]` to cover any cases here.  Simple change....

**Comment by erikerikson** [comment]
@dschep fixed in https://github.com/serverless/serverless/pull/4859

Please take a look/try it out.
