### PR TITLE
Ignore & warn on invalid yaml values

### LINKED ISSUE #4258: `sls plugin install` fails
# This is a Bug Report

## Description

When installing a plugin with a command like:
`sls plugin install --name serverless-webpack`

The command fails with the error:
`Type Error: Cannot read property 'kind' of null`

## Additional Data

* ***Serverless Framework Version you're using***: 1.22
* ***Node.js Version you're using***: 8.5.0
* ***Operating System***: macos

### PR DESCRIPTION
**Pull request by ryanmurakami**
## What did you implement:

Fixes #4258.
If the yaml is being parsed and an invalid value is found:
eg.
```yaml
service:
  name: my-service
  spotinst:

functions:
...
```
Previously, the process would fail completely. This change is to warn the user and continue on, ignoring the invalid value.

## How did you implement it:

Log a warning to the console and continue.

## How can we verify it:

Create a `serverless.yml` with an invalid value and try to install a plugin in the directory:
`serverless plugin install --name serverless-webpack`

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/utils/yamlAstParser.js [hunk 1]
```diff
@@ -24,6 +25,11 @@ const parseAST = (ymlAstContent, astObject) => {
   let newAstObject = astObject || {};
   if (ymlAstContent.mappings && _.isArray(ymlAstContent.mappings)) {
     _.forEach(ymlAstContent.mappings, (v) => {
+      if (!v.value) {
+        console.log(`Serverless: ${chalk.red(`Your serverless.yml has an invalid value with key: ${v.key.value}. Ignoring...`)}`);
```
Comment (horike37) [inline lib/utils/yamlAstParser.js]: You might want to use `BbPromise.reject`. console.log can't use the Framework since following the lint rule

Comment (horike37) [reply lib/utils/yamlAstParser.js]: In addition, you have faced `Line 29 exceeds the maximum line length of 100` lint error.
You need to spirit the line something like this
```javascript
const errorMessage = [
 `${chalk.red(`Your serverless.yml has an invalid value with key: `,
 `${v.key.value}. Ignoring...`,
 ].join('');
```
