### PR TITLE
Fix for #2685

### LINKED ISSUE #2685: invoke --data '{ json }' does not parse for Java Lambdas
# This is a (Bug Report / Feature Proposal)
Bug
## Description
The --data argument to 'serverless invoke' is not deserializable in Java lambdas.
For bug reports:
* What went wrong?
Create the sample java lamba
Run 
serverless invoke -f hello --data '{ "key1" : "pwd" }'
( and yes I have tried with all 3 keys )

Result:
```
[0][dlee@z600 newService]$ serverless invoke -f hello  --data '{ "key1" : "pwd" }'
{
    "errorMessage": "An error occurred during JSON parsing",
    "errorType": "java.lang.RuntimeException",
    "stackTrace": [],
    "cause": {
        "errorMessage": "com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class hello.Request] from String value ('{ \"key1\" : \"pwd\" }'); no single-String constructor/factory method\n at [Source: lambdainternal.util.NativeMemoryAsInputStream@dc24521; line: 1, column: 1]",
        "errorType": "java.io.UncheckedIOException",
        "stackTrace": [],
        "cause": {
            "errorMessage": "Can not instantiate value of type [simple type, class hello.Request] from String value ('{ \"key1\" : \"pwd\" }'); no single-String constructor/factory method\n at [Source: lambdainternal.util.NativeMemoryAsInputStream@dc24521; line: 1, column: 1]",
            "errorType": "com.fasterxml.jackson.databind.JsonMappingException",
            "stackTrace": [
                "com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)",
                "com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:875)",
                "com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:281)",
                "com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:284)",
                "com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1176)",
                "com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:143)",
                "com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:134)",
                "com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)",
                "com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)"
            ]
        }
    }
}
```

OTOH run aws cli

`aws lambda invoke --function-name newService-dev-hello  --payload '{ "key1" : "pwd" }'
`
The payload parses and the result is correct.

Also run

`serverless invoke -f hello --path data.json
`
Where 'data'json' has the same content. 
Result: works as expected.

* What did you expect should have happened?

Payload data pass unchanged so it would deserialize properly

* What was the config you used?

unmodified java8 runtime

* What stacktrace or error message from your provider did you see?
given

* ***Serverless Framework Version you're using***:
1.1.0
* ***Operating System***:
centos7

* ***Stack Trace***:
provided
* ***Provider Error messages***:
provided

### PR DESCRIPTION
**Pull request by ac360**
## What did you implement:

Closes #2685

WIP – Waiting on the gentleman who posted the issue to confirm this fix.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by dougmoscrop** [comment]
Doesn't this technically break backwards compatibility? Like, functions don't *have* to take JSON right? They can take strings? `sls invoke -f uppercase --data=foo` => `FOO`

**Comment by mthenw** [comment]
Valid point @dougmoscrop. We need to check that before merging.

**Comment by pmuens** [comment]
@dougmoscrop @mthenw nice catch!

I just added a check if it is a simple string or JSON so that only JSON will be parsed.

File: lib/plugins/aws/invoke/index.js [hunk 1]
```diff
@@ -28,6 +28,17 @@ class AwsInvoke {
     // validate function exists in service
     this.options.functionObj = this.serverless.service.getFunction(this.options.function);
 
+    // if data is provided via CLI, sanitize it
+    if (this.options.data && typeof this.options.data === 'string') {
```
Comment (mthenw) [inline lib/plugins/aws/invoke/index.js]: `if (typeof this.options.data === 'string') {`

is enough

Comment (mthenw) [inline lib/plugins/aws/invoke/index.js]: BTW can it be something different than string?

Comment (pmuens) [inline lib/plugins/aws/invoke/index.js]: Thanks! I'll fix this.

Not sure if it can be smth. different. /cc @eahefnawy @ac360

File: lib/plugins/aws/invoke/index.js [hunk 2]
```diff
@@ -28,6 +28,16 @@ class AwsInvoke {
     // validate function exists in service
     this.options.functionObj = this.serverless.service.getFunction(this.options.function);
 
+    // if data is provided via CLI, sanitize it
+    if (typeof this.options.data === 'string') {
+      try {
+        this.options.data = JSON.parse(this.options.data);
```
Comment (dzimine) [inline lib/plugins/aws/invoke/index.js]: Here is a problem: what if I want the data to come to Lambda as string? 

In number of cases, including default "PROXY", the body is passed to handler's `event` as string, and Lambda handler needs to convert the string to JSON. 

Please have an option to skip this conversion.

Comment (pmuens) [inline lib/plugins/aws/invoke/index.js]: Nice catch @dzimine 👍 

Maybe we should open up an issue so that we can track that.
Could you do that @dzimine? Thanks!

Related to https://github.com/serverless/serverless/issues/3691.
