### PR TITLE
2116 consistent errors missing config

### LINKED ISSUE #2116: DX: Consistent error messages when running commands without serverless.yml
# This is a Bug Report
## Description

For bug reports:
- What went wrong?

Wrong error message when running commands inside directory without serverless.yml

```
➜  ~ sls deploy

  Serverless Error ---------------------------------------

     This command can only be run inside a service directory

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

➜  ~ sls remove

  Serverless Error ---------------------------------------

     The command you entered was not found.
     Did you
     spell it correctly?

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

➜  ~ sls info

  Serverless Error ---------------------------------------

     The command you entered was not found.
     Did you
     spell it correctly?

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```
- What did you expect should have happened?

Error messages should be consistent

### PR DESCRIPTION
**Pull request by shanehandley**
## What did you implement:

Closes #2116

When running a serverless command which reads serverless config during execution in a path without an existing serverless config file, the messaging presented to the dev was inconsistent. It was picked up and reported by two plugins, but the remainder failed to identify the issue and either failed silently or reported that the command was not found.

## How did you implement it:

Validation of the command being run in a serverless directory was done on a per-command basis. This was changed so that the validation is performed within the plugin manager during execution, catching a flag defined in the plugin configuration.

## How can we verify it:

`git clone https://github.com/shanehandley/serverless`
`git co 2116-consistent-errors-missing-config`

Then run the command via `bin/serverless` example:

`bin/serverless config` should correctly fail with `This command can only be run in a Serverless service directory`

This should report correctly for applicable commands:

| Command|
| ------------- |
|Info|
|deploy|
|config|
|install|
|invoke|
|logs|
|metrics|
|package|
|print|
|remove|
|rollback|
|slstats|

## Documentation

No documentation has been added at this stage, as it provides a non-essential developer convenience to built-in commands. 

## Todos:

- [x] Write tests
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by shanehandley** [comment]
Note that [this PR](https://github.com/serverless/serverless/pull/5314) is affected by this change. The two should be resolvable without much work.

File: lib/classes/PluginManager.js [hunk 1]
```diff
@@ -429,6 +430,29 @@ class PluginManager {
     this.getCommand(commandsArray);
   }
 
+  /**
+   * If the command has no use when operated in a working directory with no serverless
+   * configuration file, throw an error
+   */
+  validateServerlessConfigDependency(command) {
+    if (_.has(command, 'configDependent') && command.configDependent === true) {
+      return getServerlessConfigFile(process.cwd()).then((result) => {
```
Comment (erikerikson) [inline lib/classes/PluginManager.js]: using cwd here rather than `sls.servicePath` is inconsistent (as I think you've noticed).  happy to adjust and fix it in #5314 but I'd be plenty happy with closing mine if it gets fixed here

File: lib/classes/PluginManager.js [hunk 2]
```diff
@@ -429,6 +430,29 @@ class PluginManager {
     this.getCommand(commandsArray);
   }
 
+  /**
+   * If the command has no use when operated in a working directory with no serverless
+   * configuration file, throw an error
+   */
+  validateServerlessConfigDependency(command) {
+    if (_.has(command, 'configDependent') && command.configDependent === true) {
```
Comment (erikerikson) [inline lib/classes/PluginManager.js]: could be:
```
if ('configDependent' in command && command.configDependent)
```

File: lib/plugins/print/print.js [hunk 3]
```diff
@@ -96,6 +97,14 @@ class Print {
     // preparation for printing the service for the user.
     return getServerlessConfigFile(process.cwd())
       .then((svc) => {
+        const isRunInService = !!svc;
```
Comment (erikerikson) [inline lib/plugins/print/print.js]: is this not redundant?  the risk of the file being deleted between plugin load and reloading the file here seems small.

File: lib/classes/PluginManager.js [hunk 4]
```diff
@@ -429,6 +430,29 @@ class PluginManager {
...
+      return getServerlessConfigFile(process.cwd()).then((result) => {
+        const isRunInService = !!result;
+
+        if (!isRunInService) {
```
Comment (erikerikson) [inline lib/classes/PluginManager.js]: Here and in print.js, the similar code could be simply:
```
if (!service) {
```
That seems fairly clear, the triple `!` seems unnecessary.  Maybe there's something I'm not seeing that you're trying to guard against?
Note that I also suggested `service` which here means a rename of `result` but in print.js implies a new position for the conditional (assuming my comment there is misled).

Comment (shanehandley) [reply lib/classes/PluginManager.js]: Yeah - The !! & ! was from the initial implementation from `plugins/lib/validate.js` and I suspect the reasoning was that `getServerlessConfigFile` will return an empty string when it fails to lookup, and they were trying to explicitly cast to Boolean. I agree it is unnecessary, and have updated accordingly 👍

File: lib/plugins/print/print.js (hunk 3 above)
Comment (shanehandley) [reply lib/plugins/print/print.js]: It is indeed! I must have implemented it here early on before changing strategy. It has been removed 👍

**Comment by shanehandley** [comment]
Thanks for the review @erikerikson 👍 I've made changes according to your comments, but I am conscious of conflicts between our branches with the switch from `process.cwd()` to getting the path from `this.serverless.config` so I have avoided changing too much there.

File: lib/plugins/print/print.js (hunk 3 above)
Comment (erikerikson) [reply lib/plugins/print/print.js]: Your comment here had led me to expect this code would disappear: https://github.com/serverless/serverless/pull/5298/files#diff-5c58e3ad980e17d98380999420228cfdR100

For the record, just noting I was a little confused.  Thanks for the changes!
Also for the record, I'm not a maintainer so I am limited in my ability to move things forward here, sorry :D

Comment (shanehandley) [reply lib/plugins/print/print.js]: 😬  Sorry my commit failed to push due to connectivity issues - should be sorted now.

No worries thank you for your review 👍

File: lib/classes/PluginManager.js [hunk 5]
```diff
@@ -429,6 +430,28 @@ class PluginManager {
     this.getCommand(commandsArray);
   }
 
+  /**
+   * If the command has no use when operated in a working directory with no serverless
+   * configuration file, throw an error
+   */
+  validateServerlessConfigDependency(command) {
+    if ('configDependent' in command && command.configDependent) {
+      const servicePath = this.serverless.config.servicePath || 'x';
```
Comment (erikerikson) [inline lib/classes/PluginManager.js]: Consider leaving defaulting to `getServerlessConfigFile` now?  (See https://github.com/serverless/serverless/pull/5314/files#diff-045b1def1b55ed8f81130ccff02544a5R10)

**Comment by softprops** [comment]
@shanehandley is this good to go then?
