### PR TITLE
 `--config` option

### LINKED ISSUE #4124: Feature Proposal: Serverless should support being able to supply path to .yml file to use for configuration
# Summary

serverless framework is currently wedded to a few concepts which make it very cumbersome to share javascript code and compiler compilation contexts between many node 'micro-service' stacks.  Specifically the fact that serverless does not allow specifying a path to the serverless config file pushes every set of cloud-formation stacks deployed by serverless toward needing to be a separate npm package.  This requirement is essentially enforced by the framework due to the framework not exposing any mechanism's for supplying a path to the serverless config file to use for a given serverless invocation.

# Problems

Forcing developers toward describing every stack as an npm package adds a lot of overhead to the development process -- particularly when its desirable to share code between stacks.  

What overhead is added by the need to describe each serverless stack as an npm package?  How much of this overhead is incidental complexity vs actually useful modularization?  I argue that for many projects/contexts, this requirement adds a large amount of incidental complexity with net negative benefit rather than encouraging useful patterns:

- every serverless deployable stack needs to setup and define its tooling environment.  Modern tooling requirements for javascript codebases are extensive (compilers/transpilers, test runners, linters, ide integrations).  Re-use of these processes between related projects is enormously beneficial.  It seems to be true that in general -- the fewer the number of packages for which you have to setup this tooling when working on related code, the better the development experience you can arrange for your team.

- every serverless deployable stack needs to describe full set of dependencies, devDependencies and needs to separately install those dependencies in order for the serverless commands to be runnable.  Full-encapsulation of development environment (rather than requiring the installation of tools globally) into package.json is very nice -- so if you wish to package all the required development dependencies then every stack deployment context ends up needing to install its own copy of the serverless framework.  If you are a using compiler/linter, every stack is also going to need its own copy of the compiler and linter (and configuration of those).  Every stack deployment context is going to need to manage versions of these things, is going to have to install these things when setting up the development context for each stack and when running automated tests for each stack.  

- its very difficult to share code between stacks.  Simple solutions for sharing code between stacks that rely on node's module resolution algorithm to organize shared dependencies won't work.  Furthermore, 'normal' techniques for easing development of related sets of npm packages won't work well with serverless because serverless doesn't handle packaging of symlinked node dependencies in a good way.  
  - tools like `npm link`lerna/yarn-workspaces which aim to ease development of related sets of npm packages also don't work well with serverless.  If lerna symlinks related-module-a into service-b/node_modules/, then when serverless is packaging service-b all of 'related-module-a/node_modules/' will be packaged into service-b including all the dev dependencies for related-module-a (not to mention source artificats, the set of things normally excluded by .npmignore etc) ...  This will generally make the package too large to deploy when packages have a lot of devDependencies.  This fact basically breaks the ability to use lerna to ease the development process of related-module-a in the context of testing/deploying/packaging service-b.
   - even if we could use lerna, the whole lerna concept is something of a large hack and for many projects introduces a large amount of complexity that may not actually be needed.

# Goals

For my purposes my goals are:

- easily share code generated from a single compilation and testing context between serverless deployed stack's
- manage devDependencies and tooling configuration for as much of the codebase as possible in a single place (shared code should be in the same compilation context for ensuring smoothest path to maximum benefit from compiler and ide tooling)
- support easily creating new variations of a stack for use in automated testing or to deal with other kinds of strange business/development requirements -- ideally by just copying/modifying a serverless.yml file
- get the best experience from ide's

The pattern I've fallen on is to structure our repository like this:

```
.serverless_plugins/    <-- custom plugins -- should be shareable between stacks
package.json               <-- scripts to start compiler, run tests etc.  
jest.json
jest.debug.json
tsconfig.json
tslint.json
wallaby.js
src/    <-- typescript code
lib/     <-- compiled javascript
services/some_service/serverless.yml
services/some_service/node_modules => ../../node_modules/
services/some_service/package.json => ../../package.json/        <-- needed to expose devDependencies to serverless packaging process
services/some_service/lib/ => ../../lib/
services/some_service/.serverless_plugins/ ../../.serverless_plugins/
```

The basic idea of above pattern is to use symlinks to trick serverless so that running `serverless` command from any services/*/ directory behaves as if you had copied the serverless.yml file into the project root directory and ran serverless from there.

# Solution

I really think a behavior like this should just be supported by default without having to use symlinks to hack a serverless.yml file into the execution context of another folder.  I'd like an option to allow providing a path to a yml file to use for serverless config.  This should interpret the config file as if the config file was located in the cwd() -- paths defined in config files should be specified relative to the cwd() -- everything should be executed just as if you had moved the configuration file to ./serverless.yml prior to execution.

# Alternative

If adding the requested feature and exposing to users the ability to control which config file to use from the command line isn't deemed desirable -- would a pull request that modified the Service class and Serverless constructor to allow easier implementation via a custom subclass of the Serverless class be accepted?

Right now I'm monkey patching the serverless framework to allow using alternative config files in my automated testing environments ...  Its not pretty and involved by necessity some copy/pasting but essentially required changing Service.load method to consider options passed to Service constructor ...  A little bit of changes to the framework could greatly ease this customization ...

```
    // PATCHED: attempt to get serviceFilenames from `that` rather than only supporting hard-coded paths ...
    // List of supported service filename variants.
    // The order defines the precedence.
    const serviceFilenames =
      that.serviceFilenames != null
        ? that.serviceFilenames
        : ["serverless.yaml", "serverless.yml", "serverless.json"];
```

And then hacking the Serverless constructor to use my patched Service subclass and pass in custom path to serverless config file ...

```
export class JestServerlessConfig extends Serverless {
  constructor(serverlessContext: JestServerlessContext) {
    // configure servicePath ...
    super({
      // set servicePath to the directory in which you want serverless command to execute (abs path)
      servicePath: serverlessContext.executionPath,
      interactive: false
    });

    // HACK: re-create the service, this time with patched behavior ...
    this.service = new JestServerlessServicePatch(this, {
      serviceFilenames: [serverlessContext.relativeServerlessConfigPath]
    });

    // HACK: Variables class picks off this.serverless.service instance inside constructor and saves it ... --
    // make sure to update that reference to point at patched object...
    this.variables.service = this.service;

    this._jestServerlessContext = serverlessContext;
  }
```

I also have to monkey patch serverless/lib/utils/getServerlessConfigFile.

# Other Alternative

Its possible I could add webpack to my build process and generate a bundle including all required node_modules for each services/*/ directory.  This could be a good alternative but webpack is complicated (and it would be much slower).  It also wouldn't really work all that well many varieties of common testing tools.  The need to do this ultimately results from a small addressable limitation of the serverless framework which I think would be better to handle with what seems a small augmentation to the framework...

### LINKED ISSUE #4473: Allow explicitly specifying `serverless.yml` file in CLI options or env var
# This is a (Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I'd like to make different deployments in dev/stage/prod environments, and I need to include or exclude certain config blocks conditionally in `serverless.yml`, which is not supported by now.

Instead of implementing conditional logic into `serverless.yml`, a simpler way is to allow the CLI accepts an explicit '-f' option, or an env var, then we could put different configs in `serverless.dev.yml` and `serverless.prod.yml`, etc.

Or even better, the main `serverless.yml` file is always taken and user could specify **extra** config files to be merged with the main config, like how `docker-compose -f` works.

* If there is additional config how would it look

Similar or dependent issues:
None

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### LINKED ISSUE #4485: Custom config template name - my-serverless.yml
# This is a Feature Proposal

## Description

For bug reports:
* What went wrong? *n/a*
* What did you expect should have happened? *n/a*
* What was the config you used? *n/a*
* What stacktrace or error message from your provider did you see? *n/a*

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

On our projects, we frequently have multiple related serverless services (typically ones that touch shared stateful resources or align to similar business domains) in the same repo to maintain a consistent life-cycle across them. We separate them into multiple services for a number of reasons - sometimes they are logical separations (the services have fundamentally separate purposes), and other times it is a technical limitation (too many resources for a single Cloudformation stack). But what we end up with is two services that need access to the same codebase and often a shared set of configuration values. It would be nice for us to store multiple `serverless.yml` files side-by-side as such:
```
.
+-- serverless-api.yml
+-- serverless-workflow1.yml
+-- serverless-workflow2.yml
+-- app
|   +-- __init__.py
|   +-- py_module.py
```
* If there is additional config how would it look

I would imagine this could be easily implemented as a command-line option:
```bash
$ serverless deploy --configFile <path/to/config>
```

I would be more than happy to help make this feature a reality. A quick glance at the codebase makes it seem like the change would be relatively straight-forward.

Similar or dependent issues:
None that I could find (I dug for a while, I promise).

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### LINKED ISSUE #5822: Config should also be read from serverless.config.js file.
# This is a Bug Report

## Description

* What went wrong?
When using a js config file (serverless.js) "npx serverless" opens this file in my editor instead of running the serverless executable.
I guess this is why for example webpack uses webpack.config.js by default as the name of config files.
* What did you expect should have happened?
npx serverless should run the executable no matter if you use a yml or json or js config.
I think the js-type config file should be read both from serverless.js for backward compatibility and serverless.config.js to avoid this issue.
* What was the config you used?
Doesn't matter as long as your config file is js.
* What stacktrace or error message from your provider did you see?
N/A

## Additional Data

* ***Serverless Framework Version you're using***:
1.37.1
* ***Operating System***:
Windows 10

### PR DESCRIPTION
**Pull request by dschep**
## What did you implement:

closes #5589
closes #4485
closes #4473
closes #4124
closes #5822

## How did you implement it:

updated `getServerlessConfigFileName` and refactored things to only use it, not any other methods of getting the config file

## How can we verify it:

```
npm i -g serverless/serverless#config-option
sls create -t aws-nodejs
mv serverless.yml foobar.yml
sls deploy --config foobar.yml
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/Serverless.js [hunk 1]
```diff
@@ -30,8 +30,12 @@ class Serverless {
     this.variables = new Variables(this);
     this.pluginManager = new PluginManager(this);
 
+    // create a new CLI instance
+    const cli = new CLI(this);
```
Comment (medikoo) [inline lib/Serverless.js]: Can't we just move ` this.cli = new this.classes.CLI(this);` from L59 here?

With this proposal two CLI instances are created in all cases.

File: lib/utils/getServerlessConfigFile.js [hunk 2]
```diff
@@ -19,12 +25,12 @@ const getServerlessConfigFilePath = (srvcPath) => {
...
-    if (exists.json) {
-      return jsonPath;
+    if (exists.yaml) {
+      return yamlPath;
     } else if (exists.yml) {
       return ymlPath;
-    } else if (exists.yaml) {
-      return yamlPath;
+    } else if (exists.json) {
+      return jsonPath;
```
Comment (medikoo) [inline lib/utils/getServerlessConfigFile.js]: It's technically a breaking change, (now `serverless.yml` will be favored over `sererless.json`, but I guess that can be assumed as a bug fix (?)

File: lib/utils/getServerlessConfigFile.js [hunk 3]
```diff
@@ -59,7 +65,6 @@ const getServerlessConfigFile = _.memoize(srvcPath => getServerlessConfigFilePat
     }
 
     return '';
-  })
-);
+  }), (configFileName, srvcPath) => srvcPath);
```
Comment (medikoo) [inline lib/utils/getServerlessConfigFile.js]: Is this ok that `configFileName` is ignored here? 

Due to that calling function mulitple times with same `srvcPath` but different `configFileName` arguments, will produce same results.

What case does this memoization addresses?

File: lib/utils/getServerlessConfigFile.test.js [hunk 4]
```diff
@@ -32,7 +32,7 @@ describe('#getServerlessConfigFile()', () => {
     const serverlessFilePath = path.join(tmpDirPath, 'serverless.yml');
 
     writeFileSync(serverlessFilePath, 'service: my-yml-service');
-    return expect(getServerlessConfigFile(tmpDirPath)).to.be.fulfilled.then((result) => {
+    return expect(getServerlessConfigFile(undefined, tmpDirPath)).to.be.fulfilled.then((result) => {
```
Comment (medikoo) [inline lib/utils/getServerlessConfigFile.test.js]: Nit: Literally I think it's cleaner to use `null` for no value (intentional) input instead of `undefined`

File: package-lock.json [hunk 5]
```diff
@@ -3602,15 +3601,13 @@
           "version": "1.0.0",
           "resolved": false,
           "integrity": "sha1-ibTRmasr7kneFk6gK4nORi1xt2c=",
-          "dev": true,
-          "optional": true
+          "dev": true
```
Comment (medikoo) [inline package-lock.json]: I think those changes are not desired.

It looks as if `package-lock.json` was regenerated by older version of npm

File: lib/Serverless.js (hunk 1 above)
Comment (dschep) [reply lib/Serverless.js]: yeah, i wasn't sure what to do about that. it's created later to allow customization, but i need to parse the config option here in order to load the config file.  Does anything use the CLI customization option?

File: lib/utils/getServerlessConfigFile.js (hunk 2 above)
Comment (dschep) [reply lib/utils/getServerlessConfigFile.js]: yeah, I this a bugfix since there were internal inconsistencies in priority

File: lib/utils/getServerlessConfigFile.js (hunk 3 above)
Comment (dschep) [reply lib/utils/getServerlessConfigFile.js]: right. good point. The memoization is just to avoid loading the file more than once in cases of... probably badly engineered code 😬 

i'll fix the key specification.

File: lib/utils/getServerlessConfigFile.test.js (hunk 4 above)
Comment (dschep) [reply lib/utils/getServerlessConfigFile.test.js]: i used `undefined` because IIRC thats what `...options.config` will be if the user doesn't specify `--config`, so this is closer to how `getServerlessConfigFile` will actually be called.

File: lib/Serverless.js (hunk 1 above)
Comment (medikoo) [reply lib/Serverless.js]: > It's created later to allow customization

Why creating it here (earlier) will prevent customization? As I see we're in a context of instance, so it should have same effect (?)

File: lib/utils/getServerlessConfigFile.test.js (hunk 4 above)
Comment (medikoo) [reply lib/utils/getServerlessConfigFile.test.js]: Technically there's no (and there should be no) difference in how `null` and `undefined` are handled. Fact that this function may receive `null` in some cases and `undefined` in others is perfectly fine.

It's just that semantically when inputting a _no value_ explicitly `null` seems a more clean choice. It's intentional _no value_, while `undefined` feels more accidental, e.g. it's the outcome of accessing a potentially defined property.

I personally try to not use `undefined` in literal form, also in older versions of a language it had implications as it wasn't a keyword, just a global variable easy to override.

So having `null` here, just feels better imo (but it was just a comment :)

File: lib/Serverless.js (hunk 1 above)
Comment (pmuens) [reply lib/Serverless.js]: Note sure if I'm following 🤔 What customization are we talking about here? The [inline-if](https://github.com/serverless/serverless/pull/6216/files#diff-55402a088565d14960a8e9e477f962bbR156) for `commandObject`?

File: lib/utils/getServerlessConfigFile.test.js (hunk 4 above)
Comment (pmuens) [reply lib/utils/getServerlessConfigFile.test.js]: I once read that `undefined` is what's computed / "picked" by Node.js / JavaScript and "humans" should always use `null`, never `undefined` (if that writeup makes sense).

That's the rule I'm always trying to follow following. Not sure if it's legit.

File: package-lock.json (hunk 5 above)
Comment (pmuens) [reply package-lock.json]: I hate these changes so much.

Maybe it was me. In every project we've been using a `package-lock.json` file we've changed that thing back- and force. Everyone produced a different file. EVERY. SINGLE. TIME.

File: lib/utils/getServerlessConfigFile.js [hunk 6]
```diff
@@ -6,8 +6,14 @@ const path = require('path');
 const fileExists = require('./fs/fileExists');
 const readFile = require('./fs/readFile');
 
-const getServerlessConfigFilePath = (srvcPath) => {
+const getServerlessConfigFilePath = (configFileName, srvcPath) => {
```
Comment (pmuens) [inline lib/utils/getServerlessConfigFile.js]: I see why we're implementing it that way here, but isn't there any way to move the logic to make the distinction between `options.config` and `config.servicePath` into another layer?

This change means that you always need to have the `options` and the `servicePath` available to pass it down the function. Would be nice to just give it the path to the config file and this function figures out what to do.

File: package-lock.json (hunk 5 above)
Comment (medikoo) [reply package-lock.json]: Remind me again why we actually version `package-lock.json`?
- It doesn't serve local development (IIRC we tend to have different setups, and there's no agreement we should follow `package-lock.json`)
- It doesn't serve global installation (npm ignores that)

What does it serve?

File: lib/Serverless.js (hunk 1 above)
Comment (dschep) [reply lib/Serverless.js]: As i said, i have no clue what uses this ability, but it's tested for like this: https://github.com/serverless/serverless/blob/master/lib/Serverless.test.js#L140-L148

File: lib/utils/getServerlessConfigFile.js (hunk 6 above)
Comment (dschep) [reply lib/utils/getServerlessConfigFile.js]: you mean implement process.argv parsing in this function? I .. don't like that :/

Comment (pmuens) [reply lib/utils/getServerlessConfigFile.js]: No, I mean consolidating that into just one parameter, rather than having 2 parameters (right now we pass in parts of the `options` and the `servicePath`).

File: package-lock.json (hunk 5 above)
Comment (pmuens) [reply package-lock.json]: Yes, true. I guess we just version this because `npm` says so when it generates it. But yes, it really serves no purpose right now.

Comment (medikoo) [reply package-lock.json]: Ok, I'll probably propose a PR that removes it then.

File: lib/Serverless.js (hunk 1 above)
Comment (pmuens) [reply lib/Serverless.js]: I have little idea either. Blaming brings up this PR --> https://github.com/serverless/serverless/pull/4160

Comment (medikoo) [reply lib/Serverless.js]: I looked into that, and it appears that our moves are limited (as we don't want to break some eventual user customizations.)

Ideal solution (imo), would be to move out CLI args parsing to `bin/serverless` and do not keep it internally, so Serverless class directly receives (already parsed out) `commands` and `options` (it'll also make a most friendly programmatical interface).

Still that change will be breaking, so I would leave it as TODO, for some near breaking release (once we sort out our versioning).

And now, I think cleaner would be, to not initialize here whole `CLI` class, but just do `minimist(process.argv.slice(2))` and seclude out of that eventual config setting (I would also add TODO comment, that signal that we will rework our commands args parsing)

Additionally I would validate existence of  `process.join(process.cwd(),customConfig)`,
With what's proposed now, we fallback to `serverless.yml` if custom config doesn't exist, but that I think can turn quite confusing (e.g. user may make typo in name, and be puzzled why original config is loaded)

Comment (dschep) [reply lib/Serverless.js]: Agreed that I don't want to introduce breaking cahnges. 

> And now, I think cleaner would be, to not initialize here whole CLI class, but just do minimist(process.argv.slice(2)) and seclude out of that eventual config setting (I would also add TODO comment, that signal that we will rework our commands args parsing)

that makes sense. i'll do the simple parsing here

> Additionally I would validate existence of process.join(process.cwd(),customConfig),
With what's proposed now, we fallback to serverless.yml if custom config doesn't exist, but that I think can turn quite confusing (e.g. user may make typo in name, and be puzzled why original config is loaded)

Good point. It actually doesn't fallback, but it breaks in a confusing way, so i'll make that error better.

File: lib/utils/getServerlessConfigFile.js (hunk 6 above)
Comment (dschep) [reply lib/utils/getServerlessConfigFile.js]: Done. It just accepts `this.serverless` from things using it.

File: lib/classes/Service.js [hunk 7]
```diff
@@ -46,73 +47,36 @@ class Service {
...
-        that.loadServiceFileParam(serviceFilename, serverlessFileParam)
-      );
+    return BbPromise.all([
+      serverlessConfigFileUtils.getServerlessConfigFilePath(this.serverless),
+      serverlessConfigFileUtils.getServerlessConfigFile(this.serverless),
+    ]).then(that.loadServiceFileParam.bind(that));
   }
 
-  loadServiceFileParam(serviceFilename, serverlessFileParam) {
+  loadServiceFileParam([serviceFilename, serverlessFileParam]) {
```
Comment (medikoo) [inline lib/classes/Service.js]: It'll be nicer to leave original signature (seems more natural), in above `then` it can be constructed as:

```javascript
args => this.loadServiceFileParam(...args)
```

_(I would also minimize internal API changes, to avoid risk of breaking some adventurous user plugins)_

File: lib/classes/Service.js [hunk 8]
```diff
@@ -46,73 +47,36 @@ class Service {
...
     const that = this;
 
+    that.serviceFilename = serviceFilename.split(path.sep).pop();
```
Comment (medikoo) [inline lib/classes/Service.js]: We may rely on Node.js native [`path.basename`](https://nodejs.org/api/path.html#path_path_basename_path_ext)
