### PR TITLE
Fix duplicate packaging issue

### LINKED ISSUE #5748: Upload size of AWS go lambda's doubles with 1.36.xx
# This is a Bug Report
I have noticed that the size of the zip files created by Serverless to upload Golang lambdas to AWS have doubled in size with the update of Serverless from 1.34.xx to 1.36.xxx, any reason for this or is it a bug?

## Description

* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by alexdebrie**
## What did you implement:

Closes #5748 

Basically, if your `include` items have `./` before them, it would grab the same file twice

```
package:
 exclude:
   - ./**
 include:
   - ./bin/**
```

This would grab `./bin/file` as well as `bin/file`.

## How did you implement it:

As a fix, I'm stripping the `./` from the start of the pattern before adding the include patterns to globby.

## How can we verify it:

Using the `aws-go` template, have a serverless.yml with the following:

```yml
service: golang-package # NOTE: update this with your service name

provider:
  name: aws
  runtime: go1.x
package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
```

Run `sls package` with the current Framework, and your zipfile in `.serverless/golang-package.zip` should have a duplicated file.

Checkout this branch and run `sls package` again. It should have just one file.

## Todos:

- [x] Write tests
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/plugins/package/lib/packageService.js [hunk 1]
```diff
@@ -225,10 +225,16 @@ module.exports = {
     params.include.forEach((pattern) => {
       patterns.push(pattern);
     });
+
+    // This strips "./" from the beginning of an includes pattern to avoid
+    // duplication of paths. See https://github.com/serverless/serverless/issues/5748
+    const strippedIncludes = params.include.map((pattern) => {
```
Comment (medikoo) [inline lib/plugins/package/lib/packageService.js]: I think relying on [`path.normalize`](https://nodejs.org/api/path.html#path_path_normalize_path) would be more reliable (it'll also pick other weird duplication cases):

```javascript
const { normalize } = require('path')

normalize('./bin'); // 'bin'
normalize('bin'); // 'bin'
normalize('./foo/../bin'); // 'bin'
```

**Comment by pmuens** [comment]
@medikoo I just updated the PR and moved the code to detect duplicates to the zipping of the whole service package.

**Comment by alexdebrie** [comment]
Awesome! Thank you @medikoo for the review and thanks @pmuens for fixing!

**Comment by pmuens** [comment]
> Awesome! Thank you @medikoo for the review and thanks @pmuens for fixing!
Sure thing 😊

Thanks for the review @medikoo :+1:
