### PR TITLE
Fix/cors omit access control allow credentials on false

### LINKED ISSUE #6994: CORS - allowCredentials: false - does not omit response headers Access-Control-Allow-Credentials
# Bug Report

### What did you do?

Setting up a resource with CORS and set `allowCredentials: false` e.g.

```yaml
# ...

functions:
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          path: product/{id}
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

# ...
```

### What happened?

The response headers of a CORS preflight contained the `access-control-allow-credentials`-header. 

```
access-control-allow-credentials: false
```

### What should've happened?

According to the specifications, the only valid value for this header is `'true'` and should be omitted when false.

> The only valid value for this header is true (case-sensitive). If you don't need credentials, omit this header entirely (rather than setting its value to false).

source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials

> Access-Control-Allow-Credentials = %s"true" ; case-sensitive

source: https://fetch.spec.whatwg.org/#http-new-header-syntax

### What's the content of your `serverless.yml` file?

(excerpts)

```yaml
functions:
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          path: product/{id}
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
```

or:

```yaml
functions:
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          path: product/{id}
          method: get
          cors: true
```

### What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

(let me know if this is relevant :-) )

### Similar or dependent issues:

- not found

---

### Further information:

I've preparing this issue as wished in the [contribution guidelines](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#when-you-propose-a-new-feature-or-bug-fix)  before submitting a PR. 

If you agree on this bug/improvement the code is ready to be submitted as PR (https://github.com/wildhaber/serverless/tree/fix/cors-omit-access-control-alow-credentials-on-false)

The required change is tiny:

```javascript
// lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
      const preflightHeaders = {
        'Access-Control-Allow-Origin': `'${origin}'`,
        'Access-Control-Allow-Headers': `'${config.headers.join(',')}'`,
        'Access-Control-Allow-Methods': `'${config.methods.join(',')}'`,
      };

      // Only set Access-Control-Allow-Credentials when explicitly allowed (omit if false)
      if(config.allowCredentials === true) {
        preflightHeaders['Access-Control-Allow-Credentials'] = `'${config.allowCredentials}'`;
      }
```
[see diff](https://github.com/serverless/serverless/compare/master...wildhaber:fix/cors-omit-access-control-alow-credentials-on-false#diff-872f8cac897abe18c7e8d00884f15926L33-R39)

(+ [Tests](https://github.com/serverless/serverless/compare/master...wildhaber:fix/cors-omit-access-control-alow-credentials-on-false#diff-047d4bdcd95d2284771376374067d708) / + [Docs](https://github.com/serverless/serverless/compare/master...wildhaber:fix/cors-omit-access-control-alow-credentials-on-false#diff-871929e390d61a5d2a3b505ac9b4bf24R287))

### PR DESCRIPTION
**Pull request by wildhaber**
## What did you implement

Only return `Access-Control-Allow-Credentials`-Header when `allowCredentials` is explicitly set to true. Otherwise the header is omitted as described in the specifications. 

Closes #6994 

## How can we verify it

(taken from the examples)

```yaml
service: aws-java-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: build/distributions/aws-java-simple-http-endpoint.zip

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - http:
          path: ping
          method: get
          cors: true
```

```yaml
service: aws-java-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: build/distributions/aws-java-simple-http-endpoint.zip

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - http:
          path: ping
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
```

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test-ci` --> Run all validation checks on proposed changes
- `npm run lint-updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check-updated` --> Check if updated files adhere to Prettier config
- `npm run prettify-updated` --> Prettify all the updated files

</details>

- [x] Write and run all tests
- [x] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

File: lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js [hunk 1]
```diff
@@ -30,9 +30,13 @@ module.exports = {
         'Access-Control-Allow-Origin': `'${origin}'`,
         'Access-Control-Allow-Headers': `'${config.headers.join(',')}'`,
         'Access-Control-Allow-Methods': `'${config.methods.join(',')}'`,
-        'Access-Control-Allow-Credentials': `'${config.allowCredentials}'`,
       };
 
+      // Only set Access-Control-Allow-Credentials when explicitly allowed (omit if false)
+      if(config.allowCredentials === true) {
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js]: As in SLS `allowCredentials` is considered boolean, let's simply do `if(config.allowCredentials)` (checks as `if (value === true)` are not natural in JS.

File: lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js [hunk 2]
```diff
@@ -157,7 +157,7 @@ describe('#compileCors()', () => {
         awsCompileApigEvents.serverless.service.provider.compiledCloudFormationTemplate.Resources
           .ApiGatewayMethodUsersUpdateOptions.Properties.Integration.IntegrationResponses[0]
           .ResponseParameters['method.response.header.Access-Control-Allow-Credentials']
-      ).to.equal("'false'");
+      ).to.equal(undefined);
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js]: Let's change to `to.not.exist`

File: lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js (hunk 1 above)
Comment (wildhaber) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js]: Ok, I could not find the place where you ensure a boolean. But this is fine for me.

My intention was to avoid having any truthy value considered as allowCredentials - true. For example:

```
// serverless.yml
allowCredentials: 'false' // would be interpreted as truthy now
```

Comment (medikoo) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js]: `'false'` is non empty string, so by JS boolean rules is a truthy value, and should be treated like that.

Still if someone will explicitly put `false` (boolean), then it's falsy, and will result with not listing that property. That's what's expected.

File: lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js (hunk 2 above)
Comment (wildhaber) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js]: Or what about - `to.be.undefined`? (As recommended in the chai over `.to.not.exist`: @see https://www.chaijs.com/api/bdd/)

```
expect(1).to.equal(1); // Recommended
expect(1).to.exist; // Not recommended

expect(0).to.equal(0); // Recommended
expect(0).to.exist; // Not recommended
```

Add .not earlier in the chain to negate .exist.

```
expect(null).to.be.null; // Recommended
expect(null).to.not.exist; // Not recommended

expect(undefined).to.be.undefined; // Recommended
expect(undefined).to.not.exist; // Not recommended
```

File: lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js (hunk 1 above)
Comment (wildhaber) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js]: Updated 👍

File: lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js (hunk 2 above)
Comment (medikoo) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js]: I assumed that `.to.not.exists` checks whether property is defined, while it checks for `null` or `undefined` value, which indeed is not what the name advertises.

In that case, yes let's use `to.be.undefined`

Comment (wildhaber) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js]: Totally agree, the naming indicates a missing of a property. Change is on the way. Thanks for your review.

**Comment by wildhaber** [comment]
@medikoo all the requested changes are made. let me know if I can further support you :-)

**Comment by wildhaber** [comment]
Thanks for spotting the issue. I thought I ran `npm run lint` without any errors. 
Seems to be fixed now.
