### PR TITLE
Fix #6267

### LINKED ISSUE #6267: Cannot read property 'split' of undefined
# This is a Bug Report

## Description

* What went wrong? `Cannot read property 'split' of undefined` with certain uncaught exceptions.
* What did you expect should have happened? Just see the `errorMessage`, `errorType`, and `stackTrace`.
* What was the config you used? Irrelevant.
* What stacktrace or error message from your provider did you see? `Cannot read property 'split' of undefined`

## Additional Data

* ***Serverless Framework Version you're using***: 1.45.1
* ***Operating System***: Mac OS X 10.14.5
* ***Stack Trace***: None.
* ***Provider Error messages***:

The issue is that I am using the `ajv` library to validate JSON. It throws an error, and because this error does not have a `stack`. It crashes here at `.../node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:551:33` because `err.stack` is `undefined`, but Serverless tries to `split()` `err.stack`. Even the TypeScript definition shows that `err.stack` can be undefined.

### PR DESCRIPTION
**Pull request by JonathanWilbur**
## What did you implement:

Closes #6267 

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/plugins/aws/invokeLocal/index.js [hunk 1]
```diff
@@ -548,7 +548,7 @@ class AwsInvokeLocal {
         errorResult = {
           errorMessage: err.message,
           errorType: err.constructor.name,
-          stackTrace: err.stack.split('\n'),
+          stackTrace: err.stack ? err.stack.split('\n') : [],
```
Comment (medikoo) [inline lib/plugins/aws/invokeLocal/index.js]: I guess it'll be more to the point to do `err.stack && err.stack.split('\n')`.

(If there's no _stack_ I would reference it with `undefined` or `null`, not an empty array, which logically suggests there is a stack but is empty)

**Comment by JonathanWilbur** [comment]
Requested changes made.
