### PR TITLE
fix(AWS API Gateway): Ensure `shouldStartNameWithService` support

### LINKED ISSUE #8720: serverless deploy error: In given setup stage specific options such as `tracing`, `logs` and `tags` are not supported.
`serverless.yml`

```yaml
service: my-api

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: development
    MY_AWS_ACCESS_KEY: ${param:MY_AWS_ACCESS_KEY}
    MY_AWS_SECRET_ACCESS_KEY: ${param:MY_AWS_SECRET_ACCESS_KEY}
    JWT_SECRET: ${param:JWT_SECRET}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'
  apiGateway:
    shouldStartNameWithService: true
    description: my-api
  lambdaHashingVersion: 20201221
  timeout: 30

functions:
  main:
    handler: src/main/handler.main
    events:
      - http:
          path: /
          method: get
          cors: true

  otherFunc:
    ...

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-split-stacks
```

I have this error:

```

 Serverless Error ---------------------------------------
 
  Rest API id could not be resolved.
  This might be caused by a custom API Gateway configuration.
  
  In given setup stage specific options such as `tracing`, `logs` and `tags` are not supported.
  
  Please update your configuration (or open up an issue if you feel that there's a way to support your setup).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.20.0
     Framework Version:         2.17.0 (local)
     Plugin Version:            4.4.1
     SDK Version:               2.3.2
     Components Version:        3.4.3
```

Anyone know how to fix this?
As deploy to sls dashboard now become red icon.
Any input is welcome...thanks

### PR DESCRIPTION
**Pull request by vicary**
The closing of #8720 was a workaround by supplying an optional option `apiName`.

In a perfect world it should correctly deploy with the recommended `provider.apiGateway.shouldStartNameWithService` without having to provide a custom `apiName`. But the workaround in the issue make it a required option, otherwise the script exits with code 1, and my CI environment is not happy about it.

This PR is a continuation of the discussion I started after the closing of the issue.

For more context please see https://github.com/serverless/serverless/issues/8720#issuecomment-955037755

### CODE REVIEW

File: lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js [hunk 1]
```diff
@@ -150,7 +150,9 @@ async function resolveRestApiId() {
     }
     const apiName = apiGatewayResource
       ? apiGatewayResource.Properties.Name
-      : provider.apiName || `${this.options.stage}-${this.state.service.service}`;
+      : provider.apiName || (provider.apiGateway && provider.apiGateway.shouldStartNameWithService)
+        ? `${this.state.service.service}-${this.options.stage}`
```
Comment (pgrzesik) [inline lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js:154]: Instead of duplicating the logic, we should rather reuse the `naming.getApiGatewayName` utility - the reason for this bug is that it was not used previously I believe.

**Review by pgrzesik — CHANGES_REQUESTED** [review]
Thanks for contribution @vicary, good catch :+1: I have one suggestion for the implementation that should help avoiding such bugs in the future. Additionally, it would be great to cover this scenario with a test case based on `runServerless` utility.

**Comment by vicary** [comment]
@pgrzesik Thanks for the review. Sorry for not super familiar with the internal API yet, using `naming.getApiGatewayName()` now.

I'll try writing a test with `runServerless` this week.

**Comment by pgrzesik** [comment]
Perfect @vicary - let me know if you have any questions :100:

**Comment by vicary** [comment]
@pgrzesik I think I need some help, so when calling `runServerless({...})` it throws `ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.`.

Assuming unit tests should have a way to mock the credentials, how do I do that?

**Comment by vicary** [comment]
@pgrzesik It was quite a trip to stub all the way down to `after:deploy:deploy`, I've learn a lot more about the inner workings nonetheless. Not sure if there is a quicker way though.

File: test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js [hunk 2]
```diff
@@ -809,4 +809,66 @@ describe('test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/u
     expect(untagResourceStub).to.have.been.calledOnce;
     expect(untagResourceStub.args[0][0].tagKeys).to.deep.equal(['keytoremove']);
   });
+
+  it('should deploys shouldStartNameWithService without apiName', async () => {
```
Comment (pgrzesik) [inline test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js:813]: I only have one minor comment - in general, it's better to not override service for tests, as it's automatically generated - I see that here we need service for assertion so we can go this route instead:

```
const { serviceConfig, servicePath: serviceDir, updateConfig } = await fixtures.setup('apiGateway');
// Here we can get service from serviceConfig
await updateConfig(); // Here we can pass config ext content
await runServerless({cwd: serviceDir, ...}) // change fixture to cwd 
```

**Review by pgrzesik — CHANGES_REQUESTED** [review]
Looks awesome, I have only one minor suggestion and we should be good to go - well done with mocking all these AWS API calls - this one was definitely very tricky case

File: test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js (hunk 2 above)
Comment (vicary) [reply test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js:813]: Should I also replace my `const service = "...";` with `serviceConfig.service`?

Comment (pgrzesik) [reply test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js:813]: yes, I don't remember exactly if under `service` there will be name or an object so you might need to check if `serviceConfig.service.name` won't be needed there

Comment (vicary) [reply test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js:814]: It's a plain string, I've update the test.

File: lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js [hunk 3]
```diff
@@ -150,7 +150,7 @@ async function resolveRestApiId() {
     }
     const apiName = apiGatewayResource
       ? apiGatewayResource.Properties.Name
-      : provider.apiName || `${this.options.stage}-${this.state.service.service}`;
+      : provider.apiName || provider.naming.getApiGatewayName();
```
[the remark this answers is not in the document]
Comment (vicary) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js]: done

**Review by pgrzesik — APPROVED** [review]
Thank you @vicary, looks great :+1:

**Comment by SrushithR** [comment]
Hi @vicary @pgrzesik. Since the latest release (`2.66.0`), our deployments with serverless pro have started failing. The same stack without the serverless pro details deploys without any issues.

For now, I have downgraded the serverless package version to `2.65.0` and the deployments are working fine. Can you please help me with this?

**Comment by pgrzesik** [comment]
Hello @SrushithR - could you please provide more details on how your deployments are failing?

**Comment by vicary** [comment]
If this is reproducible and confirmed related, I'll make a regression test.

**Comment by pgrzesik** [comment]
I think I've found the issue with the change - I'll prepare a PR with the fix and release shortly after it's accepted

**Comment by SrushithR** [comment]
@pgrzesik I have created an issue regarding the same - https://github.com/serverless/serverless/issues/10220
