### PR TITLE
Limited Lambda Permission for Events

### LINKED ISSUE #2023: Limit Lambda Permissions to created event source
# This is a Feature Proposal
## Description

When we create a LambdaPermission for sources to call a function (e.g. for S3 or SNS) we are not specific about which resource can call the function, but configure any resource of a specific service to be able to call the function (e.g. every S3 bucket or every SNS topic can call a LambdaFunction). This has to be limited so we only let specific resources call the lambda function by default.

This will not change behaviour in any way for the user, just tighten security.

Similar or dependent issues:
- #1895 
## Additional Data
- **_Serverless Framework Version you're using**_: latest master
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

### PR DESCRIPTION
**Pull request by eahefnawy**
## What did you implement:

Closes #2023 

## How did you implement it:
Added `SourceArn` property for each `Lambda::Permission` resource depending on the event. The logical IDs of the `Lambda::Permission` resources had to be changed to:

* SNS: HelloLambdaPermissionTopicSNS
* S3: HelloLambdaPermissionBucketS3
* APIG: HelloLambdaPermissionUsersCreatePostApiGateway

I've updated the docs with the new logical IDs

Notes:

* This doesn't apply to stream events because they use different permission model via IAM statements, not `Lambda::Permission`

## How can we verify it:

Using the following config:

```yml
service: myService

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get
      - s3: serverless-limit-permissions-bucket
      - schedule: rate(10 minutes)
      - sns: serverless-limit-permissions-topic
```
Deploy and make sure your function is triggered successfully based on the event source. You can also check the SourceArn in the CF template with `--noDeploy`

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by pmuens** [comment]
Just tested the PR manually with the setup / `serverless.yml` you provided and it succeeded.

However it fails if I run the `complex-integration-test` suite. The first time I ran it it only errored for `http` events. I ran it again (only the API Gateway tests) and the following is what I got.

**Note:** This first test errored differently than the second one. So the errors are non-deterministic.

It would be great if @eahefnawy, @flomotlik and @nikgraf could test it thoroughly as well (by running `npm run complex-integraiton-test`.

bildschirmfoto 2016-11-17 um 15 05 52

File: lib/plugins/aws/deploy/compile/events/apiGateway/tests/permissions.js [hunk 1]
```diff
@@ -18,25 +18,27 @@ describe('#awsCompilePermissions()', () => {
     awsCompileApigEvents.validated = {};
   });
 
-  it('should create permission resource when http events are given', () => {
+  it('should create limited permission resource scope to REST API', () => {
```
Comment (pmuens) [inline lib/plugins/aws/deploy/compile/events/apiGateway/tests/permissions.js]: `scoped`

**Comment by pmuens** [comment]
@eahefnawy thanks for the update 🙌 

Looks good from a code perspective.

Unfortunately the `complex-integration-test` suite broke the first time.
The second time (running only the API Gateway tests) it failed again.

Seems like the endpoint was not in place when the tests tried to access it.

1st test run (the API Keys tests can be ignored obviously):

```
  44 passing (53m)
  17 failing

  1) AWS - API Gateway (Integration: Lambda): CORS test should setup CORS support with simple string config:
     FetchError: request to https://029lwprjii.execute-api.us-east-1.amazonaws.com/dev/simple-cors failed, reason: getaddrinfo ENOTFOUND 029lwprjii.execute-api.us-east-1.amazonaws.com 029lwprjii.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  2) AWS - API Gateway (Integration: Lambda): CORS test should setup CORS support with complex object config:
     FetchError: request to https://029lwprjii.execute-api.us-east-1.amazonaws.com/dev/complex-cors failed, reason: getaddrinfo ENOTFOUND 029lwprjii.execute-api.us-east-1.amazonaws.com 029lwprjii.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  3) AWS - API Gateway (Integration: Lambda): API keys test should reject a request with an invalid API Key:
     FetchError: request to https://fmmtpvoqzi.execute-api.us-east-1.amazonaws.com/dev/hello failed, reason: getaddrinfo ENOTFOUND fmmtpvoqzi.execute-api.us-east-1.amazonaws.com fmmtpvoqzi.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  4) AWS - API Gateway (Integration: Lambda): API keys test should succeed if correct API key is given:
     FetchError: request to https://fmmtpvoqzi.execute-api.us-east-1.amazonaws.com/dev/hello failed, reason: getaddrinfo ENOTFOUND fmmtpvoqzi.execute-api.us-east-1.amazonaws.com fmmtpvoqzi.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  5) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "without-slash" path setup should expose an accessible POST HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev/without-slash failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  6) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "without-slash" path setup should expose an accessible GET HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev/without-slash failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  7) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "without-slash" path setup should expose an accessible PUT HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev/without-slash failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  8) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "without-slash" path setup should expose an accessible DELETE HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev/without-slash failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  9) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/with-slash" path setup should expose an accessible POST HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev/with-slash failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  10) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/with-slash" path setup should expose an accessible GET HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev/with-slash failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  11) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/with-slash" path setup should expose an accessible PUT HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev/with-slash failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  12) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/with-slash" path setup should expose an accessible DELETE HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev/with-slash failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  13) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/" path setup should expose an accessible POST HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  14) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/" path setup should expose an accessible GET HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  15) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/" path setup should expose an accessible PUT HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  16) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/" path setup should expose an accessible DELETE HTTP endpoint:
     FetchError: request to https://pif8b3sqzk.execute-api.us-east-1.amazonaws.com/dev failed, reason: getaddrinfo ENOTFOUND pif8b3sqzk.execute-api.us-east-1.amazonaws.com pif8b3sqzk.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  17) AWS - API Gateway (Integration: Lambda Proxy): API keys test should succeed if correct API key is given:

      AssertionError: expected 'Forbidden' to equal 'Hello from API Gateway!'
      + expected - actual

      -Forbidden
      +Hello from API Gateway!
      
      at fetch.then.then (tests/integration/aws/api-gateway/integration-lambda-proxy/api-keys/tests.js:76:33)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)

```

2nd test run

```
  26 passing (17m)
  14 failing

  1) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "without-slash" path setup should expose an accessible POST HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev/without-slash failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  2) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "without-slash" path setup should expose an accessible GET HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev/without-slash failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  3) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "without-slash" path setup should expose an accessible PUT HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev/without-slash failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  4) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "without-slash" path setup should expose an accessible DELETE HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev/without-slash failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  5) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/with-slash" path setup should expose an accessible POST HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev/with-slash failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  6) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/with-slash" path setup should expose an accessible GET HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev/with-slash failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  7) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/with-slash" path setup should expose an accessible PUT HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev/with-slash failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  8) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/with-slash" path setup should expose an accessible DELETE HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev/with-slash failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  9) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/" path setup should expose an accessible POST HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  10) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/" path setup should expose an accessible GET HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  11) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/" path setup should expose an accessible PUT HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  12) AWS - API Gateway (Integration: Lambda Proxy): Simple API test when having a "/" path setup should expose an accessible DELETE HTTP endpoint:
     FetchError: request to https://ydauwhntig.execute-api.us-east-1.amazonaws.com/dev failed, reason: getaddrinfo ENOTFOUND ydauwhntig.execute-api.us-east-1.amazonaws.com ydauwhntig.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  13) AWS - API Gateway (Integration: Lambda Proxy): CORS test should setup CORS support with simple string config:
     FetchError: request to https://84i6q8f008.execute-api.us-east-1.amazonaws.com/dev/simple-cors failed, reason: getaddrinfo ENOTFOUND 84i6q8f008.execute-api.us-east-1.amazonaws.com 84i6q8f008.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  14) AWS - API Gateway (Integration: Lambda Proxy): CORS test should setup CORS support with complex object config:
     FetchError: request to https://84i6q8f008.execute-api.us-east-1.amazonaws.com/dev/complex-cors failed, reason: getaddrinfo ENOTFOUND 84i6q8f008.execute-api.us-east-1.amazonaws.com 84i6q8f008.execute-api.us-east-1.amazonaws.com:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at TLSSocket.socketErrorListener (_http_client.js:308:9)
      at connectErrorNT (net.js:1015:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by pmuens** [comment]
Tested it once again. Still get the same error :-(

`FetchError: request to https://swpd4tgz1f.execute-api.us-east-1.amazonaws.com/dev/hello failed, reason: getaddrinfo ENOTFOUND swpd4tgz1f.execute-api.us-east-1.amazonaws.com swpd4tgz1f.execute-api.us-east-1.amazonaws.com:443
`

**Comment by pmuens** [comment]
Just ran the API Gateway integration test suite twice again.
Everything succeeded. Seems like there was something wrong on AWS end.

Did another code review and it looks great!

There's just one comment about a tiny typo. Other than that it's GTM from my side :shipit:
