### PR TITLE
Cross region SNS Trigger

### LINKED ISSUE #3676: Cross region SNS trigger
# This is a (Bug Report)

## Description

When trying to deploy a lambda with an SNS trigger in a different region the cloudformation script fails.

* What went wrong?

Cloudformation fails to create SNS event subscription for lambda with error:

`invalid parameter: TopicArn`

* What did you expect should have happened?

Expected the lambda to deploy (via cloudformation) with a trigger on an SNS topic in a different region.

* What was the config you used?

```
service: testservice
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-1

functions:
  hello:
    handler: handler.run
    events: 
      - sns: arn:aws:sns:eu-west-1:xxxxxxxxxxx:stresstest
```

* What stacktrace or error message from your provider did you see?
```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (2.41 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - stresser-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - HelloLambdaPermissionStresstestSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloLambdaVersionOVTh8yMAX1zsFvyQcL4UekM3pyWBiYTwE71y8M
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - HelloLambdaPermissionStresstestSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Subscription - HelloSnsSubscriptionStresstest
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloLambdaVersionOVTh8yMAX1zsFvyQcL4UekM3pyWBiYTwE71y8M
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - HelloLambdaVersionOVTh8yMAX1zsFvyQcL4UekM3pyWBiYTwE71y8M
CloudFormation - CREATE_FAILED - AWS::SNS::Subscription - HelloSnsSubscriptionStresstest
CloudFormation - CREATE_FAILED - AWS::Lambda::Permission - HelloLambdaPermissionStresstestSNS
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - stresser-dev
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - stresser-dev
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Permission - HelloLambdaPermissionStresstestSNS
CloudFormation - DELETE_COMPLETE - AWS::SNS::Subscription - HelloSnsSubscriptionStresstest
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - HelloLambdaVersionOVTh8yMAX1zsFvyQcL4UekM3pyWBiYTwE71y8M
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Permission - HelloLambdaPermissionStresstestSNS
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - stresser-dev
```

Similar or dependent issues:
* #2183

## Additional Data

```
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.10.0
     Serverless Version: 1.14.0
```

### PR DESCRIPTION
**Pull request by herebebogans**
## What did you implement:

Closes #3676

Allow cross region SNS trigger when an arn is provided in a different region

## How did you implement it:

Check if region is different in SNS event compiler.

## How can we verify it:

Tests updated.

## Todos:

_**Note: Run `npm run test-ci` to run all validation checks on proposed changes**_

- [X] Write tests and confirm existing functionality is not broken.  
       **Validate via `npm test`**
- [X] Write documentation
- [X] Ensure there are no lint errors.  
       **Validate via `npm run lint-updated`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [X] Ensure introduced changes match Prettier formatting.  
       **Validate via `npm run prettier-check-updated`**  
       _Note: All reported issues can be automatically fixed by running `npm run prettify-updated`_
- [X] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

File: lib/plugins/aws/package/compile/events/sns/index.js [hunk 1]
```diff
@@ -64,6 +64,9 @@ class AwsCompileSNSEvents {
                   if (topicArn.indexOf('arn:') === 0) {
                     const splitArn = topicArn.split(':');
                     topicName = splitArn[splitArn.length - 1];
+                    if (this.provider.options && splitArn[3] !== this.provider.options.region) {
```
Comment (pmuens) [inline lib/plugins/aws/package/compile/events/sns/index.js]: I'd propose to use `this.options.region`. This just requires to pass in the `options` as a second argument in the constructor and then set `this.options = options` in the constructor.

This is still "ugly" (due to the way the Framework deals with regions) but it's more robust compared to `this.provider`. We use this pattern (using `this.options.region`) in other plugins as well.

**Comment by herebebogans** [comment]
thanks @pmuens. Updated with feedback

**Comment by herebebogans** [comment]
@pmeuns.

A snippet from  serverless.yml for the functionality.

```
...
provider:
  name: aws
  region: ap-southeast-2
...
functions:
  myFunction:
    handler: src/myfunction.handler
    events:
      - sns:
          arn: 'arn:aws:sns:us-east-1:XXXXXXXXXXXX:my-topic'
```
A practical use case of this would be a lambda function subscribing to an SES email receipt SNS action rule as SES is only available in some regions.

File: lib/plugins/aws/package/compile/events/sns/index.js [hunk 2]
```diff
@@ -64,6 +64,9 @@ class AwsCompileSNSEvents {
                   if (topicArn.indexOf('arn:') === 0) {
                     const splitArn = topicArn.split(':');
                     topicName = splitArn[splitArn.length - 1];
+                    if (splitArn[3] !== this.options.region) {
+                      region = splitArn[3];
```
Comment (bzemms) [inline lib/plugins/aws/package/compile/events/sns/index.js]: 🐛 Bug...

this line cuase issue when arn contain pseudo params:
e.g 
```
arn:aws:sns:${AWS::Region}:...
```

it will calculate region as `${AWS`

@Simon Elder  @herebebogans @pmeuns.

Comment (svdgraaf) [reply lib/plugins/aws/package/compile/events/sns/index.js]: https://github.com/svdgraaf/serverless-pseudo-parameters/issues/38

Yep, it breaks alright 😅 Not sure what the best cause of action is here. I think it's dirty to do a direct split like this. A pseudo parameter is a valid value for the Arn. Even just a `Ref` would be a valid, and that would break this too.

Perhaps check the found region with a set list of available regions from the aws-sdk? Or add a `region` parameter to set a specific region on the sns trigger?
