### PR TITLE
Do not print logs if print command is used.

### LINKED ISSUE #5676: 'sls print' contains Warnings.
# This is a Bug Report

## Description

* What went wrong?

It came to occur since 1.36.0.
Output of `sls print` contains Warnings.

The reproduction code is as follows.

My serverless.yml:
```yaml
service: servicename

provider:
  name: aws
  runtime: nodejs8.10

functions:
  function1:
    handler: lib/proxy.handler
  function2:
    handler: lib/proxy.handler
```

Yes, We have multiple functions having same handler.
The difference between the two functions is environment variables and so on.

shell script:
```bash
sls print
```

stdout:
```
Serverless: Warning: A handler "lib/proxy.handler" is duplicated in functions: function1, function2.
service: servicename
provider:
  name: aws
  runtime: nodejs8.10
functions:
  function1:
    handler: lib/proxy.handler
  function2:
    handler: lib/proxy.handler
```

* What did you expect should have happened?

`sls print` should output valid yaml.
Warnings should be written to stderr. Otherwise, `sls print` should not output warnings.

* What was the config you used?

As mentioned above.

* What stacktrace or error message from your provider did you see?

Similar or dependent issues:

Add warning for multiple functions having same handler: https://github.com/serverless/serverless/issues/4414 https://github.com/serverless/serverless/pull/5638

// I think that this warning itself is useful.

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.0
* ***Operating System***: darwin
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by exoego**
## What did you implement:

Closes #5676

## How did you implement it:

If `print` command is used, `CLI#log` become no-op.
Therefore logs are suppressed, except printing service definition.

Though duplicate-warnings are getting removed in #5733, 
I think this change is worth to prevent similar "unexpected log while print" issues in future.

## How can we verify it:

1. `npm install -g exoego/serverless#print-no-log`
2. Prepare the below yml.
```yml
service: 
  name: myservice
provider:
  name: aws
  runtime: nodejs8.10
functions:
  function1:
    handler: lib/proxy.handler
  function2:
    handler: lib/proxy.handler
```
3. `sls print`, it should only give yml, no warnings.

## Todos:

- [x] Write tests
- [x] <del>Write documentation</del> N/A
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/Serverless.js [hunk 1]
```diff
@@ -81,6 +81,7 @@ class Serverless {
     if (this.cli.displayHelp(this.processedInput)) {
       return BbPromise.resolve();
     }
+    this.cli.suppressLog(this.processedInput);
```
Comment (eahefnawy) [inline lib/Serverless.js]: could you just add a comment here that explains that logs would only be suppressed if the print command is entered? Just to make it clear that logs don't always get suppressed, since all commands will run this method.

or maybe call the method `suppressLogIfPrintCommand`? 😄

Comment (exoego) [reply lib/Serverless.js]: Renamed in https://github.com/serverless/serverless/pull/5728/commits/59c440e0737801eb37de63dc74e133be8bbb83f7

**Comment by uneco** [comment]
This issue has recurred in versions that use writeMessage.
https://github.com/serverless/serverless/blob/e1092aff44cc839896c63908f3803f874df63fe8/lib/classes/Error.js#L30-L45
