### PR TITLE
Make ALB event target group names unique

### LINKED ISSUE #6320: ALB event Target Group names are not unique across services
# This is a Bug Report

## Description

You cannot define function with alb event in different services using the same function name. If you try to do it, the second service deployment will fail saying the a Target Group with that name already exists.

To reproduce the bug, follow these steps:
- Deploy `test` service below. 
- Update `test2` service by replacing `<listenerArn>` with the `ListenerArn` output from `test` service deploy.
- Deploy `test2` service, which should fail.

```javascript
module.exports.hello = async () => ({
  isBase64Encoded: false,
  statusCode: 200,
  statusDescription: "200 OK",
  headers: { "Content-Type": "application/json" },
  body: "Hello from Lambda"
});
```

```yaml
service: test

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

package:
  excludeDevDependencies: false
  exclude:
  - '**/*'
  include:
  - ./hello.js

functions:
  hello:
    handler: hello.hello
    events:
    - alb:
        listenerArn: { Ref: HTTPListener }
        priority: 1
        conditions:
          path: /hello

custom:
  defaultRegion: us-east-1
  defaultStage: dev
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
  objectPrefix: '${self:service}-${self:custom.stage}'

resources:
  Outputs:
    LoadBalancerDNSName:
      Value: { 'Fn::GetAtt': [ LoadBalancer, 'DNSName' ] }
      Export: { Name: '${self:custom.objectPrefix}-LoadBalancerDNSName' }
    ListenerArn:
      Value: { 'Ref': HTTPListener }
  Resources:
    VPC:
      Type: 'AWS::EC2::VPC'
      Properties:
        CidrBlock: 172.31.0.0/16
        EnableDnsHostnames: true
    InternetGateway:
      Type: 'AWS::EC2::InternetGateway'
    VPCGatewayAttachment:
      Type: 'AWS::EC2::VPCGatewayAttachment'
      Properties:
        VpcId: { Ref: VPC }
        InternetGatewayId: { Ref: InternetGateway }
    RouteTable:
      Type: 'AWS::EC2::RouteTable'
      Properties:
        VpcId: { Ref: VPC }
    InternetRoute:
      Type: 'AWS::EC2::Route'
      DependsOn: VPCGatewayAttachment
      Properties:
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: { Ref: InternetGateway }
        RouteTableId: { Ref: RouteTable }
    SubnetA:
      Type: 'AWS::EC2::Subnet'
      Properties:
        AvailabilityZone: '${self:custom.region}a'
        CidrBlock: 172.31.0.0/20
        MapPublicIpOnLaunch: false
        VpcId: { Ref: VPC }
    SubnetB:
      Type: 'AWS::EC2::Subnet'
      Properties:
        AvailabilityZone: '${self:custom.region}b'
        CidrBlock: 172.31.16.0/20
        MapPublicIpOnLaunch: false
        VpcId: { Ref: VPC }
    SubnetARouteTableAssociation:
      Type: 'AWS::EC2::SubnetRouteTableAssociation'
      Properties:
        SubnetId: { Ref: SubnetA }
        RouteTableId: { Ref: RouteTable }
    SubnetBRouteTableAssociation:
      Type: 'AWS::EC2::SubnetRouteTableAssociation'
      Properties:
        SubnetId: { Ref: SubnetB }
        RouteTableId: { Ref: RouteTable }
    SecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupName: 'http-https'
        GroupDescription: 'HTTPS / HTTPS inbound; Nothing outbound'
        VpcId: { Ref: VPC }
        SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        -
          IpProtocol: -1
          FromPort: '1'
          ToPort: '1'
          CidrIp: 127.0.0.1/32
    LoadBalancer:
      Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
      Properties:
        Type: 'application'
        Name: '${self:custom.objectPrefix}'
        IpAddressType: 'ipv4'
        Scheme: 'internet-facing'
        LoadBalancerAttributes:
        - { Key: 'deletion_protection.enabled', Value: false }
        - { Key: 'routing.http2.enabled', Value: false }
        - { Key: 'access_logs.s3.enabled', Value: false }
        SecurityGroups:
        - { Ref: SecurityGroup }
        Subnets:
        - { Ref: SubnetA }
        - { Ref: SubnetB }
    HTTPListener:
      Type: 'AWS::ElasticLoadBalancingV2::Listener'
      Properties:
        LoadBalancerArn: { Ref: LoadBalancer }
        Port: 80
        Protocol: 'HTTP'
        DefaultActions:
        -
          Type: 'fixed-response'
          Order: 1
          FixedResponseConfig:
            StatusCode: 404
            ContentType: 'application/json'
            MessageBody: '{ "not": "found" }'
```

```yaml
service: test2

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

package:
  excludeDevDependencies: false
  exclude:
  - '**/*'
  include:
  - ./hello.js

functions:
  hello:
    handler: hello.hello
    events:
    - alb:
        listenerArn: <listenerArn>
        priority: 2
        conditions:
          path: /hello

custom:
  defaultRegion: us-east-1
  defaultStage: dev
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
``

## Additional Data

### PR DESCRIPTION
**Pull request by cbm-egoubely**
## What did you implement:

Closes #6320 

This is a fix proposal, might have to wait until a better solution is found.

Instead of using `<normalizedFunctionName>-<stage>` as a Target Group name, use a md5 hash of the combination of service name, function name and stage. It would ensure uniqueness across services.

Also, to make Target Groups searchable in the EC2 console, add a `Name` tag to the Target Group with value `<service name>-<function name>-<stage>`.

Important: Target Group names are limited to 32 chars, that's why I had to use a hash instead of using a readable name. This is not satisfying but I could not come up with a better solution, so if someone has a better one, that would be great ! I hope AWS will increase this limitation in the futur.  

## How did you implement it:

Added some functions in `lib/plugins/aws/lib/naming.test.js` using the `crypto` module.

Use these functions in `targetGroups.js`.

## How can we verify it:

See the instructions to reproduce the bug in #6320 

## Todos:

- [x] Write tests and confirm existing functionality is not broken.  
- [ ] Write documentation
- [x] Ensure there are no lint errors.  
- [x] Ensure introduced changes match Prettier formatting.  
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES  
**_Is it a breaking change?:_** NO

### CODE REVIEW

File: lib/plugins/aws/lib/naming.js [hunk 1]
```diff
@@ -381,6 +382,17 @@ module.exports = {
...
+  getAlbTargetGroupNameTagValue(functionName) {
+    return `${
+      this.provider.serverless.service.service
+    }-${functionName}-${this.provider.getStage()}`;
+  },
+  getAlbTargetGroupName(functionName) {
+    return crypto
+      .createHash('md5')
+      .update(this.getAlbTargetGroupNameTagValue(functionName))
+      .digest('hex');
```
Comment (medikoo) [inline lib/plugins/aws/lib/naming.js]: Why hashing is needed? Wouldn't adding service name be good enough?

Comment (pmuens) [reply lib/plugins/aws/lib/naming.js]: Good point. I think it's necessary because of the max length for the name.

Comment (medikoo) [reply lib/plugins/aws/lib/naming.js]: And do we know what's allowed max length? Is it e.g. different from function name on AWS side?
In unhashed form iirc this name equals final function name (which is also combination of _service_, _base function name_ and _stage_ tokens)

Comment (cbm-egoubely) [reply lib/plugins/aws/lib/naming.js]: Max length is 32 (see PR description) and name has to be unique per service/function/stage, I think it would be hard to have a non-hash name that fits, even with truncating.

Comment (medikoo) [reply lib/plugins/aws/lib/naming.js]: Indeed, not sure why I didn't read through _Important_ note in description.

LGTM
