### PR TITLE
Fix issue 2132 - Fail when incorrect format for additional IAM Role Statements causes them not to be included

### LINKED ISSUE #2132: Warn when incorrect format for additional IAM Role Statements causes them not to be included
# Bug Report
## Description

When using a `$ref` to include additional IAM Role Statements for a service, if the `$ref`'d file is not in the correct format (i.e. an array including more role statements), the role statements you are attempting to include are silently not included.

This may also happen when not using `$ref` and simply including incorrectly formatted statements in the `yml` directly.
- What went wrong?

Incorrectly formatted role statements were silently not included in the final composed CloudFormation template.
- What did you expect should have happened?

For the CLI to throw an error or warning that the role statements would not be included.
- What was the config you used?

Example `serverless.yml`

``` yml
service: myfancyservice
runtime: nodejs4.3
provider:
  name: aws
  iamRoleStatements:
    $ref: ./roleStatements.json
```

Example incorrect `roleStatements.json`:

``` json
{
  "IamPolicyLambdaInvocationAndDynamoDBStream": {
    "Type": "AWS::IAM::Policy",
    "Properties": {
      "PolicyName": "iam-policy-lambda-dynamo-${opt:stage}",
      "PolicyDocument": {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "lambda:InvokeFunction"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "dynamodb:*"
            ],
            "Resource": "*"
          }
        ]
      },
      "Roles": [
        {
          "Ref": "IamRoleLambda"
        }
      ]
    }
  }
}
```

Example correct `roleStatements.json`:

``` json
[
  {
    "Effect": "Allow",
    "Action": [
      "lambda:InvokeFunction"
    ],
    "Resource": "*"
  },
  {
    "Effect": "Allow",
    "Action": [
      "dynamodb:*"
    ],
    "Resource": "*"
  }
]
```
- What stacktrace or error message from your provider did you see?

None by default.

Issue presents itself when the lambda is executed. If you add an event mapping which depends on these policies then CloudFormation will throw an error when creating the stack, if you do not have that, it will not throw an error.
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.0-rc1
- **_Operating System**_: OS X 10.11.6
- **_Stack Trace**_: N/A
- **_Provider Error messages**_: none

### PR DESCRIPTION
**Pull request by imaman**
## What did you implement:

Closes #2132: Yell when incorrect format for additional IAM Role Statements causes them not to be included

## How did you implement it:

added a validateStatements() in lib/plugins/aws/deploy/lib/mergeIamTemplates.js

## How can we verify it:

```
$ cat > serverless.yml <<EOF
> service: wed-2253
> 
> provider:
>   name: aws
>   runtime: nodejs4.3
>   iamRoleStatements:
>     Version: "2012-10-17"
>     Statement:
>     - Effect: "Allow"
>       Action:
>         - "s3:ListBucket"
>       Resource: "*"
> 
> functions:
>   hello:
>     handler: handler.hello
> 
> EOF

$ sls deploy --noDeploy
 
  Serverless Error ---------------------------------------
 
     iamRoleStatements should be an array of objects, where
     each object has Effect, Action, Resource fields. Specifically,
     it is not an array
   ....

```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

File: lib/plugins/aws/deploy/lib/mergeIamTemplates.js [hunk 1]
```diff
@@ -123,24 +136,34 @@ module.exports = {
...
-          .Properties
-          .PolicyDocument
-          .Statement = this.serverless.service.provider.compiledCloudFormationTemplate
-          .Resources
-          .IamPolicyLambdaExecution
-          .Properties
-          .PolicyDocument
-          .Statement.concat(this.serverless.service.provider.iamRoleStatements);
+      if (this.serverless.service.provider.iamRoleStatements) {
+        const reason = checkStatements(this.serverless.service.provider.iamRoleStatements);
```
Comment (pmuens) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: Could you rename this from `reason` to `statementsValid` so that it's a little bit more expressive?

File: lib/plugins/aws/deploy/lib/mergeIamTemplates.js [hunk 2]
```diff
@@ -4,6 +4,19 @@ const _ = require('lodash');
 const BbPromise = require('bluebird');
 const path = require('path');
 
+function checkStatements(statements) {
```
Comment (pmuens) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: Any chance to move this into an exported function and run this before `mergeIamTemplates` (which should be renamed to e.g. `mergeTemplates` or `merge`) and then export a method called `mergeIamTemplates` which is used to run everything in order? (see here: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/cleanupS3Bucket.js#L53-L61)

The reason for that is that the single `mergeIamTemplates` method gets more and more complex and might introduce merge conflicts in the future.

Comment (imaman) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: done. totally agree with your motivation.

File: lib/plugins/aws/deploy/lib/mergeIamTemplates.js (hunk 1 above)
Comment (imaman) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: n/a given that now the checkStatements (which was renamed to validateStatemenets) throws the error itself (instead of returning an error message)

File: lib/plugins/aws/deploy/lib/mergeIamTemplates.js (hunk 2 above)
Comment (imaman) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: One more thing: I had a couple of commits which I forgot to "git pull" before you reviewed... 
so you're going to see the following changes (in addition to the changes you requested):

a/ checkStatements() was renamed to validateStatements() and it now either returns gracefully or throws an error (so that caller does not have to deal with checking the return value and throwing an error off of it)
b/ slight changes to the phrasing of the error message
c/ a few more unit tests

**Comment by imaman** [comment]
@pmuens a friendly ping :)

**Comment by eahefnawy** [comment]
@imaman thanks a lot for the effort you put into this and really sorry for the massive delay on review. We want to include this in the next release tomorrow, so to stay agile, I'm gonna resolve the conflicts into a new branch and merge. You've done great work here and your commits will stay in the codebase 🙌 

Thanks again 😊

**Comment by eahefnawy** [comment]
Done! Closing this one...

Thanks again @imaman 😊
