### PR TITLE
Fix provisioned concurrency setup issues

### LINKED ISSUE #7059: Provisioned Concurrency Does Not Work As Described
# Bug Report

Provisioned Concurrency was recently added in Serverless v1.59 and described in detail in this blog post: https://serverless.com/blog/aws-lambda-provisioned-concurrency/

The blog post makes the claim that enabling provisioned concurrency is as easy as:

```
functions:
  hello:
    handler: handler.hello
      events:
        - http:
            path: /hello
            method: get
    provisionedConcurrency: 5
```

This is not true.

What this configuration will do is assign provisioned concurrency to the version number that was deployed, but API Gateway will continue invoking the Lambda with the $LATEST alias (no version). What effectively ends up happening is every deploy keeps assigning provisioned concurrency to each new version and never actually utilizes it. If a developer does not use any version pruning they will quickly rack up an expensive bill paying for new provisioned capacity on each version, and potentially worse, eventually exhaust their reserved (or unreserved) concurrency on their AWS account.

I think this is a critical issue and needs to, at the very least, be addressed in the blog post. Without some form of version cleanup or aliasing I don't think there's much Serverless can do to make this work in a simple configuration like that.

### PR DESCRIPTION
**Pull request by medikoo**
Fixes #7059 

Setup provisioned concurrency on an alias that references function version. This allows us use provisioned concurrency easily with lambda versioning (otherwise we will have to somehow resolve old version hash to ensure to clear provisioned concurrency from there), and also workarounds "Internal Failure" error, which happens on AWS side, when we try to update version's provisioned concurrency configuration.

Link API Gateway endpoint against created alias, as when it's linked against function, it in all cases addresses `$LATEST` alias, which is not provisioned (and cannot be provisioned).

Additionally added workaround for current AWS issue, where changing referenced lambda version under alias with provisioned concurrency setup, resulted with `Alias with weights can not be used with Provisioned Concurrency` error.
It requires addition of 3 new resources, luckily they can be added once per service (not per lambda)

### CODE REVIEW

File: lib/plugins/aws/lib/naming.js [hunk 1]
```diff
@@ -163,8 +163,11 @@ module.exports = {
       ''
     )}`;
   },
-  getLambdaOnlyVersionLogicalId(functionName) {
-    return `${this.getNormalizedFunctionName(functionName)}LambdaVersion`;
+  getLambdaProvisionedConcurrencyVersionLogicalId(functionName) {
```
Comment (pmuens) [inline lib/plugins/aws/lib/naming.js]: We should test this with services which have functions with long function names as the suffix already counts 21 characters.

Comment (medikoo) [reply lib/plugins/aws/lib/naming.js]: This PR is in deep draft state (not yet issued for review)

Comment (pmuens) [reply lib/plugins/aws/lib/naming.js]: I know. Just wanted to raise awareness because we had a couple of issues with long names in the past.

Comment (medikoo) [reply lib/plugins/aws/lib/naming.js]: Sure, thank you @pmuens ! 👍

Comment (medikoo) [reply lib/plugins/aws/lib/naming.js]: @pmuens I've just double checked, and it's guaranteed to be shorter than lamba version logical id which we already use. Therefore I assume it's safe

Comment (pmuens) [reply lib/plugins/aws/lib/naming.js]: Great. Thanks for looking into that @medikoo :+1:
