### PR TITLE
DX: Add error tracking

### LINKED ISSUE #1610: Capture errors statistics
Right now error won't be tracked at all. We should add a way to track those to see what went wrong and how we can fix the bug.

/cc @flomotlik @eahefnawy

### PR DESCRIPTION
**Pull request by DavidWells**
Tracking errors will give us far more insight on where user pain lives.

This PR will start piping errors into sentry for us to tackle common problems users are facing.

Closes #1610

### CODE REVIEW

**Comment by DavidWells** [comment]
TODO:
- check for stats disabled
- abort if in CI/CD

Both todos are waiting on 2 other PRs I made https://github.com/serverless/serverless/pull/3563 & https://github.com/serverless/serverless/pull/3558 (new utils)

**Comment by pmuens** [comment]
Thanks for opening @DavidWells 👍 

FYI: Just merged #3563

File: lib/classes/Error.js [hunk 1]
```diff
@@ -51,6 +53,11 @@ module.exports.SError = module.exports.ServerlessError;
 
 module.exports.logError = (e) => {
   try {
+    // console.log(e)
+    // throw errors to sentry
+    // if (!fileExistsSync(statsDisabledFilePath)) { // ignore if tracking disabled
+    errorReporter.captureException(e);
```
Comment (pmuens) [inline lib/classes/Error.js]: Is there any way to ensure that this won't take forever when using a slow internet connection?

We've added a timeout in the `logStat` method here so that a failed attempt won't harm DX --> https://github.com/serverless/serverless/blob/754559296ec01252eeb0c7fc7132620fe93f6e36/lib/classes/Utils.js#L177

File: lib/classes/Error.js [hunk 2]
```diff
@@ -51,6 +53,11 @@ module.exports.SError = module.exports.ServerlessError;
 
 module.exports.logError = (e) => {
   try {
+    // console.log(e)
```
Comment (pmuens) [inline lib/classes/Error.js]: Can those comments be removed?

File: lib/utils/sentry.js [hunk 3]
```diff
@@ -0,0 +1,28 @@
+const raven = require('raven');
+const pkg = require('./../../package.json');
+
+const noSentry = process.env.SERVERLESS_DISABLE_DEBUG === 'false';
+const DSN = 'https://cbb3655b343a49ee9a18494d0dd171a7:4b9ef9a2c5eb40379f30b5e6808d3814@sentry.io/165477';
+
+function initializeErrorReporter() {
+  // if (!fileExistsSync(statsDisabledFilePath)) {
```
Comment (pmuens) [inline lib/utils/sentry.js]: Will this be kept for reference or should we remove those checks for now?

**Comment by LewisJEllis** [comment]
Hey @DavidWells - I maintain Sentry's Node SDK and I heard you were running into some difficulties here. At a glance everything looks fine, but if you could provide some simple "how to check this out and run it so that it should report an error" instructions, I'd be happy to take a look and see what's going on.

**Comment by DavidWells** [comment]
@LewisJEllis I seemed to be able to get it working if I wrap in a setTimeout https://github.com/serverless/serverless/blob/addErrorTracking/lib/classes/Error.js#L85-L87 and stop the process.exit call https://github.com/serverless/serverless/blob/addErrorTracking/lib/classes/Error.js#L89

It looks like any error call that is immediately thrown, without the setTimeout to run on the next loop, will not pass through. 

Have you seen this before?

**Comment by LewisJEllis** [comment]
Ah. The 'needing to not process.exit' bit is definitely something I've seen before (we made some changes to our exit condition handling in v2.0, might take a look at [global fatal error handler docs](https://docs.sentry.io/clients/node/usage/#global-fatal-error-handler)), but I haven't seen any cases of needing to do a setTimeout for the capture to work.

As of those changes in v2.0, Raven is now really good at "I caught an error that would have otherwise made the process explode, I'm going to capture it first and then shut down the process". 

What it looks like you're trying to do here, though, is "I have an error here, and I want to shut down because of it, but I want Raven to capture it first". Raven didn't catch the error, so it doesn't go through its usual "I'm gonna capture and then shut down" procedure, but you can get it to do that with:
```
Raven.uncaughtErrorHandler(err);
```
in place of your current `captureException` + `process.exit` and see if that behaves how you want. That method call should capture it and then shutdown (or call whatever callback you pass to install; again refer to those docs).

This method is undocumented, but it would be reasonable for me to polish and document if it fits this use case.

**Comment by DavidWells** [comment]
@eahefnawy having troubles fixing this test https://github.com/serverless/serverless/blob/addErrorTracking/lib/classes/Error.test.js#L122-L137

I haven't changed how it throws https://github.com/serverless/serverless/blob/addErrorTracking/lib/classes/Error.js#L94 

Here is master version https://github.com/serverless/serverless/blob/master/lib/classes/Error.js#L93

Any ideas?

**Comment by pmuens** [comment]
@DavidWells I looked into the re-throw error test.

Seems like this test was never really working as expected (Did some equality checks in `master`). I added some stubbing via `sinon` so that the `logError` throws an error as we expect in the test.

Furthermore I resolved the shrinkwrapping conflicts.

**Comment by pmuens** [comment]
@DavidWells I updated the tests for the `Error` class so that they are not failing anymore.

There are still 2 other tests failing, but those are related to some util functions. Let me know if you need any help over there.

**Comment by pmuens** [comment]
@DavidWells just fixed the tests 👍 

Will review and test it thoroughly ASAP so that we can merge and release this in `v.1.15`.
