### PR TITLE
Fix concurrency upload

### LINKED ISSUE #4545: AWS deploy bug: artifact is being re-uploaded for each function even when packaging individually is not enabled
# This is a Bug Report

## Description

I was wondering why [uploading a 8MB artifact zip takes 10+ minutes](https://forum.serverless.com/t/uploading-artifacts-takes-10-minutes-for-8mb/3284/3) and I believe I found the reason.

For bug reports:
* What went wrong?
When running `sls deploy` with individual packaging explicitly set to false, the artifact zip is re-uploaded for every function. If you have 5 functions, it is uploaded 5 times (the same exact file to the same exact s3 path).

* What did you expect should have happened?
It should only upload the artifact file once.

* What was the config you used?
_serverless.yml_

```
frameworkVersion: '=1.24.1'

service: ${{file(./package.json):name}}

plugins:
  # transpile functions' ES7 to ES5 for provider runtime compatibility
  - serverless-webpack
```

Note that I also tried it by explicitly disabling individual packaging but the result is the same:

```
package:
  individually: false
```

* What stacktrace or error message from your provider did you see?

To get some debugging output I added some log lines to `uploadArtifacts.js`:

```
uploadFunctions() {
    let shouldUploadService = false;
    this.serverless.cli.log('Uploading artifacts...');
    const functionNames = this.serverless.service.getAllFunctions();
    this.serverless.cli.log(`Uploading function names ${util.inspect(functionNames)}`);
    return BbPromise.map(functionNames, (name) => {
      this.serverless.cli.log(`Inside mapping function for function ${name}`);
      const functionArtifactFileName = this.provider.naming.getFunctionArtifactName(name);
      const functionObject = this.serverless.service.getFunction(name);
      functionObject.package = functionObject.package || {};
      let artifactFilePath = functionObject.package.artifact ||
        this.serverless.service.package.artifact;
      this.serverless.cli.log(`Artifact file path is ${artifactFilePath}`);
      if (!artifactFilePath ||
        (this.serverless.service.artifact && !functionObject.package.artifact)) {
        this.serverless.cli.log('Artifact file path not defined');
        if (this.serverless.service.package.individually || functionObject.package.individually) {
          this.serverless.cli.log('Individual packaging enabled');
          const artifactFileName = functionArtifactFileName;
          artifactFilePath = path.join(this.packagePath, artifactFileName);
          return this.uploadZipFile(artifactFilePath);
        }
        this.serverless.cli.log('should upload service = true');
        shouldUploadService = true;
        return BbPromise.resolve();
      }
      this.serverless.cli.log('returning final upload zip file call');
      return this.uploadZipFile(artifactFilePath);
    }, { concurrency: 3 }).then(() => {
      if (shouldUploadService) {
        this.serverless.cli.log('inside should upload service');
        const artifactFileName = this.provider.naming.getServiceArtifactName();
        const artifactFilePath = path.join(this.packagePath, artifactFileName);
        const stats = fs.statSync(artifactFilePath);
        this.serverless.cli.log(`Uploading service .zip file to S3 (${filesize(stats.size)})...`);
        return this.uploadZipFile(artifactFilePath);
      }
      this.serverless.cli.log('finally resolving');
      return BbPromise.resolve();
    });
  },
```

And also to `awsProvider.js`:

```
return persistentRequest(() => {
      const awsService = new that.sdk[service](credentials);
      
      let req
      if (method === 'upload') {
        this.serverless.cli.log(`Uploading with s3 bucket ${params.Bucket} and s3 key ${params.Key}`)
        req = awsService[method](params);
        req.on('httpUploadProgress', (progress) => {
          this.serverless.cli.log(util.inspect(progress))
        });
      }
      else {
        req = awsService[method](params);
      }

     ...
```

The output is as follows and confirms the unnecessary repeated uploads of the same file, once for each function:

```
> export AWS_PROFILE=sls-$STAGE && export AWS_CLIENT_TIMEOUT=300000 && ./node_modules/serverless/bin/serverless deploy --verbose --stage $STAGE --aws-s3-accelerate

Serverless: WARNING: More than one matching handlers found for 'scripts/request-certificate'. Using 'scripts/request-certificate.js'.
bundling with webpack for environment undefined
Serverless: Removing /Users/tommedema/Drive/education/serverless/aws-serverless-crud-starter/.webpack
Serverless: Bundling with Webpack...

Serverless: Fetch dependency graph from /Users/tommedema/Drive/education/serverless/aws-serverless-crud-starter/package.json
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: source-map-support@^0.5.0, babel-runtime@^6.26.0, aws-sdk@^2.166.0, cfn-response@^1.0.1, pify@^3.0.0, async-retry@^1.1.4
Serverless: Package took [3391 ms]
Serverless: Copy modules: /Users/tommedema/Drive/education/serverless/aws-serverless-crud-starter/.webpack/service [1045 ms]
Serverless: Prune: /Users/tommedema/Drive/education/serverless/aws-serverless-crud-starter/.webpack/service [458 ms]
Serverless: Zip service: /Users/tommedema/Drive/education/serverless/aws-serverless-crud-starter/.webpack/service [2165 ms]
Serverless: Packaging service...
Serverless: Remove /Users/tommedema/Drive/education/serverless/aws-serverless-crud-starter/.webpack
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading with s3 bucket notes-api-acm-serverlessdeploymentbucket-1rengvvxxbyz5 and s3 key serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/compiled-cloudformation-template.json
Serverless: { loaded: 25150,
  total: 25150,
  part: 1,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/compiled-cloudformation-template.json' }
Serverless: Uploading artifacts...
Serverless: Uploading function names [ 'requestCertificate',
  'create',
  'get',
  'list',
  'update',
  'delete' ]
Serverless: Inside mapping function for function requestCertificate
Serverless: Artifact file path is .serverless/notes-api.zip
Serverless: returning final upload zip file call
Serverless: reading artifact file...
Serverless: uploading artifact to s3...
Serverless: Uploading with s3 bucket notes-api-acm-serverlessdeploymentbucket-1rengvvxxbyz5 and s3 key serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip
Serverless: Inside mapping function for function create
Serverless: Artifact file path is .serverless/notes-api.zip
Serverless: returning final upload zip file call
Serverless: reading artifact file...
Serverless: uploading artifact to s3...
Serverless: Uploading with s3 bucket notes-api-acm-serverlessdeploymentbucket-1rengvvxxbyz5 and s3 key serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip
Serverless: Inside mapping function for function get
Serverless: Artifact file path is .serverless/notes-api.zip
Serverless: returning final upload zip file call
Serverless: reading artifact file...
Serverless: uploading artifact to s3...
Serverless: Uploading with s3 bucket notes-api-acm-serverlessdeploymentbucket-1rengvvxxbyz5 and s3 key serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip
Serverless: { loaded: 5242880,
  total: 7846272,
  part: 1,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: { loaded: 7846272,
  total: 7846272,
  part: 2,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: { loaded: 5242880,
  total: 7846272,
  part: 1,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: { loaded: 7846272,
  total: 7846272,
  part: 2,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: { loaded: 5242880,
  total: 7846272,
  part: 1,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: { loaded: 7846272,
  total: 7846272,
  part: 2,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: Inside mapping function for function delete
Serverless: Artifact file path is .serverless/notes-api.zip
Serverless: returning final upload zip file call
Serverless: reading artifact file...
Serverless: uploading artifact to s3...
Serverless: Uploading with s3 bucket notes-api-acm-serverlessdeploymentbucket-1rengvvxxbyz5 and s3 key serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip
Serverless: { loaded: 5242880,
  total: 7846272,
  part: 1,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: { loaded: 7846272,
  total: 7846272,
  part: 2,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: Inside mapping function for function update
Serverless: Artifact file path is .serverless/notes-api.zip
Serverless: returning final upload zip file call
Serverless: reading artifact file...
Serverless: uploading artifact to s3...
Serverless: Uploading with s3 bucket notes-api-acm-serverlessdeploymentbucket-1rengvvxxbyz5 and s3 key serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip
Serverless: { loaded: 5242880,
  total: 7846272,
  part: 1,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: { loaded: 7846272,
  total: 7846272,
  part: 2,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: { loaded: 7846272,
  total: 7846272,
  part: 1,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: Inside mapping function for function list
Serverless: Artifact file path is .serverless/notes-api.zip
Serverless: returning final upload zip file call
Serverless: reading artifact file...
Serverless: uploading artifact to s3...
Serverless: Uploading with s3 bucket notes-api-acm-serverlessdeploymentbucket-1rengvvxxbyz5 and s3 key serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip
Serverless: { loaded: 5242880,
  total: 7846272,
  part: 1,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: { loaded: 7846272,
  total: 7846272,
  part: 2,
  key: 'serverless/notes-api/acm/1512849441070-2017-12-09T19:57:21.070Z/notes-api.zip' }
Serverless: finally resolving
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress..
```

What's also bad is that it seems to be doing this serially for each function, rather than in parallel.

Uploading takes about 10 minutes while it only takes ~1.5 minute when I upload the file manually using the AWS CLI (`aws s3 sync`). This again confirms the above issue (5*2=10).

Similar or dependent issues:
* NA

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: OSX Sierra
* ***Stack Trace***: NA
* ***Provider Error messages***: NA

### PR DESCRIPTION
**Pull request by franciscocpg**
## What did you implement:

Closes #4545

## How did you implement it:

I'm mapping artifact file paths uniquely before uploading it.

### The problem
Clone this repo. Let's call the path to the directory where you've cloned it as: `${path_to_serverless_repo}`.

Install dependencies: `cd ${path_to_serverless_repo} && npm install`.

Edit `serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js` and add `console.log('Uploading')` before line 73.
https://github.com/serverless/serverless/blob/3e717fa33708a15bc4d8031bd0276fcf9e6da4b7/lib/plugins/aws/deploy/lib/uploadArtifacts.js#L73-L75

Then run
```shell
path_to_serverless_repo="path to directory where you've this repo"
cd /tmp
mkdir aws-nodejs-ecma-script && cd aws-nodejs-ecma-script
${path_to_serverless_repo}/bin/serverless create --template aws-nodejs-ecma-script
npm i
${path_to_serverless_repo}/bin/serverless deploy
```

You should see 
```
(...)
Uploading
Uploading
(...)
```
We don't need `Uploading` twice here because the artifact is the same for both functions.

### The solution
Checkout this PR branch. 
```shell
cd ${path_to_serverless_repo}
git remote add franciscocpg https://github.com/franciscocpg/serverless.git
git fetch franciscocpg
git checkout franciscocpg/fix-concurrency-upload
```

Edit `serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js` and add `console.log('Uploading')` before line 76.
https://github.com/franciscocpg/serverless/blob/ede4824c97329af0bc5607960453bebb9d1d1bff/lib/plugins/aws/deploy/lib/uploadArtifacts.js#L76-L80

Then run
```shell
path_to_serverless_repo="path to directory where you've this repo"
cd /tmp/aws-nodejs-ecma-script
${path_to_serverless_repo}/bin/serverless deploy
```

You should see `Uploading` just once.

The spec below also proves it.
https://github.com/franciscocpg/serverless/blob/ede4824c97329af0bc5607960453bebb9d1d1bff/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js#L255-L273

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by franciscocpg** [comment]
@HyperBrain 
Could you take a look here?

**Comment by HyperBrain** [comment]
@franciscocpg Yes, will do tomorrow.

**Comment by franciscocpg** [comment]
Thank you @HyperBrain :smiley:

**Comment by mafrosis** [comment]
Is this pull request good for testing? My lambda deployment takes _a very long time_ at present. I found this looking for a others with the same problem.

**Comment by HyperBrain** [comment]
@mafrosis I think so. Can you give it a try and report, if everything works for you (and it is faster than before)?

File: lib/plugins/aws/deploy/lib/uploadArtifacts.js [hunk 1]
```diff
@@ -76,36 +77,36 @@ module.exports = {
...
-      if (shouldUploadService) {
-        const artifactFileName = this.provider.naming.getServiceArtifactName();
-        const artifactFilePath = path.join(this.packagePath, artifactFileName);
-        const stats = fs.statSync(artifactFilePath);
-        this.serverless.cli.log(`Uploading service .zip file to S3 (${filesize(stats.size)})...`);
-        return this.uploadZipFile(artifactFilePath);
-      }
-      return BbPromise.resolve();
-    });
+    }, { concurrency: 3 }
```
Comment (HyperBrain) [inline lib/plugins/aws/deploy/lib/uploadArtifacts.js]: We could define this as constant above in the file (e.g. `NUM_CONCURRENT_UPLOADS: 3`) and use that here instead of the literal number. 
Additionally, it might be useful to have an override in `serverless.yml` under the provider property to change the number if needed. Of course, if 3 is ok for all uses, we do not need that.

Comment (franciscocpg) [reply lib/plugins/aws/deploy/lib/uploadArtifacts.js]: @HyperBrain, I agree about the constant and did it.

About the option to override in `serverless.yml` IMO we should move on with this constant and check if users will want/need it in the future.

**Comment by HyperBrain** [comment]
@franciscocpg Great work 🥇 and sorry for the late approval.

File: lib/plugins/aws/deploy/lib/uploadArtifacts.js (hunk 1 above)
Comment (HyperBrain) [reply lib/plugins/aws/deploy/lib/uploadArtifacts.js]: Yep. Agree. If there is need for it, we'll see it.
