### PR TITLE
Fix validation after API Gateway deployment

### LINKED ISSUE #6117: Cannot read property 'events' of undefined
# This is a Bug Report

## Description

* What went wrong?
An error when deploying a package. The service is deployed correctly but the Package plugin is throwing an error at the end. If deploying without packaging it first, no errors are thrown but I want to package first so I can have different stages in my CI.

    Commands run:
    * `sls package -p package`
    * `sls deploy --package package`

* What did you expect should have happened?
No errors

* What was the config you used?
```
provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, "dev"}

  region: us-east-1
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/AmazonCognitoPowerUser"
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"

package:
  exclude:
  - node_modules/**
  - .idea/**
  - __pycache__/**
  - package.json
  - package-lock.json
  - sls_hooks/**
  - Pipfile
  - resource/**

functions:
  postSignUp:
    handler: cognito/postSignupConfirmation.handler
    events:
    - cognitoUserPool:
        pool: myUserPool
        trigger: PostConfirmation

  graphql:
    handler: graphql_api.handler
    runtime: python3.6

  download:
    handler: api_gateway/download.handler
    runtime: python3.6
    events:
      - http:
          path: download
          method: get

```

* What stacktrace or error message from your provider did you see?
```
  Stack Trace -------------------------------------------- 
  
TypeError: Cannot read property 'events' of undefined 
    at Object.after:deploy:deploy [as hook] (/codebuild/output/src613376632/src/backend/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:77:28) 
    at BbPromise.reduce (/codebuild/output/src613376632/src/backend/node_modules/serverless/lib/classes/PluginManager.js:422:55) 
From previous event: 
    at PluginManager.invoke (/codebuild/output/src613376632/src/backend/node_modules/serverless/lib/classes/PluginManager.js:422:22) 
    at PluginManager.run (/codebuild/output/src613376632/src/backend/node_modules/serverless/lib/classes/PluginManager.js:453:17) 
    at variables.populateService.then (/codebuild/output/src613376632/src/backend/node_modules/serverless/lib/Serverless.js:109:33) 
    at runCallback (timers.js:705:18) 
    at tryOnImmediate (timers.js:676:5) 
    at processImmediate (timers.js:658:5) 
    at process.topLevelDomainCallback (domain.js:120:23) 
From previous event: 
    at Serverless.run (/codebuild/output/src613376632/src/backend/node_modules/serverless/lib/Serverless.js:96:6) 
    at serverless.init.then (/codebuild/output/src613376632/src/backend/node_modules/serverless/bin/serverless:43:28) 
    at /codebuild/output/src613376632/src/backend/node_modules/graceful-fs/graceful-fs.js:111:16 
    at /codebuild/output/src613376632/src/backend/node_modules/graceful-fs/graceful-fs.js:45:10 
    at FSReqWrap.args [as oncomplete] (fs.js:140:20) 
From previous event: 
    at initializeErrorReporter.then (/codebuild/output/src613376632/src/backend/node_modules/serverless/bin/serverless:43:6) 
    at runCallback (timers.js:705:18) 
    at tryOnImmediate (timers.js:676:5) 
    at processImmediate (timers.js:658:5) 
    at process.topLevelDomainCallback (domain.js:120:23) 
From previous event: 
    at /codebuild/output/src613376632/src/backend/node_modules/serverless/bin/serverless:28:46 
    at Object.<anonymous> (/codebuild/output/src613376632/src/backend/node_modules/serverless/bin/serverless:65:4) 
    at Module._compile (internal/modules/cjs/loader.js:701:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) 
    at Module.load (internal/modules/cjs/loader.js:600:32) 
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12) 
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) 
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12) 
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14) 
```

Similar or dependent issues:
None that I know of

## Additional Data

* ***Serverless Framework Version you're using***: 1.42.1
* ***Operating System***: Amazon Linux but also happens locally in my Macbook OS X
* ***Stack Trace***: 
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by pmuens**
## What did you implement:

Closes #6117 

Fixes the bug where the event validation fails when the packaged service is deployed.

## How did you implement it:

Added a helper method which checks if a given event is used in a service.

## How can we verify it:

Use the following `serverless.yml` file:

```yaml
service: test

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  tags:
    foo: bar
    baz: qux
    num: 1234
  tracing:
    apiGateway: true
  logs:
    restApi: true
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  test:
    handler: handler.hello
    events:
       - http:
           method: GET
           path: hello
```

Run

```
serverless package -p package
```

Comment out the whole `functions` section (with this we check the `after:deploy:deploy` hook will use the correct `serverless-state.json` file to check if API Gateway setup needs to be updated).

Run

```
serverless deploy --package package
```

Validate that the API Gateway setup is updated and you have tracing etc. enabled.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/plugins/aws/lib/getServiceState.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+const path = require('path');
+
+module.exports = {
+  getServiceState() {
```
Comment (pmuens) [inline lib/plugins/aws/lib/getServiceState.js]: Sticked to this export schema so that we can re-use this easily in existing plugins (and therefore use `this.serverless...`).

File: lib/classes/Service.js [hunk 2]
```diff
@@ -280,6 +280,20 @@ class Service {
...
+      const events = func.events || [];
+      if (events.length) {
+        events.forEach(event => {
+          if (Object.keys(event)[0] === eventName) {
+            accum = true; // eslint-disable-line no-param-reassign
+          }
+        });
+      }
+      return accum;
+    }, false);
```
[the remark this answers is not in the document]
Comment (pmuens) [reply lib/classes/Service.js]: Yes, good call. I was in a rush and saw the `forEach` inside the `reduce` so I just wrote it like that.

File: lib/plugins/aws/package/compile/events/apiGateway/index.js [hunk 3]
```diff
@@ -72,9 +72,11 @@ class AwsCompileApigEvents {
 
       // TODO should be removed once AWS fixes the CloudFormation problems using a separate Stage
       'after:deploy:deploy': () => {
+        const getServiceState = require('../../../../lib/getServiceState').getServiceState;
         const updateStage = require('./lib/hack/updateStage').updateStage;
 
-        if (this.validated.events.length === 0) {
+        const state = getServiceState.call(this);
+        if (!this.serverless.utils.isEventUsed(state.service.functions, 'http')) {
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/apiGateway/index.js]: Shouldn't we also rely on resolved `state` in `updateStage` hack?

Comment (pmuens) [reply lib/plugins/aws/package/compile/events/apiGateway/index.js]: Do you mean rather than using `this.serverless.service` we should use `state.service`?

Comment (medikoo) [reply lib/plugins/aws/package/compile/events/apiGateway/index.js]: I believe so, otherwise it'll be that for CF deployment we take from `.serverless` folder, and for SDK phase we take from `serverless.yml`.
Both can be out of sync, and I assume we should rely on one config source (?)

Comment (pmuens) [reply lib/plugins/aws/package/compile/events/apiGateway/index.js]: Yes, you're right. Good catch. Providing a fix in a sec...

**Comment by pmuens** [comment]
Just updated the code so that we pull the desired config from the state file rather than using `serverless.yml`. This way we can ensure that "normal" deployment and `package` + `deploy` works as expected.
