### PR TITLE
Fix handling of event bridge events removal

### LINKED ISSUE #7655: Deployment appears to fail when removing a Lambda function using EventBridge (but doesn't)
# Bug Report

## Description

1. What did you do?

I deployed a stack with Lambda functions connected to EventBridge, and removed one.

1. What happened?

The deployment appeared to fail: The message "Operation failed!" appeared. However, the lambda is correctly removed.

1. What should've happened?

The deployment should have gone smoothly, and not triggered a false positive.

1. What's the content of your `serverless.yml` file?

```
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: test
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  test1:
    handler: test.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          pattern:
            source:
              - whatever
            detail-type:
              - whatever
  test2:
    handler: test.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          pattern:
            source:
              - whatever
            detail-type:
              - whatever

custom:
  eventBusArn: arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:event-bus/my-bus
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

*An error occurred: CustomEventBridge1 - Failed to delete resource. User: ...-custom-resource-event-bridge is not authorized to perform: lambda:RemovePermission on resource: ...test3 See details in CloudWatch Log: ...*

### PR DESCRIPTION
**Pull request by bratchenko**
Fixes https://github.com/serverless/serverless/issues/7655.

The current implementation creates a policy that looks like this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "events:PutRule",
                "events:RemoveTargets",
                "events:PutTargets",
                "events:DeleteRule"
            ],
            "Resource": "arn:aws:events:us-east-1:<account id>:rule/issue-7655x-dev-test1-rule-1",
            "Effect": "Allow"
        },
        {
            "Action": [
                "lambda:AddPermission",
                "lambda:RemovePermission"
            ],
            "Resource": "arn:aws:lambda:us-east-1:<account id>:function:issue-7655-dev-test1",
            "Effect": "Allow"
        }
    ]
}
```

The problem is that this role needs access to resources deployed in the previous version of the application to clean them up during the cleanup phase of CloudFormation.

This PR replaces specific resources like `arn:aws:lambda:us-east-1:<account id>:function:issue-7655-dev-test1` with wildcards `arn:aws:lambda:us-east-1:<account id>:function:*`. This allows the cleanup to complete successfully.

A more secure but more complex way to do this would be to add wildcards only to `Remove` actions while keeping a very specific policy for `Create` actions. I went for simplicity over additional specificity.

The new policy looks like this:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "events:PutRule",
                "events:RemoveTargets",
                "events:PutTargets",
                "events:DeleteRule"
            ],
            "Resource": "arn:aws:events:us-east-1:<account id>:rule/*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "lambda:AddPermission",
                "lambda:RemovePermission"
            ],
            "Resource": "arn:aws:lambda:us-east-1:<account id>:function:*",
            "Effect": "Allow"
        }
    ]
}
```

I've verified this fix works with a manual test case described here: https://github.com/serverless/serverless/issues/7655#issuecomment-664534942

### CODE REVIEW

File: lib/plugins/aws/package/compile/events/eventBridge/index.js [hunk 1]
```diff
@@ -190,30 +148,52 @@ class AwsCompileEventBridgeEvents {
...
+        Effect: 'Allow',
+        Resource: ruleResources,
+        Action: [
+          'events:PutRule',
+          'events:RemoveTargets',
+          'events:PutTargets',
+          'events:DeleteRule',
+        ],
+      });
+      const functionResources = {
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/eventBridge/index.js:177]: Shouldn't this be applied only if at least one event bridge event referenced event bus?

At least this will match original implementation

Comment (bratchenko) [reply lib/plugins/aws/package/compile/events/eventBridge/index.js:177]: If I'm reading the code correctly, it was adding `lambda:AddPermission` and `lambda:RemovePermission` for each function that uses EventBridge event (`funcUsesEventBridge` flag). In the new version, we add this rule if *at least one function users EventBridge event*, which is the same logic.

If you mean `events:*` permissions, it also seems like we have added them if at least one function uses any event bridge events.

**Comment by bratchenko** [comment]
@medikoo no luck running integration tests. I run them as: `AWS_ACCESS_KEY=<> AWS_SECRET_ACCESS_KEY=<> npx mocha tests/integration-all/event-bridge/tests.js` but get the error: `ENOENT: no such file or directory, open '/var/folders/8l/ds6fkcfx5lscn2w8zdwxtw6c0000gp/T/tmpdirs-serverless/2e66/.aws/credentials'`. Any advice? I tried `npm run integration-test-run-all` as well with the same error.

File: lib/plugins/aws/package/compile/events/eventBridge/index.js (hunk 1 above)
Comment (medikoo) [reply lib/plugins/aws/package/compile/events/eventBridge/index.js:182]: Thanks for explanations, I see it's ok

**Comment by bratchenko** [comment]
Running tests with `sudo` helped. Not ideal, but nothing other worked. Good news is the tests ran successfully:

```
daniil:serverless daniil$ sudo AWS_ACCESS_KEY_ID=<> AWS_SECRET_ACCESS_KEY=<> npx mocha tests/integration-all/event-bridge/tests.js


  AWS - Event Bridge Integration Test
Temporary path: /tmp/tmpdirs-serverless/f0f9/767c464297aad534
Creating Event Bus "integ-test-17081266-arn-event-bus"...
Updating serverless.yml with Event Bus arn "arn:aws:events:us-east-1:891311379611:event-bus/integ-test-17081266-arn-event-bus"
Deploying "integ-test-17081266-dev" service...
    Default Event Bus
      ✓ should invoke function when an event is sent to the event bus (13593ms)
    Custom Event Bus
      ✓ should invoke function when an event is sent to the event bus (13144ms)
    Arn Event Bus
      ✓ should invoke function when an event is sent to the event bus (12996ms)
Removing service...
Deleting Event Bus "integ-test-17081266-arn-event-bus"...


  3 passing (3m)

```

**Comment by bratchenko** [comment]
@medikoo done. Updated from the latest upstream master.
