### PR TITLE
Fixed python module parsing

### LINKED ISSUE #4663: Invoke local for Python can not run handler in subpackage
# This is a Bug Report

## Description

* What went wrong?

    When I put my python handler function in a subpackage, `invoke local` can not run it.

* What did you expect should have happened?

    `invoke local` should be able to run it, the same as on AWS.

* What was the config you used?

```yaml
functions:
  events-sqs-queuehandler:
    handler: events.sqs.queuehandler.handler
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: Docker
* ***Stack Trace***:
```
Traceback (most recent call last):
  File "/usr/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 61, in <module>
    handler = getattr(module, args.handler_name)
AttributeError: module 'events' has no attribute 'sqs'
```

### PR DESCRIPTION
**Pull request by dfee**
Ref: https://github.com/serverless/serverless/issues/4663#issuecomment-366931491

## What did you implement:

Closes #4663

The problem is that Python module parsing wasn't correctly performed. For example, consider a function handler, `xyz.scripts.task.entrypoint`. Currently, it is converted into `handlerPath = 'xyz';` and `handlerName = 'scripts'`, but we actually want `handlerPath = 'xyz.scripts.task'` and `handlerName = 'entrypoint'`.

## How did you implement it:

The change is quite simple: rather than splitting the `handler` variable at the first `.`, we instead split it at the last `.`.

## How can we verify it:

https://github.com/dfee/serverless_pymodule_demo

If you run this with the unpatched invoke/index.js you'll get the following message:
```bash
$ sls invoke local -f entrypoint
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 61, in <module>

    handler = getattr(module, args.handler_name)
AttributeError: module 'mypackage' has no attribute 'mymodule'
```

If you invoke this with the patched invoke/index.js you'll get the following (as expected):
```bash
$ sls invoke local -f entrypoint
true
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** Yes
***Is it a breaking change?:*** No

### CODE REVIEW

**Comment by dfee** [comment]
I have no idea why this would fail on travis-ci, but I'm going to speculate it's not related to my changes: https://travis-ci.org/serverless/serverless/jobs/344115053#L960

**Comment by HyperBrain** [comment]
I just restarted the Travis build. let's see if it does not timeout now.

**Comment by HyperBrain** [comment]
Can you check the todo checkboxes above and set "ready for review" to YES if it is ready?

**Comment by dfee** [comment]
@HyperBrain done.

**Comment by HyperBrain** [comment]
In which regard is this change breaking? In my opinion it only fixes the handler parsing correctly 😄

**Comment by dfee** [comment]
Ah geeze. Sorry about that.

File: lib/plugins/aws/invokeLocal/index.js [hunk 1]
```diff
@@ -130,8 +130,9 @@ class AwsInvokeLocal {
     }
 
     if (runtime === 'python2.7' || runtime === 'python3.6') {
-      const handlerPath = handler.split('.')[0];
-      const handlerName = handler.split('.')[1];
+      const handlerComponents = handler.split(/[.]+/);
```
Comment (HyperBrain) [inline lib/plugins/aws/invokeLocal/index.js]: Splitting on consecutive dots might lead to unwanted results here, e.g.
```
my..my.myTest => handlerPath=my.my    handlerName=myTest
```
So the original double dot in the path is swallowed.

Splitting on single dots only will fix that:
`const handlerComponents = handler.split(/\./);`

Comment (dfee) [reply lib/plugins/aws/invokeLocal/index.js]: It is swallowed, but I don't think that's a valid module path.

For example, using __import__ directly:
```python
In [6]: from my..my import myTest
  File "<ipython-input-6-262523a38747>", line 1
    from my..my import myTest
            ^
SyntaxError: invalid syntax
```
