### PR TITLE
Existing S3 bucket fixes

### LINKED ISSUE #6409: Serverless implicitly lowercases object suffix when using existing S3
# This is a Bug Report

## Description

- What went wrong?

I'm setting an event on an existing S3 bucket, as described in https://serverless.com/framework/docs/providers/aws/events/s3#using-existing-buckets. When setting the event this way, `serverless` implicitly lowercases the object suffix in the event rule. This causes the event not to work when the created object has a suffix that is not lowercase.

- What did you expect should have happened?

Serverless should preserve the casing of the suffix when creating the event rule. For comparison, the [existing-s3](https://www.npmjs.com/package/serverless-plugin-existing-s3) plugin preserves the casing.

- What was the config you used?

```yaml
      - s3:
          bucket: ${opt:s3-bucket}
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: my-output/
            - suffix: _LATEST
          existing: true
```

Similar or dependent issues:

N/A

## Additional Data

- Serverless version: 1.48.0
- OS: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by pmuens**
## What did you implement:

Closes #6409

Fixes some issues with existing S3 buckets. E.g. the prefix / suffix values were always lowercased. Also uses Refs and AWS Variables to construct IAM policies.

## How did you implement it:

Fix it and write regression tests.

## How can we verify it:

The easiest way is to run the integration tests for S3 buckets.

Otherwise you can also deploy the following service:

```yaml
service: test-${self:custom.idx}

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

custom:
  idx: 0
  bucket: serverless-existing-s3-bucket # change this with your bucket name

functions:
  test:
    handler: handler.hello
    events:
      - s3:
          bucket: ${self:custom.bucket}
          events: s3:ObjectCreated:*
          rules:
            - suffix: .txt
            - prefix: CamelCase/
          existing: true
```

## Todos:

_**Note: Run `npm run test-ci` to run all validation checks on proposed changes**_

- [x] Write tests and confirm existing functionality is not broken.  
       **Validate via `npm test`**
- [x] Ensure there are no lint errors.  
       **Validate via `npm run lint-updated`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [x] Ensure introduced changes match Prettier formatting.  
       **Validate via `npm run prettier-check-updated`**  
       _Note: All reported issues can be automatically fixed by running `npm run prettify-updated`_
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

File: lib/plugins/aws/package/compile/events/s3/index.js [hunk 1]
```diff
@@ -254,7 +254,9 @@ class AwsCompileS3Events {
 
             iamRoleStatements.push({
               Effect: 'Allow',
-              Resource: `arn:aws:s3:::${bucket}`,
+              Resource: {
+                'Fn::Join': ['', ['arn:', { Ref: 'AWS::Partition' }, `:s3:::${bucket}`]],
```
Comment (quassnoi) [inline lib/plugins/aws/package/compile/events/s3/index.js]: What happens if the `bucket` is not a string but an object (like a `Ref` or an `ImportValue`)?

Comment (pmuens) [reply lib/plugins/aws/package/compile/events/s3/index.js]: Thanks for the pointer. Yes, we definitely have to support that as well and I saw your PR the other day. I'd say that we ship this PR since it addresses a couple of other blocking issues and after that we should focus on the improvements you've proposed via https://github.com/serverless/serverless/pull/6417

Comment (quassnoi) [reply lib/plugins/aws/package/compile/events/s3/index.js]: thanks!

Comment (pmuens) [reply lib/plugins/aws/package/compile/events/s3/index.js]: Thanks for working on the fix for that! :+1:
