### PR TITLE
Filter out duplicate create/delete event bus custom policies

### LINKED ISSUE #7643: Maximum policy size of 10240 bytes exceeded - event bridge triggered lambdas
# Bug Report

## Description

1. What did you do?

I deployed a stack using 20+ lambdas triggered by event bridge events, on the same event bus.

1. What happened?

The deployment failed with error "Maximum policy size of 10240 bytes exceeded for role xxx...IamRoleCustomResourcesLa-ZKI29XIB3PPS"

1. What should've happened?

The deployment should have succeeded.

1. What's the content of your `serverless.yml` file?

Of interest for this issue: An event bridge resource and 20+ lambdas using it.

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

ServerlessError: An error occurred: IamRoleCustomResourcesLambdaExecution - Maximum policy size of 10240 bytes exceeded for role ...-IamRoleCustomResourcesLa-ZKI29XIB3PPS (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded; Request ID: ...).

Similar or dependent issues:

- #6212 
- #2508

### PR DESCRIPTION
**Pull request by ThomasAribart**
## What did you implement

Closes #7643 

On my project, I deployed a stack with 20+ lambdas connected to EventBridge and ran into a "Maximum policy size" error during deployment for the IamRoleCustomResourcesLa policy.

Upon inspection, I found that a policy for event bus creation/deletion is duplicated for each lambda. I managed to reduce the size of the custom resources policy  by ~30% by removing this duplication (in the case where it contains only lambdas using event bridges).

## How can we verify it

```
service:
  name: serverless-issue-7643

package:
  exclude:
    - .git/**
    - .gitignore

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  test1:
    handler: test.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          pattern:
            source:
              - whatever
            detail-type:
              - whatever
  test2:
    handler: test.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          pattern:
            source:
              - whatever
            detail-type:
              - whatever
...
  test25:
    handler: test.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          pattern:
            source:
              - whatever
            detail-type:
              - whatever


custom:
  eventBusArn: arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:event-bus/event-bus-issue-7643
```

The deployment should not fail. You should see the following policy **only once** in the IamRoleCustomResourcesLa policy:

```
{
  "Effect":"Allow",
  "Resource":{"Fn::Join":[":",["arn",{"Ref":"AWS::Partition"},"events",{"Ref":"AWS::Region"},{"Ref":"AWS::AccountId"},"event-bus/event-bus-issue-7643"]]},
  "Action":["events:CreateEventBus","events:DeleteEventBus"]
}
```

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test:ci` --> Run all validation checks on proposed changes
- `npm run lint:updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check:updated` --> Check if updated files adhere to Prettier config
- `npm run prettify:updated` --> Prettify all the updated files

</details>

- [x] Write and run all tests
- [ ] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

File: lib/plugins/aws/package/compile/events/eventBridge/index.js [hunk 1]
```diff
@@ -159,11 +159,20 @@ class AwsCompileEventBridgeEvents {
...
+                const createDeleteEventBusStmt = {
                   Effect: 'Allow',
                   Resource: eventBusResource,
                   Action: ['events:CreateEventBus', 'events:DeleteEventBus'],
-                });
+                };
+
+                if (
+                  _.findIndex(iamRoleStatements, stmt =>
+                    _.isEqual(stmt, createDeleteEventBusStmt)
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/eventBridge/index.js:171]: We're trying to avoid lodash for construct which could easily be reflected with native means, and I think here it's the case.

Also with repeated array search we'll not that optimal. Of course in this case it's hard to approach any performance issues, but I believe it'll also be logically cleaner to resort structures as `Map`. Therefore what about switching to logic as:

```javascript
const eventBusIamRoleStatements = new Map();
...
if (!eventBusIamRoleStatements.has(eventBusName)) {
  eventBusIamRoleStatements.set(eventBusName, {
    Effect: 'Allow',
    ...
  });
}
...
iamRoleStatements.push(...eventBusIamRoleStatements.values())
```

**Comment by ThomasAribart** [comment]
Thanks @medikoo 👍 I implemented the requested change !
