### PR TITLE
Kubeless template for python and nodejs

### LINKED ISSUE #3969: create function template for kubeless provider
# This is a Feature Proposal

## Description

Add the ability to create function template for the kubeless provider:

```
serverless create --template kubeless-python --path foobar
```

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by sebgoa**
## What did you implement:

Closes #3969

template creation for kubeless provider

## How did you implement it:

add templates in `lib/plugins/create/templates/kubeless-python`
and `lib/plugins/create/templates/kubeless-nodejs`

modified:

`lib/plugins/create/create.js`
`lib/plugins/create/create.test.js`

Plus the removal of the provider validation in:

https://github.com/serverless/serverless/pull/3941

## How can we verify it:

Install the PR and try:

```
serverless create --template kubeless-nodejs --path sebgoa
Serverless: Generating boilerplate...
Serverless: Generating boilerplate in "/Users/sebgoa/Desktop/foobar/sebgoa"
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.17.0
 -------'

Serverless: Successfully generated boilerplate for template: "kubeless-nodejs"
```

or

```
serverless create --template kubeless-python --path foobar
```

## Todos:

- [ ] Write tests
- [ ] Write documentation

***Is this ready for review?:*** YES

But this also include the change pending in https://github.com/serverless/serverless/pull/3941

And let me know when you are ready to merge, as we will increment the plugin version number in the PR before merge.

***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/classes/Service.js [hunk 1]
```diff
@@ -92,16 +92,6 @@ class Service {
           };
         }
 
-        const providers = ['aws', 'azure', 'google', 'openwhisk'];
```
Comment (pmuens) [inline lib/classes/Service.js]: Can you remove this part since it'll be included in #3611.

File: lib/classes/Service.test.js [hunk 2]
```diff
@@ -572,23 +572,6 @@ describe('Service', () => {
       });
     });
 
-    it('should reject if provider property is invalid', () => {
```
Comment (pmuens) [inline lib/classes/Service.test.js]: This should be removed since it's part of #3611.

File: lib/plugins/create/templates/kubeless-python/.gitignore [hunk 3]
```diff
@@ -0,0 +1,6 @@
+# package directories
```
Comment (pmuens) [inline lib/plugins/create/templates/kubeless-python/.gitignore]: This file needs to be named `gitignore` (without a `.`). See --> https://github.com/serverless/serverless/tree/master/lib/plugins/create/templates/aws-nodejs

We had an issue with `.gitignore` and `.npmignore` and decided to add an extra step which updates the file from `gitignore` to `.gitgnore`.

File: lib/plugins/create/templates/kubeless-python/package.json [hunk 4]
```diff
@@ -0,0 +1,17 @@
+{
+  "name": "kubeless-python",
+  "version": "1.0.0",
+  "description": "Sample Kubeless Python serverless framework service.",
+  "dependencies": {
+    "serverless-kubeless": "^0.1.1"
```
Comment (pmuens) [inline lib/plugins/create/templates/kubeless-python/package.json]: Why not version `0.1.3`?

File: lib/plugins/create/create.test.js [hunk 5]
```diff
@@ -387,6 +387,38 @@ describe('Create', () => {
...
+      create.options.template = 'kubeless-nodejs';
+
+      return create.create().then(() => {
+        expect(create.serverless.utils.fileExistsSync(path.join(tmpDir, 'package.json')))
+          .to.be.equal(true);
+        expect(create.serverless.utils.fileExistsSync(path.join(tmpDir, 'serverless.yml')))
+          .to.be.equal(true);
+        expect(create.serverless.utils.fileExistsSync(path.join(tmpDir, 'handler.js')))
+          .to.be.equal(true);
+        expect(create.serverless.utils.fileExistsSync(path.join(tmpDir, '.gitignore')))
```
Comment (pmuens) [inline lib/plugins/create/create.test.js]: This file seems to be missing. Please note the comment about the `gitignore` file name below when adding it.

**Comment by sebgoa** [comment]
ok all fixed I think.

**Comment by pmuens** [comment]
> ok all fixed I think.

Thanks! Let us know if you need any help 👍
