### PR TITLE
Fix support for EventBridge partner event sources

### LINKED ISSUE #6514: Amazon EventBridge not compatible with partner event sources
# This is a Bug Report

## Description

When deploying an AWS Lambda that is triggered by Amazon EventBridge using a partner event source (such as segment.com) a CloudFormation error occurs that the event bus cannot be found. This error appears to be caused by the way the event bus ARN is parsed by Serverless, detailed below.

Configuration:

```yaml
# ...
functions:
  # ...
  create-request:
    handler: functions/handler.createRequest
    events:
      - eventBridge:
          eventBus: 'arn:aws:events:us-east-1:XXXXXXXXXXXX:event-bus/aws.partner/segment.com/XXXXXXXXXX'
          pattern:
            source:
              - 'aws.partner/segment.com/XXXXXXXXXX'
            detail:
              event:
                - 'My Event'
              type:
                - 'track'
# ...
```

The deployment error that is displayed in the console is:

```
Failed to create resource. Event bus XXXXXXXXXX does not exist. See details in CloudWatch Log: 2019/08/06/[$LATEST][...].
```

In the current implementation, Serverless parses out the event bus ARN so it only includes the text after the last `/` character. In the case of partner sources, a portion of the ARN is omitted by this approach.

[Current implementation](https://github.com/serverless/serverless/blob/2c1315666a3bd25c6c744cb810b830dd6d248160/lib/plugins/aws/package/compile/events/eventBridge/index.js#L122) added in #6397 [here](https://github.com/serverless/serverless/commit/871b04e238b19bc9c57a9b430685ad157b52b98b#diff-8996f21d004732c3332fe2aeb726f6bbR122):

```javascript
eventBusName = EventBus.split('/').pop();
```

This implementation works for custom event busses formatted as follows:

```
event-bus/<bus_name>
```

However, it is not compatible with event busses from partner sources or any ARN containing additional `/` characters such as the Segment event bus in my example:

```
event-bus/aws.partner/segment.com/XXXXXXXXXX
```

The above ARN path is converted to `event-bus/XXXXXXXXXX` which does not exist.

Similar or dependent issues:

- #6363 - PR #6397 

## Additional Data

- **_Serverless Framework Version you're using_**: v1.49.0
- **_Operating System_**: Mac OS X 10.14.6
- **_Stack Trace_**:
- **_Provider Error messages_**:
- **_Forum Post_**: https://forum.serverless.com/t/amazon-eventbridge-partner-event-sources-error/9011

### PR DESCRIPTION
**Pull request by pmuens**
## What did you implement:

Closes #6514 

Fixes support for EventBridge partner event sources.

## How did you implement it:

Fix the arn parser.

## How can we verify it:

See [service config](https://github.com/serverless/serverless/issues/6514#issue-478071889) posted in the issue.

## Todos:

_**Note: Run `npm run test-ci` to run all validation checks on proposed changes**_

- [x] Write tests and confirm existing functionality is not broken.  
       **Validate via `npm test`**
- [x] Write documentation
- [x] Ensure there are no lint errors.  
       **Validate via `npm run lint-updated`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [x] Ensure introduced changes match Prettier formatting.  
       **Validate via `npm run prettier-check-updated`**  
       _Note: All reported issues can be automatically fixed by running `npm run prettify-updated`_
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

File: lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js [hunk 1]
```diff
@@ -2,7 +2,13 @@
...
 function getEventBusName(eventBus) {
   if (eventBus && eventBus.startsWith('arn')) {
-    return eventBus.split('/').pop();
+    const splittedEventBus = eventBus.split('/');
+    // if it's a custom event bus
+    if (splittedEventBus.length === 1) {
+      return splittedEventBus.pop();
+    }
+    // if it's a partner event bus
+    return splittedEventBus.slice(1).join('/');
```
Comment (medikoo) [inline lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js]: This implementation looks a bit weird. Technically it looks as if the goal is to simply strip leading token, if `eventBus` contains `/`, and otherwise pass it through, right?

If it indeed is the intention, wouldn't it be more straightforward to write it as:

```javascript
const separatorIndex = eventBus.indexOf('/'):
return (separateorIndex === -1) ? eventBus : eventBus.slice(separatorIndex + 1); 
```

?

File: lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js [hunk 2]
```diff
@@ -2,7 +2,13 @@
 
 function getEventBusName(eventBus) {
   if (eventBus && eventBus.startsWith('arn')) {
-    return eventBus.split('/').pop();
+    const splittedEventBus = eventBus.split('/');
+    // if it's a custom event bus
+    if (splittedEventBus.length === 1) {
```
Comment (medikoo) [inline lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js]: This will turn true only if there's no `/` in `eventBus` string. Is that a possible scenario?

Comment (pmuens) [reply lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js]: Good point. This should actually be `=== 2` since a custom event bus arn always includes only one `/`.

File: lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js (hunk 1 above)
Comment (pmuens) [reply lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js]: Yes, that's the intention. I'll update the PR in the next couple of minutes to include that change.

File: lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js [hunk 3]
```diff
@@ -2,7 +2,8 @@
 
 function getEventBusName(eventBus) {
   if (eventBus && eventBus.startsWith('arn')) {
-    return eventBus.split('/').pop();
+    const separatorIndex = eventBus.indexOf('/');
+    return separatorIndex === -1 ? eventBus : eventBus.slice(separatorIndex + 1);
```
Comment (medikoo) [inline lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js]: Looks good now.

Still, is this possible for event bus _arn_ to not contain `/` character?

In tests I don't see such case explored.

I'm thinking that maybe we should have here `eventBus.slice(eventBus.indexOf('/')+ 1)` unconditionally(?)

Comment (pmuens) [reply lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js]: Every `arn` has at least one `/` which is basically the separator for the name of the the event bus.

Comment (pmuens) [reply lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js]: Updating...
