### PR TITLE
Invoke local override env

### LINKED ISSUE #5096: sls invoke local should make it possible to override environment variables
# This is a (Feature Proposal)

## Description

`sls invoke local` should make it possible to override environment variables as command line arguments. For instance `sls invoke local -f myFunction --env myvar1=123 --env myvar2=foobar`

## Additional Data

* ***Serverless Framework Version you're using***:
1.27.1
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by robin-norwood**
## What did you implement:

Closes #5096 
 - sls invoke local should make it possible to override environment variables

## How did you implement it:

- Added --env option to `sls invoke local` to override environment vars in lib/plugins/invoke/invoke.js
  - Usage: --env NAME1=val1 --env NAME2=val2 ...

## How can we verify it:

Run:
`npm run test lib/plugins/invoke/`
`sls invoke local -f helloWorld ---env NAME1=val1 --env NAME2=val2`

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/plugins/invoke/invoke.js [hunk 1]
```diff
@@ -114,6 +119,13 @@ class Invoke {
 
     _.merge(process.env, defaultEnvVars);
 
+    // Turn zero or more --env options into an array
+    //   ...then split --env NAME=value and put into process.env.
+    Array.concat(this.options.env || []).forEach(itm => {
```
Comment (horike37) [inline lib/plugins/invoke/invoke.js]: Is it possible to use `lodash` library? We make a point of using it for consistency of code base when implementing if-check as possible as you can.

**Comment by robin-norwood** [comment]
I've added the docs - is this what you meant by using lodash? There may be a better way, but I'm afraid I'm not that familiar with lodash.

**Comment by softprops** [comment]
Very cool feature!

**Comment by robin-norwood** [comment]
@horike37 I think the coverage message is a rounding error in this case. Please do let me know if there are any other changes to make.

**Comment by horike37** [comment]
@robin-norwood 
Thank you for the updates 👍 
Looks perfect! merging...
