### PR TITLE
fix: prevent crash when packaging in parallel

### LINKED ISSUE #9565: Crash when packaging custom resource zip when two separate projects are packaging at the same time
If you use a tool like yarn workspaces to package multiple (unrelated) projects in parallel
you can get crash that looks like the following during the "Serverless: Installing dependencies for custom CloudFormation resources..." step.

```
➤ YN0000: [xxxx]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [yyyy]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [xxxx]:  
➤ YN0000: [xxxx]:  Error ---------------------------------------------------
➤ YN0000: [xxxx]:  
➤ YN0000: [xxxx]:  
➤ YN0000: [xxxx]:   Error: dest already exists.
➤ YN0000: [xxxx]:       at /var/lib/jenkins/workspace/xxxx-build_develop/node_modules/fs-extra/lib/move/move.js:41:31
➤ YN0000: [xxxx]:       at /var/lib/jenkins/workspace/xxxx-build_develop/node_modules/fs-extra/node_modules/universalify/index.js:22:54
➤ YN0000: [xxxx]:  
➤ YN0000: [xxxx]:      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

It has also been reported at https://github.com/serverless/serverless/issues/5002#issuecomment-737519692

The line that seems to be crashing is https://github.com/serverless/serverless/blob/ae67bf448950b199eaf2a0ec406349d63f60424c/lib/plugins/aws/customResources/generateZip.js#L21

I'm pretty sure the reason is that the ensureArtifact function is not thread safe. The custom CloudFormation resources are built once and cached in a shared folder in the home drive:

https://github.com/serverless/serverless/blob/ae67bf448950b199eaf2a0ec406349d63f60424c/lib/utils/ensureArtifact.js#L9

It seems that when there are multiple serverless instances building the artifacts and trying to cache them in the shared folder the crash happens.

To reproduce you need to make sure you delete the serverless cache directory at "$HOME/.serverless/artifacts/"

I'll create a test repo to reproduce the issue

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-issue-9565-repro-1

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  # These options should force a custom resource lambda to be packaged
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi: # Enables INFO level logging of API Gateway requests
      accessLogging: true
      fullExecutionData: false

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: v1/hello
          method: get

```

</details>

<details>
<summary><b><code>yarn build-all #(yarn sls package)</code> output</b></summary>

```
➤ YN0000: [serverless-issue-9565-repro-4]: Serverless: Deprecation warning: Detected unrecognized CLI options: "--verbose".
➤ YN0000: [serverless-issue-9565-repro-4]:             Starting with the next major, Serverless Framework will report them with a thrown error
➤ YN0000: [serverless-issue-9565-repro-4]:             More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
➤ YN0000: [serverless-issue-9565-repro-1]: Serverless: Deprecation warning: Detected unrecognized CLI options: "--verbose".
➤ YN0000: [serverless-issue-9565-repro-1]:             Starting with the next major, Serverless Framework will report them with a thrown error
➤ YN0000: [serverless-issue-9565-repro-1]:             More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
➤ YN0000: [serverless-issue-9565-repro-3]: Serverless: Deprecation warning: Detected unrecognized CLI options: "--verbose".
➤ YN0000: [serverless-issue-9565-repro-3]:             Starting with the next major, Serverless Framework will report them with a thrown error
➤ YN0000: [serverless-issue-9565-repro-3]:             More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
➤ YN0000: [serverless-issue-9565-repro-2]: Serverless: Deprecation warning: Detected unrecognized CLI options: "--verbose".
➤ YN0000: [serverless-issue-9565-repro-2]:             Starting with the next major, Serverless Framework will report them with a thrown error
➤ YN0000: [serverless-issue-9565-repro-2]:             More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
➤ YN0000: [serverless-issue-9565-repro-4]: Serverless: Packaging service...
➤ YN0000: [serverless-issue-9565-repro-4]: Serverless: Excluding development dependencies...
➤ YN0000: [serverless-issue-9565-repro-3]: Serverless: Packaging service...
➤ YN0000: [serverless-issue-9565-repro-3]: Serverless: Excluding development dependencies...
➤ YN0000: [serverless-issue-9565-repro-1]: Serverless: Packaging service...
➤ YN0000: [serverless-issue-9565-repro-1]: Serverless: Excluding development dependencies...
➤ YN0000: [serverless-issue-9565-repro-2]: Serverless: Packaging service...
➤ YN0000: [serverless-issue-9565-repro-2]: Serverless: Excluding development dependencies...
➤ YN0000: [serverless-issue-9565-repro-4]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [serverless-issue-9565-repro-3]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [serverless-issue-9565-repro-1]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:  Error ---------------------------------------------------
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:   Error: dest already exists.
➤ YN0000: [serverless-issue-9565-repro-3]:       at /var/home/seandawson/Development/work/ai-media/serverless-issue-9565-repro/node_modules/fs-extra/lib/move/move.js:41:31
➤ YN0000: [serverless-issue-9565-repro-3]:       at /var/home/seandawson/Development/work/ai-media/serverless-issue-9565-repro/node_modules/universalify/index.js:22:54
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:   Get Support --------------------------------------------
➤ YN0000: [serverless-issue-9565-repro-3]:      Docs:          docs.serverless.com
➤ YN0000: [serverless-issue-9565-repro-3]:      Bugs:          github.com/serverless/serverless/issues
➤ YN0000: [serverless-issue-9565-repro-3]:      Issues:        forum.serverless.com
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-3]:   Your Environment Information ---------------------------
➤ YN0000: [serverless-issue-9565-repro-3]:      Operating System:          linux
➤ YN0000: [serverless-issue-9565-repro-3]:      Node Version:              12.20.1
➤ YN0000: [serverless-issue-9565-repro-3]:      Framework Version:         2.44.0 (local)
➤ YN0000: [serverless-issue-9565-repro-3]:      Plugin Version:            5.2.0
➤ YN0000: [serverless-issue-9565-repro-3]:      SDK Version:               4.2.3
➤ YN0000: [serverless-issue-9565-repro-3]:      Components Version:        3.11.0
➤ YN0000: [serverless-issue-9565-repro-3]:  
➤ YN0000: [serverless-issue-9565-repro-2]: Serverless: Installing dependencies for custom CloudFormation resources...
➤ YN0000: Done in 3s 515ms
```

</details>

```
Framework Core: 2.44.0 (local)
Plugin: 5.2.0
SDK: 4.2.3
Components: 3.11.0
```

### PR DESCRIPTION
**Pull request by NoxHarmonium**
- Previously there was a race condition in ensureArtifact where if you were running multiple 'sls package' in parallel, two or more instances of serverless could notice that the custom resources package was missing and try and create it
- This meant that one of the serverless instances would 'win' the race and create it first. Then the other instances would crash because the file already existed
- Now each project gets its own cache folder and they can't conflict with each other, even if they are packaging in parallel
- Also implemented a safe move function that allows files to be renamed across filesystem boundaries

Closes: #9565

### CODE REVIEW

**Comment by NoxHarmonium** [comment]
FWIW I pulled in this branch into my test repo and tried to reproduce the issue.

Ran `yarn build-all` 20 times in a for loop and didn't get any failures so it looks good from that perspective

Branch with fix:
https://github.com/NoxHarmonium/serverless-issue-9565-repro/tree/test-fix

**Review by pgrzesik — COMMENTED** [review]
Thanks @NoxHarmonium - it looks good overall, however, I'd love to get @medikoo review first as he's more familiar with the issue

**Comment by NoxHarmonium** [comment]
Oh sorry about that, it seemed to be working for Node 12x but I didn't test v10/14 or on Windows. I'll have a look

File: lib/plugins/aws/customResources/generateZip.js [hunk 1]
```diff
@@ -5,20 +5,19 @@ const fse = require('fs-extra');
...
 const createZipFile = require('../../../utils/fs/createZipFile');
 const ensureArtifact = require('../../../utils/ensureArtifact');
+const safeMoveFile = require('../../../utils/fs/safeMoveFile');
 
 const srcDirPath = path.join(__dirname, 'resources');
 
-const artifactName = 'custom-resources.zip';
-
-module.exports = async () => {
+module.exports = async (artifactName) => {
```
Comment (medikoo) [inline lib/plugins/aws/customResources/generateZip.js:12]: What's the reasoning behind that change?

File: test/unit/lib/plugins/aws/customResources/generateZip.test.js [hunk 2]
```diff
@@ -0,0 +1,279 @@
...
+ */
+const sourcePath = getTmpDirPath();
+
+/**
+ * The full path to the generated artefact after is has been
+ * copied to the cache directory
+ */
+const cachedFile = join(cachePath, artefactName);
+
+describe('#generateZip()', () => {
```
Comment (medikoo) [inline test/unit/lib/plugins/aws/customResources/generateZip.test.js:78]: I think this should be the tests for `saveMoveFile` util specifically, can we convert it to it.

File: test/unit/lib/plugins/aws/customResources/generateZip.test.js [hunk 3]
```diff
@@ -0,0 +1,279 @@
...
+            's3/lib/bucket.js',
+            's3/lib/permissions.js',
+            'utils.js',
+          ]);
+        });
+      });
+    });
+  });
+
+  describe('when the temporary directory is on a different device to the cache directory', () => {
```
Comment (medikoo) [inline test/unit/lib/plugins/aws/customResources/generateZip.test.js:186]: Can we cover those two scenarios (1) when tmp dir is on different device (2) when tmp dir is not on different device, with reusable group of tests?

What I mean is something as:

```javascript
const testMove = (beforeEach) => {
    beforeEach(() => beforeEach());
    describe('when the file does not exist by the time the zip is generated, ... );
    ..
});

describe('when the temporary directory is not on a different device to the cache directory', () => {
  testMove(() => ...);
});

describe('when the temporary directory is on a different device to the cache directory', () => {
  testMove(() => ...);
});
```

**Review by medikoo — CHANGES_REQUESTED** [review]
@NoxHarmonium great thanks! That looks outstanding!

It looks very very good. I've just proposed some changes to how we test it. If I see correctly in `generateZip` we mostly test `safeMoveFile` logic. I think it's better if we simply prepare tests  for this util, and minimize content (large tests also affect maintance of Framework, which already is bloated).

Let me know what you think

File: lib/plugins/aws/customResources/generateZip.js (hunk 1 above)
Comment (NoxHarmonium) [reply lib/plugins/aws/customResources/generateZip.js:12]: It just makes testing a lot easier. I thought it wasn't a very invasive change so it was worth doing. I suppose I could try and do it with mocking or something instead but it is kind of useful to be able to specify the artifact name,

File: test/unit/lib/plugins/aws/customResources/generateZip.test.js (hunk 3 above)
Comment (NoxHarmonium) [reply test/unit/lib/plugins/aws/customResources/generateZip.test.js:182]: Oh of course! That makes sense. I'll make the change

File: test/unit/lib/plugins/aws/customResources/generateZip.test.js (hunk 2 above)
Comment (NoxHarmonium) [reply test/unit/lib/plugins/aws/customResources/generateZip.test.js:71]: Could I just extract the safeMoveFile parts to a separate test and simplify this test? Or are you thinking we get rid of this test altogether?

File: test/unit/lib/plugins/aws/customResources/generateZip.test.js (hunk 3 above)
Comment (NoxHarmonium) [reply test/unit/lib/plugins/aws/customResources/generateZip.test.js]: In my last commit where I extracted the saveMoveFile tests I factored out the test scenarios like this

File: test/unit/lib/plugins/aws/customResources/generateZip.test.js (hunk 2 above)
Comment (NoxHarmonium) [reply test/unit/lib/plugins/aws/customResources/generateZip.test.js:46]: I ended up simplifying the generateZip tests greatly and extracted the safeMoveFile tests into their own test file

**Comment by NoxHarmonium** [comment]
All comments addressed. Ready for re-review. Hopefully the build passes this time. :crossed_fingers:

**Comment by NoxHarmonium** [comment]
```
Error: EPERM: operation not permitted, rename 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpdirs-serverless\1691\b8347f9efaa05415\foo-bar.zip' -> 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpdirs-serverless\1691\4df22399035ac3e2\foo-bar.zip'
```
That is a strange issue that only seems to happen on Windows. I'll boot into Windows and see if I reproduce it there.

**Comment by NoxHarmonium** [comment]
Hmm its not looking good on Windows. I tried this on the REPL
```
Welcome to Node.js v14.17.1.
Type ".help" for more information.
> const fs = require('fs');
undefined
> const handle = fs.openSync(env.TEMP + "\\z.txt")
> const sourceFilePath = process.env.TEMP + "\\a.txt"
undefined
> const destFilePath = process.env.TEMP + "\\b.txt"
undefined
> fs.writeFileSync(sourceFilePath, "foo")
undefined
> fs.writeFileSync(destFilePath, "barr")
undefined
> const handle = fs.openSync(destFilePath, "r+")
undefined
> fs.renameSync(sourceFilePath, destFilePath)
Uncaught:
Error: EPERM: operation not permitted, rename 'C:\Users\Sean\AppData\Local\Temp\a.txt' -> 'C:\Users\Sean\AppData\Local\Temp\b.txt'
    at Object.renameSync (fs.js:794:3) {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'C:\\Users\\Sean\\AppData\\Local\\Temp\\a.txt',
  dest: 'C:\\Users\\Sean\\AppData\\Local\\Temp\\b.txt'
}
> fs.closeSync(handle)
undefined
> const handle2 = fs.openSync(destFilePath, "r")
undefined
> fs.renameSync(sourceFilePath, destFilePath)
Uncaught:
Error: EPERM: operation not permitted, rename 'C:\Users\Sean\AppData\Local\Temp\a.txt' -> 'C:\Users\Sean\AppData\Local\Temp\b.txt'
    at Object.renameSync (fs.js:794:3) {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'C:\\Users\\Sean\\AppData\\Local\\Temp\\a.txt',
  dest: 'C:\\Users\\Sean\\AppData\\Local\\Temp\\b.txt'
}
> fs.closeSync(handle2)
undefined
> fs.renameSync(sourceFilePath, destFilePath)
undefined
```

However, if I open the file in something like Notepad it doesn't prevent the file from getting overridden. I guess it depends on what flags the process that reads the file open it with.

The uploader opens the file with createReadStream with defaults to the "r" mode which would block the file from being overwritten on windows.
https://github.com/serverless/serverless/blob/38e463a8cdd324a80bf8ffbc678aae32b8ef106f/lib/plugins/aws/deploy/lib/uploadArtifacts.js#L53

```
> const ds = fs.createReadStream(destFilePath)
undefined
> fs.renameSync(sourceFilePath, destFilePath)
Uncaught:
Error: EPERM: operation not permitted, rename 'C:\Users\Sean\AppData\Local\Temp\a.txt' -> 'C:\Users\Sean\AppData\Local\Temp\b.txt'
    at Object.renameSync (fs.js:794:3) {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'C:\\Users\\Sean\\AppData\\Local\\Temp\\a.txt',
  dest: 'C:\\Users\\Sean\\AppData\\Local\\Temp\\b.txt'
}
```

So I guess that the problem might be unsolvable on Windows. It doesn't seem like the Windows filesystem allows a multiple processes to have handles to different versions of the same file. I'll have to have a think about it.

If it is unsolvable I could maybe skip that test on Windows or something.

**Comment by medikoo** [comment]
> If it is unsolvable I could maybe skip that test on Windows or something.

I understand that situation happens only if destination file exists?

If that's the case we probably should catch the error, remove the file at destination and rename again.

**Comment by NoxHarmonium** [comment]
It’s only if the destination file exists *and* the destination file is open
(e.g. serverless is uploading it). We won’t be able to delete it either
because the file is locked by the reader.

We could detect if the file is open and just skip writing it because if it
is open then some other process has already written it and started
uploading it.

 I hope that makes sense 😅

**Comment by medikoo** [comment]
> It’s only if the destination file exists *and* the destination file is open
(e.g. serverless is uploading it).

Ok. but in our case, there won't be a situation where we would have this file open, as in all cases it'll be just a _rename_ target (and never a _copy_ target). Right?

**Comment by NoxHarmonium** [comment]
> Ok. but in our case, there won't be a situation where we would have this file open, as in all cases it'll be just a rename target (and never a copy target). Right?

Oh I think I see now. Serverless doesn't upload the zip from the cache folder, it copies the zip out of the cache folder into the `.serverless` directory and uploads it from there. So yeah I think you're right that there wouldn't be a case where the cache file is opened by another process.

The main reason I made that test whether an open file could be overwritten was the comment on https://github.com/serverless/serverless/issues/9565#issuecomment-860463639 
> One note, we would have to confirm that it doesn't cause issues when attempting a rename when file is already open.

I can just remove that test if you don't think it is is necessary.

**Comment by medikoo** [comment]
> I can just remove that test if you don't think it is is necessary.

I think we can remove such test, as our process will not create such situation (even when multiple instances will be run at once)

**Comment by NoxHarmonium** [comment]
Ok great 👍 Hopefully the next build passes then 😉

**Comment by NoxHarmonium** [comment]
Oh oops, my fix didn't get pushed up last night for some reason. I've pushed it up now

File: test/unit/lib/utils/fs/safeMoveFile.test.js [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+ * The full path to destination where the file is being moved to
+ */
+const destinationFile = join(destinationPath, artefactName);
+
+/**
+ * The full path to the file that is being moved
+ */
+const sourceFile = join(sourcePath, artefactName);
+
+describe('#safeMoveFile()', () => {
```
Comment (medikoo) [inline test/unit/lib/utils/fs/safeMoveFile.test.js:66]: Let's put test file path as main title, it's a convention we use in all new tests, e.g.: https://github.com/serverless/serverless/blob/38e463a8cdd324a80bf8ffbc678aae32b8ef106f/test/unit/lib/configuration/read.test.js#L13
we just didn't took the effort to update old ones

File: test/unit/lib/utils/fs/safeMoveFile.test.js [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+      it('should write a file', async () => {
+        await safeMoveFile(sourceFile, destinationFile);
+
+        const exists = fse.existsSync(destinationFile);
+        expect(exists).to.be.true;
+        postAssertion();
+      });
+    });
+
+    describe('when the file already exists by the time the zip is generated', () => {
```
Comment (medikoo) [inline test/unit/lib/utils/fs/safeMoveFile.test.js:116]: This util is file type agnostic. So I guess better title name would be simply: `when file at target path already exists`

File: test/unit/lib/utils/fs/safeMoveFile.test.js [hunk 6]
```diff
@@ -0,0 +1,160 @@
...
+      beforeEach(async () => {
+        // Create an existing file that is at the destination
+        fse.ensureFileSync(destinationFile);
+        fse.writeFileSync(destinationFile, 'existing destination data');
+      });
+
+      describe('when the cached file is not open', () => {
```
Comment (medikoo) [inline test/unit/lib/utils/fs/safeMoveFile.test.js:123]: Let's remove this _describe_ wrap

File: test/unit/lib/utils/fs/safeMoveFile.test.js [hunk 7]
```diff
@@ -0,0 +1,160 @@
...
+        it('should overwrite the cached file with a valid zip file', async () => {
```
Comment (medikoo) [inline test/unit/lib/utils/fs/safeMoveFile.test.js:124]: Let's rename `should move file to target destination`

File: test/unit/lib/utils/fs/safeMoveFile.test.js [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+          const cachedData = fse.readFileSync(destinationFile).toString();
+          expect(cachedData).not.to.eq('existing destination data');
+
+          postAssertion();
+        });
+      });
+    });
+  };
+
+  describe('when the temporary directory is not on a different device to the cache directory', () => {
```
Comment (medikoo) [inline test/unit/lib/utils/fs/safeMoveFile.test.js:137]: Let's rename to `when file is moved in context of same device`

File: test/unit/lib/utils/fs/safeMoveFile.test.js [hunk 9]
```diff
@@ -0,0 +1,160 @@
...
+    runTestScenariosWithPostAssertion(() => {
+      // Happy path: Only rename is called
+      expect(renameStub).to.have.be.calledOnce;
+      expect(copyFileStub).to.not.have.been.called;
+      expect(unlinkStub).to.not.have.been.called;
+    });
+  });
+
+  describe('when the temporary directory is on a different device to the cache directory', () => {
```
Comment (medikoo) [inline test/unit/lib/utils/fs/safeMoveFile.test.js:146]: Let's rename to `when file is moved to different device`

File: test/unit/lib/utils/fs/safeMoveFile.test.js [hunk 10]
```diff
@@ -0,0 +1,160 @@
+'use strict';
+
+const fse = require('fs-extra');
+const sinon = require('sinon');
+const chai = require('chai');
+const { getTmpDirPath } = require('../../../../utils/fs');
```
Comment (medikoo) [inline test/unit/lib/utils/fs/safeMoveFile.test.js:6]: Let's rely on `@serverless/test/provision-tmp-dir` instead (note it's _async_).

(we're considering `getTmpDirPath` as deprecated, and it's scheduled to be removed)

File: test/unit/lib/utils/fs/safeMoveFile.test.js [hunk 11]
```diff
@@ -0,0 +1,160 @@
...
+  fakeCrossDeviceError.syscall = 'rename';
+  fakeCrossDeviceError.path = '/foo/bar';
+  fakeCrossDeviceError.dest = '/bar/baz';
+  return fakeCrossDeviceError;
+};
+
+/**
+ * The name of the file that will be moved
+ */
+const artefactName = 'foo-bar.zip';
```
Comment (medikoo) [inline test/unit/lib/utils/fs/safeMoveFile.test.js:41]: nit: typo, it rather should be `artifactName`

File: test/unit/lib/utils/fs/safeMoveFile.test.js [hunk 12]
```diff
@@ -0,0 +1,160 @@
...
+  let unlinkStub;
+
+  beforeEach(async () => {
+    renameStub = sinon.stub(fsp, 'rename');
+    copyFileStub = sinon.stub(fsp, 'copyFile');
+    unlinkStub = sinon.stub(fsp, 'unlink');
+    // Allow the fs calls to act as normal until we want to force the rename to fail
+    renameStub.callThrough();
+    copyFileStub.callThrough();
+    unlinkStub.callThrough();
```
Comment (medikoo) [inline test/unit/lib/utils/fs/safeMoveFile.test.js:78]: Ideally if in test we treat implementation as _black box_ and with above approach, we're technically confirming that implementation is calling given functions and how many times. We practised that in some parts and it appeared as very problematic for refactors (where we improve internals without affecting the outcome).

I propose, to change a bit methodology:
- Let's mock just `rename` (as without that, it's hard to (1) confirm rename is used for instant files move (2) emualate `'EXDEV'` error), and let all others `fs` functions work naturally
- In each test simply confirm that file at source path no longer exists, expected file exists at target path, `rename` was called to move it.

File: test/unit/lib/plugins/aws/customResources/generateZip.test.js (hunk 2 above)
Comment (medikoo) [reply test/unit/lib/plugins/aws/customResources/generateZip.test.js:46]: If we're about to create a test for this file, then I believe it should just confirm, that after resolution of `generateZip()`, at returned path we have an archive of which content reflects content of `resources` folder.

Confirming on other things, I believe is out of scope here, as it's handled by used utils (and not inline implementation) which have that tested in scope of their own unit tests.

Also if we follow that, we do not need to introduce any modifications to `generateZip` module

**Review by medikoo — COMMENTED** [review]
Great thanks @NoxHarmonium ! It looks way better now, however I've proposed few other improvements (simplications in general). Let me know what you think

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 4 above)
Comment (NoxHarmonium) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: No worries, updated!

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 5 above)
Comment (NoxHarmonium) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: Oh yeah, there would be a lot of these issues because I cut and paste the tests from the generateZip tests. Fixed!

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 6 above)
Comment (NoxHarmonium) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: Done!

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 7 above)
Comment (NoxHarmonium) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: Done!

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 8 above)
Comment (NoxHarmonium) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: Done!

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 9 above)
Comment (NoxHarmonium) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: Done!

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 10 above)
Comment (NoxHarmonium) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: Oh I see. I've switched that over, Should I use that `@serverless` prefix whenever I'm requiring something, rather than using the relative path?

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 11 above)
Comment (NoxHarmonium) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: Oh sorry, that's Australian spelling. Fixed!

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 12 above)
Comment (NoxHarmonium) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: That makes a lot of sense. I've updated the test to what you proposed.

**Comment by NoxHarmonium** [comment]
I've reverted my changes to the `generateZip` function and updated the tests to test it as a black box. Ready for re-review!

**Comment by NoxHarmonium** [comment]
Oh oops I've reverted too much of generateZip. Standby...

**Comment by NoxHarmonium** [comment]
Ok I've pushed up the fixed version now and it has been tested in https://github.com/NoxHarmonium/serverless-issue-9565-repro/tree/test-fix again just to be sure

**Comment by NoxHarmonium** [comment]
Ah right, looks like `path.resolve` is turning the path into a Windows path (backslashes) on Windows and globby doesn't like that. Might have to dual boot over to Windows again to fix that one :sweat_smile:

**Comment by NoxHarmonium** [comment]
Sorry about that, I tend to be quite Linux focused in my testing!
Now tested on Window/Linux and in https://github.com/NoxHarmonium/serverless-issue-9565-repro/tree/test-fix
:crossed_fingers:

File: test/unit/lib/utils/fs/safeMoveFile.test.js (hunk 10 above)
Comment (medikoo) [reply test/unit/lib/utils/fs/safeMoveFile.test.js]: `@serverless/test` simply points to modules in externally maintained [`@serverless/test`](https://www.npmjs.com/package/@serverless/test)

We should use paths naturally (per Node.js rules) if we want to rely on modules hosted in context of this package links should be local, and if we want to import external modules paths should start with names of the packages from which we want import from.

**Review by medikoo — APPROVED** [review]
Looks great now @NoxHarmonium. Thank you for your patience! It's a very valuable fix
