### PR TITLE
Fix schema for resource tags.

### LINKED ISSUE #8304: Incorrect schema for AWS tags
It was reported at Slack, that tags with format as below are rejected:

```yaml
tags:
    "mycompany:team": myteam
    "mycompany:service": ${self:service}
```

Current schema definition is:

https://github.com/serverless/serverless/blob/8c4d97211aa3dd4c41d9205a3ca0ccaab3564225/lib/plugins/aws/provider/awsProvider.js#L364-L369

and indeed _key_ pattern seems to not allow `:`, which seems not correct. Also I think _value_ can be any string (at least I do not see any restriction documented on AWS side), so probably `pattern` should be removed there.

I'd follow closely restrictions as described here: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Tag.html

(cc @fredericbarthelet )

### PR DESCRIPTION
**Pull request by dashmug**
AWS allows for resource tags to have colons in them. In fact, they use it themselves for their reserved tags and they recommend their use in their [best practices](https://d1.awsstatic.com/whitepapers/aws-tagging-best-practices.pdf). Serverless config schema validation should also allow for it.

The schema validation is based on the documentation in this page: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Tag.html.

This PR closes #8304.

### CODE REVIEW

File: lib/plugins/aws/provider/awsProvider.js [hunk 1]
```diff
@@ -356,9 +356,8 @@ class AwsProvider {
           awsResourceTags: {
             type: 'object',
             patternProperties: {
-              '^(?!aws:)[\\w./=+-]{1,128}$': {
+              '^(?!aws:)[\\w./=+-:]{1,128}$': {
```
Comment (medikoo) [inline lib/plugins/aws/provider/awsProvider.js:359]: I think we need to move `-` so it's listed last, otherwise `+-:` implies a _range_

**Review by medikoo — CHANGES_REQUESTED** [review]
Thank you @dashmug, it looks great! Still I think I've spotted one issue in pattern, let me know

File: lib/plugins/aws/provider/awsProvider.js (hunk 1 above)
Comment (dashmug) [reply lib/plugins/aws/provider/awsProvider.js]: Thanks @medikoo. I've updated it.

**Review by medikoo — APPROVED** [review]
Thank you @dashmug !
