### PR TITLE
Explicitly Added LogGroups as CF Resources

### LINKED ISSUE #2126: Feature Proposal: Create Log Groups for lambda functions as part of Cloudformation
# This is a Feature Proposal

## Description
When creating the functions in the cloudformation template it would be ideal if the relevant log groups were created as well. 

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

This would allow for setting a retention policy on the logs to help with costs. It also would allow for hooking up of a subscription to handle alerting and processing of logs. This is hard at the moment due to the fact that the log groups are only created after the lambda has executed once. It will also mean the log groups can be cleaned up as part of `sls remove` where they are being left there currently clogging up the interface.
* If there is additional config how would it look

```
{
    "Type" : "AWS::Logs::LogGroup",
    "Properties" : {
        "LogGroupName" : "/aws/lambda/${FunctionName}"
    }
}
```
It would be simple to add it around https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/functions/index.js#L170 

## Additional Data

* ***Serverless Framework Version you're using***: Master
* ***Operating System***: Win
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by eahefnawy**
## What did you implement:
Pulled @erikerikson branch 😊 

Closes #2126 and #1944

## How can we verify it:

Run `serverless deploy --noDeploy` Using this config:

```yml
service: serverless-logging-core-resource

provider:
  name: aws
  cfLogs: true

functions:
  hello:
    handler: handler.hello
```
And check the "update" CF template. You'll see that there's a new LogGroup resource for each function. You can also do the following for actual testing:

- deploy
- invoke
- log
- remove => make sure the resource group was removed from AWS console

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

File: lib/plugins/aws/deploy/lib/mergeIamTemplates.js [hunk 1]
```diff
@@ -36,16 +36,76 @@ module.exports = {
...
+          .Resource = `arn:aws:logs:${this.options.region}:*:*`;
+
+        this.serverless.service.provider.compiledCloudFormationTemplate.Resources
+          .IamPolicyLambdaExecution
+          .Properties
+          .PolicyDocument
+          .Statement[1]
+          .Resource = `arn:aws:logs:${this.options.region}:*:*`;
+
+        const warningMessage = [
```
Comment (pmuens) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: This `warningMessage` should be updated as it looks like this (formatting, comma and fullstops):

bildschirmfoto 2016-10-24 um 13 35 16

Furthermore I would change `CF` to `CloudFormation` to reduce cognitive load.

File: lib/plugins/aws/deploy/tests/mergeIamTemplates.js [hunk 2]
```diff
@@ -121,4 +121,134 @@ describe('#mergeIamTemplates()', () => {
...
+            LogGroupName: `/aws/lambda/${functionName}`,
+          },
+        }
+      );
+    });
+  });
+
+  it('should update IamPolicyLambdaExecution with a logging resource for the function', () => {
+    awsDeploy.serverless.service.provider.cf_logs = true;
+    const service = awsDeploy.serverless.service; // avoid 100 char lines below
```
Comment (pmuens) [inline lib/plugins/aws/deploy/tests/mergeIamTemplates.js]: Could be rewritten like this so that it's consistent with our existing codebase:

```
awsDeploy.serverless.service
  .functions = { foo: bar };
```

File: lib/plugins/aws/deploy/tests/mergeIamTemplates.js [hunk 3]
```diff
@@ -121,4 +121,134 @@ describe('#mergeIamTemplates()', () => {
...
+      func0: {
+        handler: 'func.function.handler',
+        name: 'func0',
+      },
+      func1: {
+        handler: 'func.function.handler',
+        name: 'func1',
+      },
+    };
+    const f = service.functions; // avoid 100 char lines below
```
Comment (pmuens) [inline lib/plugins/aws/deploy/tests/mergeIamTemplates.js]: Same rewrite proposal can be applied here.

File: lib/plugins/aws/deploy/tests/mergeIamTemplates.js [hunk 4]
```diff
@@ -121,4 +121,134 @@ describe('#mergeIamTemplates()', () => {
...
+        .PolicyDocument
+        .Statement[1]
+        .Resource
+      ).to.deep.equal([{ 'Fn::Join': [':', [{ 'Fn::GetAtt': [normalizedName, 'Arn'] }, '*']] }]);
+    });
+  });
+
+  it('should update IamPolicyLambdaExecution with each function\'s logging resources', () => {
+    awsDeploy.serverless.service.provider.cf_logs = true;
+    const service = awsDeploy.serverless.service; // avoid 100 char lines below
```
Comment (pmuens) [inline lib/plugins/aws/deploy/tests/mergeIamTemplates.js]: Same rewrite proposal can be applied here.

File: lib/plugins/aws/deploy/tests/mergeIamTemplates.js [hunk 5]
```diff
@@ -121,4 +121,134 @@ describe('#mergeIamTemplates()', () => {
...
+      func0: {
+        handler: 'func.function.handler',
+        name: 'func0',
+      },
+      func1: {
+        handler: 'func.function.handler',
+        name: 'func1',
+      },
+    };
+    const f = service.functions; // avoid 100 char lines below
```
Comment (pmuens) [inline lib/plugins/aws/deploy/tests/mergeIamTemplates.js]: Same rewrite proposal can be applied here.

File: lib/plugins/aws/deploy/lib/mergeIamTemplates.js [hunk 6]
```diff
@@ -36,16 +36,76 @@ module.exports = {
...
-        .IamPolicyLambdaExecution
-        .Properties
-        .PolicyDocument
-        .Statement[0]
-        .Resource = `arn:aws:logs:${this.options.region}:*:*`;
-
       _.merge(this.serverless.service.provider.compiledCloudFormationTemplate.Resources,
         iamPolicyLambdaExecutionTemplate);
 
+      if (!this.serverless.service.provider.cf_logs) {
```
Comment (pmuens) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: I would like to change this to `cfLogs` or `cloudFormationLogs` or something similar (`camelCase`) as we're using this type of convention throughout the whole `serverless.yml` file and this would be the only exception.

File: lib/plugins/aws/deploy/lib/mergeIamTemplates.js (hunk 1 above)
Comment (eahefnawy) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: done

**Comment by eahefnawy** [comment]
@pmuens I've pushed your suggested changes along with docs for backward compatibility

This PR is G2M from my side at this point.

File: lib/classes/Service.js [hunk 7]
```diff
@@ -58,9 +58,9 @@ class Service {
         if (!serverlessFile.provider) {
           throw new SError('"provider" property is missing in serverless.yml');
         }
-        if (!serverlessFile.functions) {
-          throw new SError('"functions" property is missing in serverless.yml');
-        }
+        // if (!serverlessFile.functions) {
```
Comment (pmuens) [inline lib/classes/Service.js]: Please remove it not in use.

**Comment by pmuens** [comment]
GTM from my side 🎉  Really great feature!

**Comment by eahefnawy** [comment]
Thanks tons @erikerikson for your great work here 😊
