### PR TITLE
Fix queue url generation for redrivePolicy in SNS events.

### LINKED ISSUE #7276: Redrive Policy not properly referencing queue
## Description

Recentely, I have been able to test serverless 1.62 which includes the option to use redriverPolicy for sns events. However, when I submited a PR for that feature, I overlooked the param specificacion format on the queuePolicy that is created. To be more specific, the Resource part needs to be an ARN but the Queue needs to be defined by URL.
````
Resource: event.sns.redrivePolicy.deadLetterTargetArn -> should be a Fn::GetAtt [deadLetterTarget, Arn]
````

````
Queues: [event.sns.redrivePolicy.deadLetterTargetArn], -> should be a Ref: deadLetterTarget
````

This translates in using GetAtt Arn for one thing and Ref for the other, while now both use the ARN (which leads to deployment errors). Also, the documentation says that Ref can be used which is wrong since it would only provide one of the needed values.

In this case, what I think would be easier is just to pass the queue resource name to the sns event redrivepolicy section (like myDLQ), and build the GetAtt and Ref inside.
Other solutions would involve more complex things like trying to generate the url from the Arn. I'm open to whatever you think is best and will start a PR as soon as there's consensus

#7239

### PR DESCRIPTION
**Pull request by tcastelli**
Fixes the error introduced in #7239 by not generating the queue Url and allowing to pass Ref as an input. Now the deadLetterTargetArn can be either defined as a string or using Fn::GetAtt, and the url will be generated automatically from that.

Still needs more testing but can be reviewed for structural decissions

Closes #7276

### CODE REVIEW

**Comment by tcastelli** [comment]
I have tested this locally with one of my projects and I could deploy it sucessfully after this fix :+1:

File: lib/plugins/aws/lib/naming.js [hunk 1]
```diff
@@ -335,6 +335,11 @@ module.exports = {
   getTopicLogicalId(topicName) {
     return `SNSTopic${this.normalizeTopicName(topicName)}`;
   },
+  getTopicDLQPolicyLogicalId(functionName, topicName) {
```
Comment (tcastelli) [inline lib/plugins/aws/lib/naming.js]: I've created this, since the previously generated names for the queue policy looked wrong (ere referencing eventMapping) since they were designed for a Queue and not for a QueuePolicy

File: lib/plugins/aws/package/compile/events/sns/index.js [hunk 2]
```diff
@@ -225,10 +225,30 @@ class AwsCompileSNSEvents {
...
+
+              let queueUrl;
+              const arnDefinition = event.sns.redrivePolicy.deadLetterTargetArn;
+              if (typeof arnDefinition === 'object' && arnDefinition['Fn::GetAtt']) {
+                queueUrl = { Ref: arnDefinition['Fn::GetAtt'][0] };
+              } else if (typeof arnDefinition === 'string' && arnDefinition.startsWith('arn:')) {
+                // obtain queue url from an arn like arn:aws:sqs:us-east-2:444455556666:queue1
+                const queueParts = arnDefinition.split(':');
+                const partsLength = queueParts.length;
+                queueUrl = `https://sqs.${queueParts[partsLength - 3]}.amazonaws.com/${
```
Comment (maafk) [inline lib/plugins/aws/package/compile/events/sns/index.js]: Rather than `amazonaws.com`, can you take advantage of [`AWS::URLSuffix`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-urlsuffix)?

Something like
```javascript
queueUrl = {
  'Fn::Join': [
    '',
    `https://sqs.${queueParts[partsLength - 3]}.`,
    { Ref: 'AWS::URLSuffix' },
    `/${queueParts[partsLength - 2]}/${queueParts[partsLength - 1]}`
  ]
};

```

Comment (tcastelli) [reply lib/plugins/aws/package/compile/events/sns/index.js]: done!

**Comment by tcastelli** [comment]
Since this implementation was lacking the option to use any arn defined without GetAtt or a string, I've added the option to also define the url for the queue, so now people can also use Fn:ImportValue or Fn::Join

File: docs/providers/aws/events/sns.md [hunk 3]
```diff
@@ -168,3 +184,19 @@ resources:
...
+  dispatcher:
+    handler: dispatcher.handler
+    events:
+      - sns:
+          topicName: dispatcher
+          redrivePolicy:
+            deadLetterTargetArn:
+              'Fn::ImportValue': MyShared-DLQArn
+            deadLetterTargetUrl:
+              'Fn::ImportValue': MyShared-DLQUrl
```
Comment (medikoo) [inline docs/providers/aws/events/sns.md]: Is there a case, where complete configuration must include a URL?

I wonder why do we allow to provide both ARN and URL? Is ARN not enough for some cases?

Comment (tcastelli) [reply docs/providers/aws/events/sns.md]: If you pass an Arn with ImportValue or a Join for example(i had to use importvalue in one of my projects), then I haven't found a reliable way to generate the url from that Arn since it could use a different region/name than your current deployment.
Maybe I am missing some CloudFormation function that allows to do that?

Comment (tcastelli) [reply docs/providers/aws/events/sns.md]: I think this naming convention could be a little confusing when trying to specify the arn with Fn::Join. 
I would prefer `deadLetterTargetImport` to be named something else where you can use any way of defining your arn and your url. What about `deadLetterTargetCustomDef`?
so then the arn and url fields inside can be specified with any cloudformation function like Join Import or whatever else

Comment (medikoo) [reply docs/providers/aws/events/sns.md]: > I think this naming convention could be a little confusing when trying to specify the arn with Fn::Join.

What would be the use case for user wanting to use `Fn::Join` when having options as above? I believe in such case user should just reference resource id via `deadLetterTargetRef: myDLQ` (?)

> to be named something else where you can use any way of defining your arn and your url. 

To avoid unnecessary complexity in handling that, and to make things more straightforward, I think it's better to lay out things more to the point as:
- If you want to reference via ARN, use `deadLetterTargetArn`
- If you want to reference by pointing an existing resource in same stack, use `deadLetterTargetRef`
- If you want to reference by pointing an output from other stack, use `deadLetterTargetImport`

Do you think it won't cover all cases?

Comment (tcastelli) [reply docs/providers/aws/events/sns.md]: Well the Fn::Join case could be useful when generating the arn from different variables, but well I don't want to argue that much since most of the cases will be covered anyway. I'll updtae the PR asap

**Comment by tcastelli** [comment]
Just updated the PR with latest changes requested. Please take a look when you can @medikoo
