### PR TITLE
fix(esbuild): include package.json in artifact if type is module

### LINKED ISSUE #12706: [V4] Typescript with ESM support
### Issue description

I've created a test project using typescript. If I don't enable ESM support, everything is working fine. I need ESM, so I've added `"type": "module"` to my `package.json` file.

After doing that, I have problems when executing the code locally, while the deployment works fine. I understand that _esbuild_ is not being used locally, from what I've read _ts-node_ is being used. Is there any way to replace that with _tsx_? I've had way better results with that. I'm fine using either, as long as ESM is supported.

The code:
```
export const hello = async (event: any) => {
  return {
    statusCode: 200,
    body: JSON.stringify({
      message: "Go Serverless v4! Your function executed successfully!",
    }),
  };
};
```

- When running `serverless invoke -f hello` (after deploying):
```
{
    "statusCode": 200,
    "body": "{\"message\":\"Go Serverless v4! Your function executed successfully!\"}"
}
```

- When running `serverless invoke local -f hello`:
```
✖ ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/gus/Projects/test/.serverless/build/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/gus/Projects/test/.serverless/build/handler.js:24:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadModule (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:851:9938)
    at async AwsInvokeLocal.invokeLocalNodeJs (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:851:9253)
    at async PluginManager.runHooks (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:9296)
    at async PluginManager.invoke (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:10066)
    at async PluginManager.run (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:10790)
    at async Serverless.run (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:861:10442)
    at async runFramework (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:909:2314)


✖ Exception encountered when loading /home/gus/Projects/test/.serverless/build/handler
ServerlessError2: Exception encountered when loading /home/gus/Projects/test/.serverless/build/handler
    at AwsInvokeLocal.invokeLocalNodeJs (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:851:9362)
    at async PluginManager.runHooks (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:9296)
    at async PluginManager.invoke (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:10066)
    at async PluginManager.run (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:10790)
    at async Serverless.run (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:861:10442)
    at async runFramework (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:909:2314)
    at async route (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:920:16046)
    at async Object.run2 [as run] (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:920:16444)
    at async run3 (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:920:17704)
```

- When running `serverless run dev` (after deploying, I call the endpoint):
```
→ λ hello ── aws:apigateway:v2:get:/
─ ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/gus/Projects/test/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/gus/Projects/test/.serverless/build/handler.js:24:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importFunction (file:///home/gus/.serverless/releases/4.1.16/package/lib/plugins/aws/dev/local-lambda/runtime-wrappers/node.js:116:28)
    at async file:///home/gus/.serverless/releases/4.1.16/package/lib/plugins/aws/dev/local-lambda/runtime-wrappers/node.js:185:21
← λ hello
```

I'd appreciate any help. Thanks in advance.

### Context

# Service Overview
- Serverless Framework Version: 4.1.16
- Service Path: /home/gus/Projects/test
- Service Config File: serverless.yml
- Service Name: test
- Service App: test
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1
- Command: invoke --function hello

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gdlin
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: test
# "service" is the name of this project. This will also be added to your AWS resource names.
service: test
provider:
  name: aws
  runtime: nodejs20.x
  profile: test
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
```

### PR DESCRIPTION
**Pull request by eahefnawy**
Closes #12706

### CODE REVIEW

File: lib/plugins/esbuild/index.js [hunk 1]
```diff
@@ -314,6 +314,22 @@ class Esbuild {
...
+    // If the user explicitly set the type to "module" then we need to set the output format to ESM
+    if (packageJson.type === 'module') {
+      defaultConfig.format = `esm`
+
+      // We will also need to make sure we include the package.json in the build
+      // for AWS Lambda to know that it is an ESM module
+      this.serverless.service.package = this.serverless.service.package || {}
+      this.serverless.service.package.patterns = [
+        ...(this.serverless.service.package.patterns || []),
+        'package.json',
```
Comment (Mmarzex) [inline lib/plugins/esbuild/index.js:329]: We shouldn't be doing it this way.

We already prepare a package.json to include in the build [here](https://github.com/serverless/serverless/blob/main/lib/plugins/esbuild/index.js#L858), we should instead make sure this is setup and included correctly.

**Review by Mmarzex — CHANGES_REQUESTED** [review]

File: lib/plugins/esbuild/index.js (hunk 1 above)
Comment (eahefnawy) [reply lib/plugins/esbuild/index.js]: There was nothing wrong in the `preparePackageJson` function. It gets added to the build directory as expected, but it just wasn't being added to the zip file. I updated the PR with a fix in the zip function.

**Review by czubocha — APPROVED** [review]

**Review by Mmarzex — APPROVED** [review]
