### PR TITLE
Fix tagging API Gateway stage fails if tag contains special characters like space

### LINKED ISSUE #6133: API Gateway tags setting Stage Variables not Tags
# This is a Bug Report
## Description

* What went wrong?
Updated to new version of serverless. Deploying failed due to it trying to put our tags that contain spaces into stack variables on api gateway.
* What did you expect should have happened?
api gateway tags to be set not stack variables for tags
* What was the config you used?
```
provider:
  stackTags:
    Project ID: xxxxx
```
* What stacktrace or error message from your provider did you see?
```
Serverless Error ---------------------------------------

 Invalid stage variable name: Project ID.  Please use names with only word characters.
```
Similar or dependent issues:
* PR #5851

## Additional Data

* ***Serverless Framework Version you're using***: tried with 1.42.2 and 1.42.3
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### LINKED ISSUE #6170: problem with tags including german umlauts
I tried to add a tag with an german umlaut but it wasn't working, serverless said:

Bildschirmfoto 2019-05-24 um 10 59 41

If i add this tag directly in the lambda-function it is working.

Bildschirmfoto 2019-05-24 um 11 02 56

Every sign i'm able to set in a tag-value should be usable in the serverless.yml
Bildschirmfoto 2019-05-24 um 11 12 49

### PR DESCRIPTION
**Pull request by exoego**
## What did you implement:

Closes #6133
Closes #6170

## How did you implement it:

Use [tagResource](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#tagResource-property) and [untagResource](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#untagResource-property) that can use tag containing space. 

## How can we verify it:

The following should deploy successfully where API GW stage are tagged with `bar bar` & `foo`.

```yaml
service: fix-6133

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  tags:
    foo: XXX
  stackTags:
    bar bar: ZZZ

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
```

## Todos:

- [x] Write tests
- N/A Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES 
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by exoego** [comment]
@shredder2500 is [trying to invetsitage issue deeply](https://github.com/serverless/serverless/issues/6133#issuecomment-492437634), so please hold review 🙇

**Comment by exoego** [comment]
It seems that API Gateway console allow us to tag containing space, so there must be API to update tag that does not rely on stage variable.
I will try [tagResource](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#tagResource-property) API in SDK

**Comment by exoego** [comment]
@pmuens 
I think the issue is fixed without breaking change.

**Comment by shredder2500** [comment]
@exoego 
Tested with our app and is working. Thanks for fixing this!

File: lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js [hunk 1]
```diff
@@ -198,32 +202,43 @@ function handleLogs() {
...
+  const tagsMerged = _.mapValues(Object.assign({}, provider.stackTags, provider.tags),
+      v => String(v));
+  const currentTags = this.apiGatewayStageState.tags || {};
+  const tagKeysToBeRemoved = Object.keys(currentTags)
+    .filter(currentKey => !_.isString(tagsMerged[currentKey]));
+
+  const restApiId = this.apiGatewayRestApiId;
+  const stageName = this.options.stage;
+  const region = this.options.region;
+  const resourceArn = `arn:aws:apigateway:${region}::/restapis/${restApiId}/stages/${stageName}`;
```
Comment (pmuens) [inline lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js]: Does this work with a custom API name? (see `apiName` in https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/serverless.yml.md).

File: lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js [hunk 2]
```diff
@@ -198,32 +202,43 @@ function handleLogs() {
...
-  }));
-  if (tagsToCreate) {
-    tagsToCreate.forEach((tag) => {
-      const operation = { op: 'replace', path: `/variables/${tag.key}`, value: tag.value };
-      this.apiGatewayStagePatchOperations.push(operation);
+  const tagsMerged = _.mapValues(Object.assign({}, provider.stackTags, provider.tags),
+      v => String(v));
+  const currentTags = this.apiGatewayStageState.tags || {};
+  const tagKeysToBeRemoved = Object.keys(currentTags)
+    .filter(currentKey => !_.isString(tagsMerged[currentKey]));
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js]: Style suggestion: More to the point could be `tagsMerged.hasOwnProperty(currentKey)`, or if we created `tagsMerged` literal with `Object.create(null)` simply just `tagsMerged[currentKey]`.

(also`tagsMerged`could be setup as `Map`, still I get it turns cumbersome when we cannot rely on `Object.entries` and typical array utils, which are not out of a box available for maps)

File: lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js [hunk 3]
```diff
@@ -198,32 +202,43 @@ function handleLogs() {
...
-    if (tagsToRemove) {
-      tagsToRemove.forEach((tagKey) => {
-        const operation = { op: 'remove', path: `/variables/${tagKey}` };
-        this.apiGatewayStagePatchOperations.push(operation);
-      });
-    }
+  if (!_.isEqual(currentTags, tagsMerged) && _.size(tagsMerged) > 0) {
+    this.apiGatewayTagResourceParams.push({
+      resourceArn,
+      tags: tagsMerged,
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js]: Why not difference of `tagsMerged` against `currentTags` ?

Comment (exoego) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js]: Because tagResouce API can ignore unchanged keys, so no need to filter out unchanged keys from `tagsMerged`, as far as I tested.

File: lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js (hunk 2 above)
Comment (exoego) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js]: `~.hasOwnProperty` since it is forbidden by eslint rule `no-prototype-builtins`

We should not use `tagsMerged[currentKey]` to filter keys to be removed.
Because if tag value is a string `'0'` or `''` which is falsy, it wont be filtered.

`Object.assign` is used widely in codebase, since `Map` was not available on node.js prior to v4.
So I don't think there is a strong to choose `Map`. Will refactor in separate PR.

File: lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js (hunk 3 above)
Comment (medikoo) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js]: Ok, indeed no harm in that

File: lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js (hunk 2 above)
Comment (medikoo) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js]: > Unfortunately ~.hasOwnProperty cannot be used since it is forbidden by eslint rule no-prototype-builtins.

Yes, this rule is meant to address cases when we deal with externally passed objects, which are not guaranteed to have `.hasOwnProperty` (as e.g. ones created with `Object.create(null)`.

Here's it's not the case, but lint rule is not smart enough to detect that, so usually that's addressed with notation as:

```javascript
const hasOwnProperty = Object.prototype.hasOwnProperty;
...
hasOwnProperty.call(obj, propertyName)
```

Still here we could be cleaner if we create an object with `Object.create(null)`, as then we can simply rely on existence (or `currentKey in tagsMerged` if for some reason we care for `''`)

> We should not use tagsMerged[currentKey] to filter keys to be removed.
Because if a tag value is a string '0' or '' which is falsy, it wont be filtered.
So I used _.isString that does not care the content of string.

It's only `''` that's falsy and would be filtered. Still assuming we want to take in that as well, we can simply rely on `currentKey in tagsMerged`.

> So I don't think there is a strong preferrence to choose Map. Will refactor in separate PR.

Yes, no need, it was only a suggestion.

**Comment by joe-keane** [comment]
@exoego great job here! 
Took it for a spin and was able to get stackTags added and updated, with or without spaces.

File: lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js (hunk 1 above)
Comment (pmuens) [reply lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js]: Makes sense :+1:

Just want to be 100% sure that we don't re-introduce any regression here.

**Comment by shredder2500** [comment]
@pmuens 
> Unfortunately the Stage Variables are not updated.  

I dont think this should change Stage Variables as those are not tags. Api gateway has tags and this PR is updating it to set tags not stage variables. 

I have tested this branch with an already deployed service and it is working as I would expect it to

**Comment by joe-keane** [comment]
@pmuens Same with me as @shredder2500, a service deployed got the tags added or removed accordingly. I also never expected stackTags or tags to be saved as Stage Variables.

**Comment by pmuens** [comment]
@joe-keane @shredder2500 Thanks for the follow-up. I guess I got a little bit confused here.
