### PR TITLE
BREAKING-CHANGE Preserver whitespace in variable fallback

### LINKED ISSUE #5558: schedule from file with default value removes space
# This is a Bug Report

## Description

* What went wrong?
I ran `serverless deploy --stage custom`. The serverless.yml refers to files like `serverless.prod.config.json` depending on the stage name.
I have a variable schedule, it's running faster on acceptance than on prod.
Because I was using a `custom` stage there is no `serverless.custom.config.json` and all the settings fall back to their default in serverless.yml.

from serverless.yml:
```
  applereceiptstoupdate:
    handler: src/handler.appleFindReceiptsInNeedOfUpdate
    timeout: 10
    events:
      # In the apple sandbox time runs faster, so we need to check the apple receipts faster.
      - schedule: ${file(./serverless.${self:provider.stage}.config.json):AppleReciptsToUpdateSchedule, 
"rate(3 hours)"}
```

The following updatestack.json was produced:
```
    "ApplereceiptstoupdateEventsRuleSchedule1": {
      "Type": "AWS::Events::Rule",
      "Properties": {
        "ScheduleExpression": "rate(3hours)",
        "State": "ENABLED",
        "Targets": [
          {
            "Arn": {
              "Fn::GetAtt": [
                "ApplereceiptstoupdateLambdaFunction",
                "Arn"
              ]
            },
            "Id": "applereceiptstoupdateSchedule"
          }
        ]
      }
    },
```
Note that the space between `3` and `hours` disappeared for the schedule.
This results in an error when pushing the stack to aws.

* What did you expect should have happened?
The space should not have been removed.

* What stacktrace or error message from your provider did you see?
```
  An error occurred: ApplereceiptstoupdateEventsRuleSchedule1 - Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: ...).
```
## Additional Data
When deploying from a stage that does have a file with AppleReciptsToUpdateSchedule in it, the `rate(3 hours)` is correctly used...

* ***Serverless Framework Version you're using***: 1.34.1
* ***Operating System***: macOS 10.14.1
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by exoego**
## What did you implement:

Closes #5558 

## How did you implement it:

Remove whitespace cleaning (`.replace(/\s/g, '');`) which seems unnecessary.

I am suprised that removing it break nothing.
I am not sure that it is essentially unnecessary...

## How can we verify it:
`npm test`

## Todos:

- [x] Write tests
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

File: lib/classes/Variables.js [hunk 1]
```diff
@@ -268,7 +268,7 @@ class Variables {
     return match.replace(
       this.variableSyntax,
       (context, contents) => contents.trim()
-    ).replace(/\s/g, '');
+    );
```
Comment (dschep) [inline lib/classes/Variables.js]: I had to dive deep in the `git blame` rabbit hole.. but it seems you initially added the whitespace removal @eahefnawy. What are you thoughts on this PR?

Comment (eahefnawy) [reply lib/classes/Variables.js]: If I remember correctly, this is meant to normalize variables written like this `${opt: foo}`. I think the real solution would be to NOT remove white spaces from the literal fallback only, but keep it for variables. This might be easier said than done though...

Overall, imo the issue raised is more severe than cleaning the variable itself. So I wouldn't oppose losing that tiny functionality.
