### PR TITLE
BREAKING - Replace IamPolicyLambdaExecution with inline policies and added ManagedPolicyArns to fix VPC permissions

### LINKED ISSUE #1786: VPC not created correctly in 1.0.0-beta
##### Serverless Framework Version:

1.0.0-beta
##### Operating System:

Windows/Cygwin. (Sorry! My real computer died in a flood localized to my kitchen table and the replacement hasn't arrived yet. This hurts me more than it hurts you.)
##### Expected Behavior:

specifying `vpc` for either under a function or under `provider` should set the VPC correctly in the AWS Lambda console 
##### Actual Behavior:

It doesn't. When I add the relevant stuff (see below) and `sls deploy`, I get an error saying ````  Serverless Error ---------------------------------------

``````
 An error occurred while provisioning your cloudformation:
 The following resource(s) failed to update: [myfunctionname].````
``````
##### Stack-Trace (Optional):

```
$ SLS_DEBUG=true sls deploy
Serverless: Zipping service...
Serverless: Removing old service versions...
Serverless: Uploading .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...

  Serverless Error ---------------------------------------

     An error occurred while provisioning your cloudformation:
     The following resource(s) failed to update: [myfunctionname].


  Stack Trace --------------------------------------------

ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to update: [myfunctionname].
    at C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\lib\updateStack.js:56:33
    at tryCatcher (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The config in my `serverless.yml` looks like this, whether under `provider` or under `functions`.`myfunctionname`:

```
    vpc:
      securityGroupIds:
        - sg-abcdefg
      subnetIds: 
        - subnet-abcdefg1
        - subnet-abcdefg2
        - subnet-abcdefg3
        - subnet-abcdefg4
```

A possible hint: when I use the IAM role created by serverless (myproject-dev-IamRoleLambda-5ABCDEFGH) and attempt to add the VPC settings in the Lambda console, the console complains "Your role does not have VPC permissions. Please go back and select "Basic with VPC" under the role dropdown to add these permissions.". Is it possible that the serverless-created roles don't have the right permissions? 

Thanks for your help. First started with serverless this morning and it's already really awesome. Thanks for your hard work!!

### LINKED ISSUE #2780: EC2 permissions for VPC not set on first deploy
Hi Guys,

I have multiple serverless projects up and running, but today I wanted to set up a new one, and I can't figured it out.

My project is inside a VPC, and I have a permission error on the "AWS::Lambda::Function" role:
> Your access has been denied by EC2, please make sure your function execution role have permission to CreateNetworkInterface. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.

But my serverless.yml is setup the same way than my working projects:

```yaml
service: AwesomeService
frameworkVersion: "=1.2.1"
custom: ${file(./environments/serverless/${env:NODE_ENV}.yml)}
provider:
  name: aws
  cfLogs: true
  runtime: nodejs4.3
  region: eu-central-1
  stage: ${self:custom.stage}
  memorySize: ${self:custom.memorySize}
  timeout: ${self:custom.timeout}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
  vpc: ${self:custom.vpc}
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: post
          path: hello
          cors: true
          integration: lambda
```

As you can see, I clearly set the iamRoleStatements for EC2. Moreover, I read this in the documentation:
> Further, if you have specified VPC security groups and subnets for your lambdas to use then the EC2 rights necessary to attach to the VPC via an ENI will be added into the default IAM policy.

But when the role is created, the inline policy attached is the following:
```json
{
	"Version": "2012-10-17",
	"Statement": [{
		"Action": ["logs:CreateLogGroup", "logs:CreateLogStream"],
		"Resource": ["arn:aws:logs:eu-central-1:111118746979:log-group:/aws/lambda/AwesomeService-development-hello:*"],
		"Effect": "Allow"
	}, {
		"Action": ["logs:PutLogEvents"],
		"Resource": ["arn:aws:logs:eu-central-1:111118746979:log-group:/aws/lambda/AwesomeService-development-hello:*:*"],
		"Effect": "Allow"
	}]
}
```

No rights about EC2 are added...
Does anyone have an idea?

Many thanks

### LINKED ISSUE #2830: report error when we cannot delete a network interface
So I found out about this from our AWS account manager when I exceeded quota.

Running serverless deploy with the VPC, SecurityGroupIds, and SubnetIds defined seems to create a new network interface on each deploy, but doesn't clean up old, unused network interfaces.    

This is happening in 1.1.0.

Is this a known issue?

### LINKED ISSUE #2856: BREAKING - [1.3.0] IAM role name is to long if service + stage is more than 37 characters
# This is a Bug Report

## Description

* What went wrong?

Deployment failed due to having an IAM role that was to long (over 64 characters):

```
sls deploy                    
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (274 B)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.......Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: IamRoleLambdaExecution
     - 1 validation error detected: Value 'this-string-is-one-character-over-stage-ap-southeast-2-lambdaRole'
     at 'roleName' failed to satisfy constraint: Member must
     have length less than or equal to 64.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.3.0
 
```

* What did you expect should have happened?

Should have deployed successfully. `v1.2.1` still deploys successfully with a role name of `this-string-is-one-characte-IamRoleLambdaExecution-123456ABCDEFG`

I don't know if going back to what it was is the answer (I'm not sure what the purpose behind the changes was) but that be sufficient for me.

* What was the config you used?

```yml
service: this-string-is-one-character-over
provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-2
  stage: stage
functions:
  'helloworld':
    events:
      - http: GET helloworld
    handler: handler.handler
```

* What stacktrace or error message from your provider did you see?

> An error occurred while provisioning your stack: IamRoleLambdaExecution - 1 validation error detected: Value 'this-string-is-one-character-over-stage-ap-southeast-2-lambdaRole' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64.

Similar or dependent issues:

N/A

## Additional Data

* ***Serverless Framework Version you're using***: `v1.3.0`
* ***Operating System***: `darwin`
* ***Stack Trace***: N/A
* ***Provider Error messages***: 
> An error occurred while provisioning your stack: IamRoleLambdaExecution - 1 validation error detected: Value 'this-string-is-one-character-over-stage-ap-southeast-2-lambdaRole' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64.

### PR DESCRIPTION
**Pull request by nicka**
## What did you implement:

Closes #1786 
Closes #2780 
Closes #2830

## How did you implement it:

- Migrated the `IamPolicyLambdaExecution` resource statements towards inline polices within the `IamRoleLambdaExecution` resource to fix CloudFormation dependency issues. As a bonues, we save an extra CloudFormation resource.
-  Added the `ManagedPolicyArns` property to `IamRoleLambdaExecution` resource when VPC config is provided.
- Improved [logic](https://github.com/serverless/serverless/pull/2983/files#diff-e7c535e2a3417a31b2ce07a09b731acdR24) which checks if all functions contain a custom role, in which case we skip creation of the `IamRoleLambdaExecution` resource.

**NOTE:** This might be a breaking change since users could be referecing to the `IamPolicyLambdaExecution` policy which this PR removes.

## Research

Adding VPC config to an existing stack still occasionally fails with the ec2 permissions issue. As a solution to this I will try to work with [ManagedPolicyArns](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-managepolicyarns). Each account should come with a default `arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole` by AWS which could be used within the `ManagedPolicyArns` property.

**Update 1:**
The `ManagedPolicyArns` with the default `AWSLambdaVPCAccessExecutionRole` works!!!

**Update 2:**
`ManagedPolicyArns` has been added as a default when vpc config is provided.

## How can we verify

- [x] Real-life test create/update stack
- [x] Real-life test create/update stack - with VPC provider level
- [x] Real-life test create/update stack - with VPC functional level
- [x] Real-life test create/update stack - with role provider level
- [x] Real-life test create/update stack - with multiple functions with one having a role
- [x] Real-life test create/update stack - with multiple functions all having a role
- [x] Real-life test create/update stack - with custom provider iamRoleStatements
- [ ] Real-life test create/update stack - with Kinesis stream
- [ ] Real-life test create/update stack - with DyanomoDB stream

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by nicka** [comment]
**Diff against deployed stack:**

```
{
   Resources: {
-    IamPolicyLambdaExecution: {
-      Type: "AWS::IAM::Policy"
-      DependsOn: [
-        "IamRoleLambdaExecution"
-      ]
-      Properties: {
-        PolicyName: {
-          Fn::Join: [
-            "-"
-            [
-              "test"
-              "bandlab-resty"
-              "lambda"
-            ]
-          ]
-        }
-        PolicyDocument: {
-          Version: "2012-10-17"
-          Statement: [
-            {
-              Effect: "Allow"
-              Action: [
-                "logs:CreateLogGroup"
-                "logs:CreateLogStream"
-              ]
-              Resource: [
-                {
-                  Fn::GetAtt: [
-                    "ServiceLogGroup"
-                    "Arn"
-                  ]
-                }
-              ]
-            }
-            {
-              Effect: "Allow"
-              Action: [
-                "logs:PutLogEvents"
-              ]
-              Resource: [
-                {
-                  Fn::Join: [
-                    ":"
-                    [
-                      {
-                        Fn::GetAtt: [
-                          "ServiceLogGroup"
-                          "Arn"
-                        ]
-                      }
-                      "*"
-                    ]
-                  ]
-                }
-              ]
-            }
-            {
-              Effect: "Allow"
-              Action: [
-                "lambda:InvokeFunction"
-              ]
-              Resource: "arn:aws:lambda:ap-northeast-1:*:function:bandlab-bands-*"
-            }
-          ]
-        }
-        Roles: [
-          {
-            Ref: "IamRoleLambdaExecution"
-          }
-        ]
-      }
-    }
     IamRoleLambdaExecution: {
       Properties: {
+        Policies: [
+          {
+            PolicyName: {
+              Fn::Join: [
+                "-"
+                [
+                  "test"
+                  "bandlab-resty"
+                  "lambda"
+                ]
+              ]
+            }
+            PolicyDocument: {
+              Version: "2012-10-17"
+              Statement: [
+                {
+                  Effect: "Allow"
+                  Action: [
+                    "logs:CreateLogGroup"
+                    "logs:CreateLogStream"
+                  ]
+                  Resource: [
+                    {
+                      Fn::GetAtt: [
+                        "ServiceLogGroup"
+                        "Arn"
+                      ]
+                    }
+                  ]
+                }
+                {
+                  Effect: "Allow"
+                  Action: [
+                    "logs:PutLogEvents"
+                  ]
+                  Resource: [
+                    {
+                      Fn::Join: [
+                        ":"
+                        [
+                          {
+                            Fn::GetAtt: [
+                              "ServiceLogGroup"
+                              "Arn"
+                            ]
+                          }
+                          "*"
+                        ]
+                      ]
+                    }
+                  ]
+                }
+                {
+                  Effect: "Allow"
+                  Action: [
+                    "lambda:InvokeFunction"
+                  ]
+                  Resource: "arn:aws:lambda:ap-northeast-1:*:function:bandlab-bands-*"
+                }
+              ]
+            }
+          }
+        ]
       }
     }
   }
 }
```

**Create stack non-vpc:** 

```
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersionms0WgVsdL6mHLeyy0TGHwAAsl1td2xsfCL5S2prQ
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-migrator-test
Serverless: Stack create finished...
```

**Create stack vpc:** 

```
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersionfs0KdDY9eM6nbOpZWasxzVRrBanCtm17wBiDKbtgKlw
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-migrator-test
Serverless: Stack create finished...
```

**Update stack non-vpc:** 

```
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-resty-test
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ServiceLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - ServiceLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ServiceLambdaVersionY5LrdQpEdSiE3Qd5iCM07fIl31pGOBjuzTUZ09vmOvE
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ServiceLambdaVersionY5LrdQpEdSiE3Qd5iCM07fIl31pGOBjuzTUZ09vmOvE
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - ServiceLambdaVersionY5LrdQpEdSiE3Qd5iCM07fIl31pGOBjuzTUZ09vmOvE
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482183277780
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482183277780
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482183277780
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-resty-test
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482138138120
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - ServiceLambdaVersionQWtPf0uFghON9bTACkvi9ofHudry3jCM5wmQjmpMQ
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482138138120
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-resty-test
Serverless: Stack update finished...
```

**Update stack vpc:** 

Again, sometimes it goes through, sometimes it fails.

```
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - bandlab-migrator-test
Serverless: Deployment failed!
```

```
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersionujkBUTd99gyT7deEDqTXDxWrzrs605Y4yWqNKQC0o
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersionujkBUTd99gyT7deEDqTXDxWrzrs605Y4yWqNKQC0o
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersionujkBUTd99gyT7deEDqTXDxWrzrs605Y4yWqNKQC0o
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersionujkBUTd99gyT7deEDqTXDxWrzrs605Y4yWqNKQC0o
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-migrator-test
Serverless: Stack update finished...
```

Working with `ManagedPolicyArns`:

```
{
   Resources: {
     IamRoleLambdaExecution: {
       Properties: {
+        ManagedPolicyArns: [
+          "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
+        ]
         Policies: [
           {
             PolicyDocument: {
               Statement: [
                 ...
                 ...
-                {
-                  Effect: "Allow"
-                  Action: [
-                    "ec2:CreateNetworkInterface"
-                    "ec2:DescribeNetworkInterfaces"
-                    "ec2:DeleteNetworkInterface"
-                  ]
-                  Resource: "*"
-                }
               ]
             }
           }
         ]
       }
     }
   }
 }
```

```
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersionG3waUdlL6q5G0ZDLIuWj6gTOg3Mu8DlyfNVsvsVCc
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersioniJQtsjzjCruxCXTC5nWjBm2eaXEoBFrsAYHVlNJKCQc
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-migrator-test
Serverless: Stack update finished...
```

**Comment by mthenw** [comment]
@nicka

**Comment by erikerikson** [comment]
Rockin'!  This has been needed for a very long while!

File: lib/plugins/aws/deploy/lib/mergeIamTemplates.js [hunk 1]
```diff
@@ -11,131 +11,141 @@ module.exports = {
   },
 
   merge() {
+    // resolve early if no functions are provided
     if (!this.serverless.service.getAllFunctions().length) {
       return BbPromise.resolve();
     }
 
-    let anyFunctionHasNoRole = false;
```
Comment (nicka) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: @pmuens @eahefnawy @mthenw I updated this logic as it seemed to be broken, or my brain didn't compute 😊

**Comment by nicka** [comment]
@pmuens @eahefnawy @mthenw I added the `ManagedPolicyArns` property to the `IamRoleLambdaExecution` resource by default in case vpc config is provided

**Comment by nicka** [comment]
Damn you old node versions 😂

**Comment by nicka** [comment]
✅ **Test create stack:**
- No vpc
- No custom roles

```
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersionGROnjlWcyx1P4CJtD9JiErDoONV2ohlNWM6VmnDQ
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-migrator-test
Serverless: Stack create finished...
```

**Comment by nicka** [comment]
✅ **Test update stack:**

- No vpc
- No custom roles

```
{
   Resources: {
-    IamPolicyLambdaExecution: {
-      Type: "AWS::IAM::Policy"
-      DependsOn: [
-        "IamRoleLambdaExecution"
-      ]
-      Properties: {
-        PolicyName: {
-          Fn::Join: [
-            "-"
-            [
-              "test"
-              "bandlab-graphql"
-              "lambda"
-            ]
-          ]
-        }
-        PolicyDocument: {
-          Version: "2012-10-17"
-          Statement: [
-            {
-              Effect: "Allow"
-              Action: [
-                "logs:CreateLogGroup"
-                "logs:CreateLogStream"
-              ]
-              Resource: [
-                {
-                  Fn::GetAtt: [
-                    "GraphqlLogGroup"
-                    "Arn"
-                  ]
-                }
-              ]
-            }
-            {
-              Effect: "Allow"
-              Action: [
-                "logs:PutLogEvents"
-              ]
-              Resource: [
-                {
-                  Fn::Join: [
-                    ":"
-                    [
-                      {
-                        Fn::GetAtt: [
-                          "GraphqlLogGroup"
-                          "Arn"
-                        ]
-                      }
-                      "*"
-                    ]
-                  ]
-                }
-              ]
-            }
-            {
-              Effect: "Allow"
-              Action: [
-                "lambda:InvokeFunction"
-              ]
-              Resource: [
-                "arn:aws:lambda:ap-northeast-1:*:function:bandlab-prelude-*"
-                "arn:aws:lambda:ap-northeast-1:*:function:bandlab-bands-*"
-              ]
-            }
-          ]
-        }
-        Roles: [
-          {
-            Ref: "IamRoleLambdaExecution"
-          }
-        ]
-      }
-    }
-    GraphqlLambdaVersionPfV234yhWmg6OO8s6WbAoioZy9WFYIzgVoUhp0UF8: {
-      Type: "AWS::Lambda::Version"
-      DeletionPolicy: "Retain"
-      Properties: {
-        FunctionName: {
-          Ref: "GraphqlLambdaFunction"
-        }
-        CodeSha256: "PfV234yhWmg6OO8s6WbAoioZy9W/FYIzgVoUh+p0UF8="
-      }
-    }
-    ApiGatewayDeployment1482137983349: {
-      Type: "AWS::ApiGateway::Deployment"
-      Properties: {
-        RestApiId: {
-          Ref: "ApiGatewayRestApi"
-        }
-        StageName: "test"
-      }
-      DependsOn: [
-        "ApiGatewayMethodProxyVarAny"
-      ]
-    }
+    GraphqlLambdaVersionVyCEhtC2R76OpgaQHvqtfPVDiB73yNjWTYwjPFRU: {
+      Type: "AWS::Lambda::Version"
+      DeletionPolicy: "Retain"
+      Properties: {
+        FunctionName: {
+          Ref: "GraphqlLambdaFunction"
+        }
+        CodeSha256: "VyCEhtC2R76/OpgaQHvqtfPVDiB73/yNjWTYw+jPFRU="
+      }
+    }
+    ApiGatewayDeployment1482311955147: {
+      Type: "AWS::ApiGateway::Deployment"
+      Properties: {
+        RestApiId: {
+          Ref: "ApiGatewayRestApi"
+        }
+        StageName: "test"
+      }
+      DependsOn: [
+        "ApiGatewayMethodProxyVarAny"
+      ]
+    }
     IamRoleLambdaExecution: {
       Properties: {
+        Policies: [
+          {
+            PolicyName: {
+              Fn::Join: [
+                "-"
+                [
+                  "test"
+                  "bandlab-graphql"
+                  "lambda"
+                ]
+              ]
+            }
+            PolicyDocument: {
+              Version: "2012-10-17"
+              Statement: [
+                {
+                  Effect: "Allow"
+                  Action: [
+                    "logs:CreateLogGroup"
+                    "logs:CreateLogStream"
+                  ]
+                  Resource: [
+                    {
+                      Fn::GetAtt: [
+                        "GraphqlLogGroup"
+                        "Arn"
+                      ]
+                    }
+                  ]
+                }
+                {
+                  Effect: "Allow"
+                  Action: [
+                    "logs:PutLogEvents"
+                  ]
+                  Resource: [
+                    {
+                      Fn::Join: [
+                        ":"
+                        [
+                          {
+                            Fn::GetAtt: [
+                              "GraphqlLogGroup"
+                              "Arn"
+                            ]
+                          }
+                          "*"
+                        ]
+                      ]
+                    }
+                  ]
+                }
+                {
+                  Effect: "Allow"
+                  Action: [
+                    "lambda:InvokeFunction"
+                  ]
+                  Resource: [
+                    "arn:aws:lambda:ap-northeast-1:*:function:bandlab-prelude-*"
+                    "arn:aws:lambda:ap-northeast-1:*:function:bandlab-bands-*"
+                  ]
+                }
+              ]
+            }
+          }
+        ]
       }
     }
     GraphqlLambdaFunction: {
       Properties: {
         Code: {
-          S3Key: "serverless/bandlab-graphql/test/1482137983324-2016-12-19T08:59:43.324Z/bandlab-graphql.zip"
+          S3Key: "serverless/bandlab-graphql/test/1482311955133-2016-12-21T09:19:15.133Z/bandlab-graphql.zip"
         }
       }
       DependsOn: [
-        "IamPolicyLambdaExecution"
         "IamRoleLambdaExecution"
       ]
     }
   }
   Outputs: {
     GraphqlLambdaFunctionQualifiedArn: {
       Value: {
-        Ref: "GraphqlLambdaVersionPfV234yhWmg6OO8s6WbAoioZy9WFYIzgVoUhp0UF8"
+        Ref: "GraphqlLambdaVersionVyCEhtC2R76OpgaQHvqtfPVDiB73yNjWTYwjPFRU"
       }
     }
   }
 }
```

```
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-graphql-test
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - GraphqlLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - GraphqlLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - GraphqlLambdaVersionZ0taShAf8QYwVKYm0MXVW17uEPa1hcUkoVXULWBpcRw
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - GraphqlLambdaVersionZ0taShAf8QYwVKYm0MXVW17uEPa1hcUkoVXULWBpcRw
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - GraphqlLambdaVersionZ0taShAf8QYwVKYm0MXVW17uEPa1hcUkoVXULWBpcRw
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482311961537
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482311961537
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482311961537
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-graphql-test
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - GraphqlLambdaVersionPfV234yhWmg6OO8s6WbAoioZy9WFYIzgVoUhp0UF8
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482137983349
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1482137983349
CloudFormation - DELETE_COMPLETE - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-graphql-test
Serverless: Stack update finished...
```

**Comment by nicka** [comment]
✅ **Test create stack**

- VPC provider level
- No custom roles

```
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersionGTJAtaZEJu61vuDngsqR4MIbwmSrJkmDwkIsS2L74
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-migrator-test
Serverless: Stack create finished...
```

**Comment by nicka** [comment]
✅ **Test create stack:**

- VPC functional level
- No custom roles

```
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - SeedLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - RollbackLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - MigrateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CurrentVersionLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersionzECMyuKWuyGmLtbhpD1daaLRS8QScLi0aEfRGPmJq3A
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-migrator-test
Serverless: Stack create finished...
```

**Comment by nicka** [comment]
✅ **Test update existing stack:**

- VPC provider level
- No custom roles

```
{
   Resources: {
-    MigrateLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc: {
-      Type: "AWS::Lambda::Version"
-      DeletionPolicy: "Retain"
-      Properties: {
-        FunctionName: {
-          Ref: "MigrateLambdaFunction"
-        }
-        CodeSha256: "9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc="
-      }
-    }
-    SeedLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc: {
-      Type: "AWS::Lambda::Version"
-      DeletionPolicy: "Retain"
-      Properties: {
-        FunctionName: {
-          Ref: "SeedLambdaFunction"
-        }
-        CodeSha256: "9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc="
-      }
-    }
-    CurrentVersionLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc: {
-      Type: "AWS::Lambda::Version"
-      DeletionPolicy: "Retain"
-      Properties: {
-        FunctionName: {
-          Ref: "CurrentVersionLambdaFunction"
-        }
-        CodeSha256: "9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc="
-      }
-    }
-    RollbackLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc: {
-      Type: "AWS::Lambda::Version"
-      DeletionPolicy: "Retain"
-      Properties: {
-        FunctionName: {
-          Ref: "RollbackLambdaFunction"
-        }
-        CodeSha256: "9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc="
-      }
-    }
+    MigrateLambdaVersionBYrGJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0bkjI: {
+      Type: "AWS::Lambda::Version"
+      DeletionPolicy: "Retain"
+      Properties: {
+        FunctionName: {
+          Ref: "MigrateLambdaFunction"
+        }
+        CodeSha256: "BYr/GJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0b+kjI="
+      }
+    }
+    SeedLambdaVersionBYrGJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0bkjI: {
+      Type: "AWS::Lambda::Version"
+      DeletionPolicy: "Retain"
+      Properties: {
+        FunctionName: {
+          Ref: "SeedLambdaFunction"
+        }
+        CodeSha256: "BYr/GJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0b+kjI="
+      }
+    }
+    CurrentVersionLambdaVersionBYrGJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0bkjI: {
+      Type: "AWS::Lambda::Version"
+      DeletionPolicy: "Retain"
+      Properties: {
+        FunctionName: {
+          Ref: "CurrentVersionLambdaFunction"
+        }
+        CodeSha256: "BYr/GJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0b+kjI="
+      }
+    }
+    RollbackLambdaVersionBYrGJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0bkjI: {
+      Type: "AWS::Lambda::Version"
+      DeletionPolicy: "Retain"
+      Properties: {
+        FunctionName: {
+          Ref: "RollbackLambdaFunction"
+        }
+        CodeSha256: "BYr/GJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0b+kjI="
+      }
+    }
     IamRoleLambdaExecution: {
       Properties: {
+        ManagedPolicyArns: [
+          "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
+        ]
       }
     }
     MigrateLambdaFunction: {
       Properties: {
+        VpcConfig: {
+          SecurityGroupIds: [
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-DatabaseSecurityGroup"
+            }
+          ]
+          SubnetIds: [
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetAPublic"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetAPrivate"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetBPublic"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetBPrivate"
+            }
+          ]
+        }
         Code: {
-          S3Key: "serverless/bandlab-migrator/test/1482312909154-2016-12-21T09:35:09.154Z/bandlab-migrator.zip"
+          S3Key: "serverless/bandlab-migrator/test/1482313440629-2016-12-21T09:44:00.629Z/bandlab-migrator.zip"
         }
       }
     }
     SeedLambdaFunction: {
       Properties: {
+        VpcConfig: {
+          SecurityGroupIds: [
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-DatabaseSecurityGroup"
+            }
+          ]
+          SubnetIds: [
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetAPublic"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetAPrivate"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetBPublic"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetBPrivate"
+            }
+          ]
+        }
         Code: {
-          S3Key: "serverless/bandlab-migrator/test/1482312909154-2016-12-21T09:35:09.154Z/bandlab-migrator.zip"
+          S3Key: "serverless/bandlab-migrator/test/1482313440629-2016-12-21T09:44:00.629Z/bandlab-migrator.zip"
         }
       }
     }
     CurrentVersionLambdaFunction: {
       Properties: {
+        VpcConfig: {
+          SecurityGroupIds: [
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-DatabaseSecurityGroup"
+            }
+          ]
+          SubnetIds: [
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetAPublic"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetAPrivate"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetBPublic"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetBPrivate"
+            }
+          ]
+        }
         Code: {
-          S3Key: "serverless/bandlab-migrator/test/1482312909154-2016-12-21T09:35:09.154Z/bandlab-migrator.zip"
+          S3Key: "serverless/bandlab-migrator/test/1482313440629-2016-12-21T09:44:00.629Z/bandlab-migrator.zip"
         }
       }
     }
     RollbackLambdaFunction: {
       Properties: {
+        VpcConfig: {
+          SecurityGroupIds: [
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-DatabaseSecurityGroup"
+            }
+          ]
+          SubnetIds: [
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetAPublic"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetAPrivate"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetBPublic"
+            }
+            {
+              Fn::ImportValue: "bandlab-aws-resources-test-VpcSubnetBPrivate"
+            }
+          ]
+        }
         Code: {
-          S3Key: "serverless/bandlab-migrator/test/1482312909154-2016-12-21T09:35:09.154Z/bandlab-migrator.zip"
+          S3Key: "serverless/bandlab-migrator/test/1482313440629-2016-12-21T09:44:00.629Z/bandlab-migrator.zip"
         }
       }
     }
   }
   Outputs: {
     MigrateLambdaFunctionQualifiedArn: {
       Value: {
-        Ref: "MigrateLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc"
+        Ref: "MigrateLambdaVersionBYrGJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0bkjI"
       }
     }
     SeedLambdaFunctionQualifiedArn: {
       Value: {
-        Ref: "SeedLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc"
+        Ref: "SeedLambdaVersionBYrGJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0bkjI"
       }
     }
     CurrentVersionLambdaFunctionQualifiedArn: {
       Value: {
-        Ref: "CurrentVersionLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc"
+        Ref: "CurrentVersionLambdaVersionBYrGJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0bkjI"
       }
     }
     RollbackLambdaFunctionQualifiedArn: {
       Value: {
-        Ref: "RollbackLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc"
+        Ref: "RollbackLambdaVersionBYrGJZGkN8qxG1PZsQpMMMr9m2Awptb5AyEi0bkjI"
       }
     }
   }
 }
```

```
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - CurrentVersionLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MigrateLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - RollbackLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - SeedLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - RollbackLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CurrentVersionLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MigrateLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SeedLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersionlkA35Z90eib93gn1y2NirbevuuGeJa4rEbMPbjMOtY
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - bandlab-migrator-test
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - SeedLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - CurrentVersionLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - RollbackLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - MigrateLambdaVersion9zqvhPl2nYztS4O4MAyV8zZJ5g0H4qA7tP093wkBitc
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - bandlab-migrator-test
Serverless: Stack update finished...
```

**Comment by nicka** [comment]
@serverless/team Successfully tested all stack create/update cases against actual stacks. This PR is now 100% ready for review 👍

**Comment by nicka** [comment]
@pmuens Any news on this?

**Comment by pmuens** [comment]
@nicka thanks for getting back.
We're currently working on the v1.5 release which is just around the corner 😸 

This PR is a great move towards v2 so we'll focus on this one soon! 👍

**Comment by pmuens** [comment]
Hey @nicka we finalized the decision to include this PR in v1.8!

Could you maybe look at the conflicts and resolve them 😬 . That would be super awesome 💯 

Sorry for any inconveniences. Let us know if you need any help and thanks in advance! 👍 

/cc @eahefnawy @brianneisler

**Comment by nicka** [comment]
@pmuens Sure think, will try my best to finish this by the end of this week.

**Comment by BardiaAfshin** [comment]
I'm working behind a company firewall and when I run

```bash
serverless deploy -v
```

I'm getting
```bash

  WARNING: You are running v1.7.0. v1.8.0 will include the following breaking changes:
    - Will replace IamPolicyLambdaExecution resource with inline policies -> https://git.io/vDilm
    - "sls info" will output the short function name rather than the lambda name -> https://git.io/vDiWx

  You can opt-out from these warnings by setting the "SLS_IGNORE_WARNING=*" environment variable.
```

I just installed serverless npm module, why am I getting a old module to begin with?

**Comment by dannycohn** [comment]
You are not getting an old version. This is a warning that the next version will have breaking changes to give you time to adjust.

**Comment by nicka** [comment]
@pmuens @mthenw @erikerikson Rebased on top of master (the merge conflicts where hell), def needs some love and testing before merging!

File: lib/plugins/aws/deploy/lib/mergeIamTemplates.js [hunk 2]
```diff
@@ -11,6 +11,47 @@ module.exports = {
...
+      .PolicyName = this.provider.naming.getPolicyName();
+
+    _.merge(
+      this.serverless.service.provider.compiledCloudFormationTemplate.Resources,
+      {
+        [this.provider.naming.getRoleLogicalId()]: iamRoleLambdaExecutionTemplate,
+      }
+    );
+
     this.serverless.service.getAllFunctions().forEach((functionName) => {
```
Comment (eahefnawy) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: This code block must be at the very beginning of the `merge()` method, otherwise bug #3174 will resurface. In other words, now that we *always* use log group resources, they must be merged regardless of whether we're using custom or default roles.

Comment (nicka) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: I'm not sure if I completely follow because of all the prior checks:
```js
// resolve early if no functions are provided
// resolve early if provider level role is provided
// resolve early if all functions contain a custom role
```

If we're talking purely about Log groups and assuming the user is providing his own IAM statement to put logs the following code block:
```js
this.serverless.service.getAllFunctions().forEach((functionName) => {
      const functionObject = this.serverless.service.getFunction(functionName);
      const logGroupLogicalId = this.provider.naming
        .getLogGroupLogicalId(functionName);
      const newLogGroup = {
        [logGroupLogicalId]: {
          Type: 'AWS::Logs::LogGroup',
          Properties: {
            LogGroupName: this.provider.naming.getLogGroupName(functionObject.name),
          },
        },
      };
      _.merge(this.serverless.service.provider.compiledCloudFormationTemplate.Resources,
        newLogGroup);
});
```
might come between:
```js
// resolve early if no functions are provided
// HEREEEEEE
// resolve early if provider level role is provided
```

Comment (eahefnawy) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: @nicka yep exactly ... what we're trying to avoid is to resolving early *before* getting the chance to merge the LogGroup, which must be merged regardless of the what role we're using.

Comment (nicka) [inline lib/plugins/aws/deploy/lib/mergeIamTemplates.js]: Ok, I'll update the flow 👍

**Comment by eahefnawy** [comment]
@nicka added another comment. Sorry for the hassle 🙌

File: lib/plugins/aws/deploy/lib/iam-role-lambda-execution-template.json [hunk 3]
```diff
@@ -16,6 +16,31 @@
...
+              "Effect": "Allow",
+              "Action": [
+                "logs:PutLogEvents"
+              ],
+              "Resource": []
+            }
+          ]
+        }
+      }
+    ]
```
Comment (nicka) [inline lib/plugins/aws/deploy/lib/iam-role-lambda-execution-template.json]: Makes total sense to update, especially if were ALWAYS creating the log groups. Will only keep `CreateLogStream` and `PutLogEvents` then.

Comment (nicka) [inline lib/plugins/aws/deploy/lib/iam-role-lambda-execution-template.json]: Might still need two because of `/*` within IAM. What do you think?

Comment (eahefnawy) [inline lib/plugins/aws/deploy/lib/iam-role-lambda-execution-template.json]: aaah right I think you're right! 😊

Comment (nicka) [inline lib/plugins/aws/deploy/lib/iam-role-lambda-execution-template.json]: Sorry for the delay, switched MacBook's etc. Will work on the updates.

**Comment by nicka** [comment]
@eahefnawy Updated!

**Comment by AndrewFarley** [comment]
My stacks aren't complex, but I confirm this fixes the problem for me for my projects that functions in a VPC during initial creation!  +1 here, good job, can't wait for it in next release.  Cheers!

**Comment by nicka** [comment]
Woehoe!!!

File: lib/plugins/aws/deploy/lib/iam-role-lambda-execution-template.json (hunk 3 above)
Comment (erikerikson) [inline lib/plugins/aws/deploy/lib/iam-role-lambda-execution-template.json]: @eahefnawy using two was important because the use of star would give creation rights to any log group with the same prefix.  but as you note, it is legacy that can be removed now that explicit log group creation happens.

There's a bit more paranoia not in there though...  Here is our latest:
```
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                  Resource:
                    - Fn::GetAtt:
                      - TheLogGroup
                      - Arn
                - Effect: Allow
                  Action:
                    - logs:PutLogEvents
                  Resource:
                    - Fn::Join:
                      - ":"
                      - - Fn::GetAtt:
                          - TheLogGroup
                          - Arn
                        - "*"
```
This way, the lambda can't create log streams in any similarly-prefixed-but-not-the-log-group-that-has-been-created while still being able to create in the created log group and then write to any such log stream.

Comment (erikerikson) [inline lib/plugins/aws/deploy/lib/iam-role-lambda-execution-template.json]: small surface space but since we're choosing this for all users and we can do it once and be done...  seems worth the energy.

Comment (erikerikson) [inline lib/plugins/aws/deploy/lib/iam-role-lambda-execution-template.json]: and... pretty sure it's my fault it's not already correct.  sorry for that
